### ISSUE TITLE
WPA2 packets with QOS service can not be decrypted

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1038]
**Reported by b0ukm4n on 10 Oct 2012 11:45 UTC**

In file crypto.c in function decrypt_ccmp(..) the optional QOS field of WPA2 packets is not considered. 

The two fixes would be (first line indicates where to add the second line):

1)
z= 24 + 6 * is_a4;
if ((h80211[& 0x80) == 0x80) z+=2;

2)
AAD[1](0]) = 22 + 6 * is_a4;
if ((h80211[& 0x80) == 0x80) AAD[1](0])+=2;

Cheers,
b0uk4m

**Comment by aircrack-ng** [comment]
**Comment by misterx on 10 Oct 2012 11:45 UTC**

Fixed typo in title.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 10 Oct 2012 11:45 UTC**

Milestone N/A deleted

**Comment by ChrisLundquist** [comment]
I believe this is fixed now. At least, there is code in that function regarding QoS
