### ISSUE TITLE
Make osdep a shared library

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1239]
**Reported by misterx on 4 Sep 2013 01:09 UTC**

Convert osdep from a static library to a shared one.

**Comment by aircrack-ng** [comment]
**Attachment by misterx on 4 Sep 2013 01:11 UTC**

Uploaded file [make_osdep_shared_Makefile.diff](https://github.com/aircrack-ng/trac-attachments/blob/master/1239/20130904-011110_614-make_osdep_shared_Makefile.diff)

Makefile: make osdep a shared library

**Comment by jbenden** [comment]
Is this still desired?

**Comment by aircrack-ng** [comment]
Yes

**Comment by jbenden** [comment]
The master branch now supports building shared libraries. Use the `--enable-shared` option to the `configure` script, to enable them.

They are not supported on Windows, because our project is not 100% DLL "safe" - per the Autotools documentation. This goal may be reached in the future, though.

**Comment by jbenden** [comment]
Windows is now supported in the master branch, too. I also updated the `README.md` file.
