### ISSUE TITLE
Run STACK against aircrack-ng

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1251]
**Reported by misterx on 30 Oct 2013 00:35 UTC**

STACK is a static checker that detects unstable code in C/C++ programs.

URL: http://css.csail.mit.edu/stack/

**Comment by aircrack-ng** [comment]
**Comment by misterx on 30 Oct 2013 00:35 UTC**

git://g.csail.mit.edu/stack

**Comment by gemesa** [comment]
The [original](https://github.com/xiw/stack/) STACK has been abandoned since 2014, I checked the 55 forks and [one of them](https://github.com/gou4shi1/stack) was "active" in 2019 for ~2 months. I think we can say this issue is obsolete and consider closing it.
