### ISSUE TITLE
Aircrack-ng fails to open a file with a ':' in the name

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1478]
**Reported by misterx on 23 Sep 2014 02:59 UTC**

After selecting the network, aircrack-ng fails to reopen the file to read it when the filename contains ':'.

**Comment by badrussians** [comment]
I think, that my found error has the same roots (so I'm writing here):
## aircrack-ng do not find passwords file, that name has comma ','.

`aircrack-ng 'capFile-01.cap' -w 'pass , words.txt' # pass,words.txt has comma in its name`

part of output:
> ERROR: Opening dictionary pass  failed (No such file or directory)
> ERROR: Opening dictionary  words.txt failed (No such file or directory)
> ERROR: Opening dictionary pass  failed (No such file or directory)
> ERROR: Opening dictionary  words.txt failed (No such file or directory)

**Comment by aircrack-ng** [comment]
The comma is used to separate dictionaries.

The original issue cannot be reproduced.
