### ISSUE TITLE
besside-ng fails when using TL-WN722N (ath9k_htc)

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1627]
**Reported by jeffree on 18 Sep 2015 13:16 UTC**

besside-ng fails when used with TP-LINK TL-WN722N (ath9k_htc) and Ubuntu 14.04, with messages "besside-ng: wi_read(): No such file or directory" on first run, and "besside-ng: wi_read(): No child processes" on subsequent runs.

'''The first time it is run:'''

'''Command:'''
```
besside-ng wlan2mon
```

'''result:'''
```
[Let's ride
[07:59:22](07:59:22]) Logging to besside.log
besside-ng: wi_read(): No such file or directory
```

'''Subsequent runs:'''

'''Command:'''
```
besside-ng wlan2mon
```

'''Result:'''
```
[Let's ride
[07:10:20](07:10:20]) Resuming from besside.log
[Appending to wpa.cap
[07:10:20](07:10:20]) Appending to wep.cap
[07:10:20] Logging to besside.log
besside-ng: wi_read(): No child processes
```

This error occurred only with the TL-WN722N (ath9k_htc). besside-ng worked properly with Alfa AWUS036H (rtl8187) and internal PCI-E Qualcomm Atheros AR9285 (ath9k). Tested with both Aircrack-ng 1.2 rc2 and latest svn, which is Aircrack-ng 1.2 rc2 aircrack-ng/aircrack-ng@3bbfac9a5b7e4b413affa6b32a9c08dd1268a494.

'''System details:'''

'''Linux distro:'''
```
Ubuntu 14.04
```
'''kernel:'''
```
3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:43:30 UTC 2015 i686 athlon i686 GNU/Linux
```

'''airmon-ng output:'''
```
PHY	Interface	Driver		Chipset

phy0	wlan0		ath9k		Qualcomm Atheros AR9285 Wireless Network Adapter (PCI-Express) (rev 01)
phy11	wlan1		rtl8187		Realtek Semiconductor Corp. RTL8187
phy10	wlan2mon	ath9k_htc	Atheros Communications, Inc. AR9271 802.11n
```

**Comment by aircrack-ng** [comment]
**Comment by misterx on 18 Sep 2015 13:16 UTC**

#1558 is similar, if not a duplicate.

**Comment by aircrack-ng** [comment]
**Comment by strasharo2000 on 18 Sep 2015 13:16 UTC**

Here's the fix for this issue, it's not accepted yet though:
https://github.com/aircrack-ng/aircrack-ng/pull/66

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 18 Sep 2015 13:16 UTC**

just re-install it that worked for me

**Comment by am3ience** [comment]
Just found this issue since i'm having it too, I'm unsure how to do a reinstall of besside-ng.

I did a "apt-get --purge remove aircrack-ng" then did an apt-get install, but besside-ng still doesn't work for me.

**Comment by aircrack-ng** [comment]
@am3ience this is a question for the forum. This is a bug tracker.

**Comment by aircrack-ng** [comment]
I assume we can close it since it worked fine for one user and other linked bugs are fixed.
