### ISSUE TITLE
Test and integrate jemalloc

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1648]
**Reported by misterx on 6 Dec 2015 07:09 UTC**

Test jemalloc and see if it is any useful: cpu usage improvement and/or memory usage improvement.

URL: http://www.canonware.com/jemalloc/

**Comment by aircrack-ng** [comment]
**Comment by misterx on 6 Dec 2015 07:09 UTC**

Also look at lockless allocator and tcmalloc.

**Comment by jbenden** [comment]
![workstation-jemalloc-master-7a87602](https://user-images.githubusercontent.com/73767/41752368-efc149fc-757b-11e8-8c49-d10140674528.png)

The bars around the dots are the error margins.

It would seem on my hardware that the native, system allocator performs better.

As always, test on your hardware; do not simply rely on published benchmarks.

**Comment by jbenden** [comment]
![workstation-tcmalloc-master-7a87602](https://user-images.githubusercontent.com/73767/41753958-51035f58-7585-11e8-8374-9d67e18f114b.png)

Once again, the system allocator wins. Note: I have not yet committed the changes for enabling `tcmalloc`, but they'll be in shortly.

As always, test on your hardware; do not simply rely on published benchmarks.
