### ISSUE TITLE
Create test system for Aircrack-ng

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1660]
**Reported by misterx on 31 Dec 2015 20:10 UTC**

Create a test system where I can simply toss patches at and it would test compile (and do make check too) it on different systems (BSD, Solaris, Linux, Cygwin) as well as different CPU architectures (using qemu; speed is not important).

It would most likely be using buildbots.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 31 Dec 2015 20:10 UTC**

Or maybe not buildbot since it depends on commits in svn.

Most likely custom web interface. It would allow uploading a patch, monitoring trac for new patch uploads (and github for PR and updated PR).

Two possible structures: either connect to build systems or build systems connect to it (every 5 mins).

Reporting would be done in a similar way to TravisCI, via email (if patch uploaded) and IRC bot.

**Comment by jbenden** [comment]
Is anything here still valid?

**Comment by aircrack-ng** [comment]
The last item would be setting up qemu systems for other systems. Everything else is pretty much implemented.

**Comment by jbenden** [comment]
TR;DL: This is very tricky to do and we have ARM BuildBots now.

We now have two different ARM systems in place, running BuildBot. I additionally do test the project on FreeBSD, from time to time.

If we have other architectures to test the project on, then Qemu booting to a Linux chroot, is viable.

Using Qemu to boot into FreeBSD isn't simple. In fact it has a lot of problem which make automating it reliably, difficult. For a starter, there is no 9P support; this makes copying the Travis project into the qcow2 the only great solution. To do this, we need NBB Linux driver. Not sure how that would go on Travis... Another is the whole of it would require complex Expect script processing; which I can do.

I think if you'd like BSD to be a part of CI testing, we should consider acquiring a small VM for which I could set up BuildBot on, connected to the BuildBot master machine. The downside to the solution is it would cost monthly money and a BSD VM is sometimes tough to come by. (FYI: OceanDigitial is a cheaper one!)

Thoughts, comments, suggestions are welcomed!
-Joe

**Comment by jbenden** [comment]
Is anything here still valid? Did we still need a QEMU setup?
