### ISSUE TITLE
Floating point exception on rpi2

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1666]
**Reported by ilvalle on 2 Feb 2016 20:12 UTC**

With the last git version ([2867]) compiled with sqlite=true I got
```
pi@apd ~/aircrack-ng/test $  aircrack-ng -r passphrases.db wpa.cap
Opening wpa.cap
Read 13 packets.

   #  BSSID              ESSID                     Encryption

   1  00:0D:93:EB:B0:8C  test                      WPA (1 handshake)

Choosing first network as target.

Opening wpa.cap
Floating point exceptionwait...

```

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 2 Feb 2016 20:12 UTC**

I received this issue too.
The command I ran used a wordlist instead:

aircrack-ng -w crunch.txt clean2.cap


Similar output, however I only had 3 packets in my cap file.

**Comment by aircrack-ng** [comment]
**Modified by misterx on 2 Feb 2016 20:12 UTC**

**Comment by aircrack-ng** [comment]
**Comment by misterx on 2 Feb 2016 20:12 UTC**

Does it still happen with current trunk/master?

**Comment by Aspect9** [comment]
Ive got a 30GB wordlist Aircrack-ng is having issues with - whats the play? how can i get it done - xtra dependencies? shell commands hey yo#

**Comment by aircrack-ng** [comment]
As mentioned in the previous comment (that is 2 years old), does it still happen when you use current master?

For the dependencies, check out the wiki and the INSTALLING file, they are very well documented there.

**Comment by aircrack-ng** [comment]
It still happens with current master on armhf
