### ISSUE TITLE
airodump-ng  cygwin_exception::open_stackdumpfile

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1684]
**Reported by anonymous on 20 Apr 2016 10:37 UTC**

airodump-ng 6676 cygwin_exception::open_stackdumpfile: Dumping stack trace to airodump-ng.exe.stackdump

**Comment by aircrack-ng** [comment]
**Attachment by anonymous on 20 Apr 2016 10:37 UTC**

Uploaded file [airodump-ng.exe.stackdump](https://github.com/aircrack-ng/trac-attachments/blob/master/1684/20160420-103753_098-airodump-ng.exe.stackdump)

**Comment by jbenden** [comment]
Does this problem still exist?

**Comment by aircrack-ng** [comment]
It was probably due to the CPU detection that built it with AVX2 where the system didn't support it. With the current build, it shouldn't be a problem.
