### ISSUE TITLE
Device chipset unrecognized

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1688]
**Reported by mben06 on 15 May 2016 18:23 UTC**

airmon-ng told me to report this:

airmon-ng doesn't seem to recognize my builtin wireless adapter on nexus 6 running kali nethunter but does recognize usb adapter. Builtin adapter shows:

PHY = phy0, Interface = wlan0, Driver = ??????, Chipset = non-mac80211 device?(report this!)

This isn't an issue for me since I only need my usb adapter for monitor mode(and that works perfect) but just reporting because it wanted me to..also, everytime I run, say... 'airmon-ng start wlan1' (or wlan1mon) it says "Found phy0 with no interfaces assigned, would like to assign one?" this shows even if I say yes then it lists my builtin adapter on phy0 and if I run again I get the same question. As far as my needs go though, everything appears to be working great! airmon gets my usb adapter into monitor mode and I can use it for my purposes, just wanted to report the chipset thing in case some recognition was missing that might affect something later on for yall.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 15 May 2016 18:23 UTC**

What version of aircrack-ng are you running?

Could you attach lsmod and dmesg?

**Comment by ZeroChaos-** [comment]
over a year old, no useful details
