### ISSUE TITLE
airmon-ng shows "non-mac80211 device?" for bcm4312 (14e4:4315)

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1697]
**Reported by ericbakuladavis on 2 Aug 2016 21:43 UTC**

'''OS:''' Kali Linux 2016.1 i366 Live USB (persistent)
'''kernel:''' 4.3.0-kali1-686-pae
'''aircrack-ng version:''' 1.2-rc3

```
# airmon-ng

PHY	Interface	Driver		Chipset

phy0	wlan0		b43		non-mac80211 device? (report this!)
```

```
# lspci -nn | grep Network
01:00.0 Network controller [Broadcom Corporation BCM4312 802.11b/g LP-PHY [14e4:4315](0280]:) (rev 01)
```

```
# lsmod | grep b43
b43                   393216  0
bcma                   45056  1 b43
mac80211              516096  1 b43
cfg80211              413696  2 b43,mac80211
rng_core               16384  1 b43
ssb                    57344  1 b43
mmc_core              102400  2 b43,ssb
pcmcia                 49152  2 b43,ssb
```

It seems to me that BCM4312 is a mac80211 device.

Same defect was reported and fixed in airmon-zc 1.2-beta1: #1233

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 2 Aug 2016 21:43 UTC**

can you find a way to fix this?

**Comment by MuhmmadNasir** [comment]
I am facing same issue and also I am newbie therefore struggling to solve this problem can you please guide me how to solve it. I have cloned the git repository i had downloaded it but don't know how to install it or where to replace files in system in order to patch it.I would appreciate if direct link to install it is being shared.

**Comment by MuhmmadNasir** [comment]
i am using this command wget   https://github.com/aircrack-ng/aircrack-ng.git
but don't know how to install it after download.

**Comment by kimocoder** [comment]
@MuhmmadNasir 

Not wget.. use "git clone https://github.com/aircrack-ng/aircrack-ng"
Then "cd aircrack-ng && ./autogen.sh" then "make && make install"

**Comment by MuhmmadNasir** [comment]
root@kali:~# wget   https://github.com/aircrack-ng/aircrack-ng.git
--2018-08-31 16:12:11--  https://github.com/aircrack-ng/aircrack-ng.git
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/aircrack-ng/aircrack-ng [following]
--2018-08-31 16:12:14--  https://github.com/aircrack-ng/aircrack-ng
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘aircrack-ng.git.1’

aircrack-ng.git.1       [ <=>                ] 151.59K  3.85KB/s    in 26s   

after all this I am still getting same error 
root@kali:~# airmon-ng start mon0

Found 3 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to run 'airmon-ng check kill'

  PID Name
 1229 NetworkManager
 1534 wpa_supplicant
 2241 dhclient

PHY	Interface	Driver		Chipset

phy0	wlan0		b43		non-mac80211 device? (report this!)

**Comment by kimocoder** [comment]
I said.. NOT wget . You have to clone with "git"

**Comment by MuhmmadNasir** [comment]
cd aircrack-ng && ./autogen.sh
Could not auto-detect 'libtoolize'; please install or specify the 'LIBTOOLIZE' environment variable.
Little Help required?
I had installed Libtoolize now aclocal is missing

**Comment by MuhmmadNasir** [comment]
root@kali:~/aircrack-ng# make && make install
make: *** No targets specified and no makefile found.  Stop.

**Comment by aircrack-ng** [comment]
check out the README.md in the directory, it tells you exactly what to run to install the requirements.

FYI, if you are running kali, the installed aircrack-ng should have the issue fixed, 1.2rc3 was a VERY old version.

**Comment by LiberationFrequency** [comment]
Same device, same issue on Arch Linux with aircrack-ng 1.4-1 and b43-firmware-6.30.163.46-1. It works so far, but it receives no data. Replacing the b43-firmware with broadcom-wl-dkms 6.30.223.271-18 works for me.

**Comment by LiberationFrequency** [comment]
I think you can close it. TCPdump and Wireshark also receive beacons, but no data. It is not a issue by aircrack-ng, either it is the kernel or the driver. Earlier it used to work with the same version of b43-firmware.

**Comment by dreamlayers** [comment]
I'm also getting "non-mac80211 device? (report this!)" for BCM4321 Dell Wireless 1500 Draft 802.11n WLAN Mini-Card. But that seems cosmetic, only related to information displayed to the user, and not related to actual packet capture. It is expecting `ethtool -i wlan0` to have a line saying `bus-info: bcma` but instead there is `bus-info: ssb0:0`.

I'm getting beacons, probe requests and probe responses, even though I know there is data on the network. But that is unrelated. Use the Broadcom proprietary driver as a workaround for that, eg. via broadcom-sta-dkms in Ubuntu.

**Comment by belugacrx** [comment]
Please help! I wanted to run aircrack-ng and getting this error. Or tell me another way to use aircrack-ng with monitor mode in android. ![Screenshot_2020-09-21-18-21-31-341_tech.ula.jpg](https://user-images.githubusercontent.com/71138336/93769689-cb748280-fc38-11ea-8830-9c4baec008c1.jpg)

**Comment by Diaz123-droid** [comment]
Same error here. Am running Kali on Dell latitude d630. Could it be that the machine is old?

**Comment by ZeroChaos-** [comment]
I see various issues in here, some related to android permissions issues (selinux probably).  The originally reported issue is tested and confirmed working at this time and all recent releases, so closing as obsolete
