### ISSUE TITLE
Don't keep adding mon to interface name when using airmon-ng

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1698]
**Reported by misterx on 2 Aug 2016 23:40 UTC**

Network managers have a tendency to move the interface back to managed mode  but since airmon-ng adds mon to the interface, it can get long.

See https://forum.aircrack-ng.org/index.php/topic,1394

On top of it, add a warning if there is an interface in managed mode that has mon at the end of it.

**Comment by ZeroChaos-** [comment]
the warning was added, as well as detection and handling for when modes switch unexpectedly.  The solution is "iw wlan0mon del" for now, and airmon-ng recreates the device at next run.
