### ISSUE TITLE
AVX2 support was not compiled in

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1715]
**Reported by guardiadfinanza on 14 Jan 2017 20:30 UTC**

```
[root@parrot][/home/user]
 #aircrack-ng -u
Vendor          = Intel
Model           = Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
Features        = MMX,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AES-NI,AVX,AVX2
Hyper-Threading = No
CPU frequency   = 801 MHz (Max: 3100 MHz)
CPU cores       = 4
SIMD size       = 8 (256 bit)
NOTE: Your processor is capable of AVX2 but AVX2 support was not compiled in!
Please send a copy of this output to the aircrack team to improve autodetection.
```

**Comment by aircrack-ng** [comment]
**Attachment by guardiadfinanza on 14 Jan 2017 20:31 UTC**

Uploaded file [at 2017-01-14 21-23-13.png](Screenshot)(https://github.com/aircrack-ng/trac-attachments/blob/master/1715/20170114-203106_398-Screenshot%20at%202017-01-14%2021-23-13.png)

aircrack-ng -u report

**Comment by aircrack-ng** [comment]
**Comment by misterx on 14 Jan 2017 20:30 UTC**

Reopen if you compiled it yourself.

**Comment by aircrack-ng** [comment]
**Modified by misterx on 14 Jan 2017 20:30 UTC**

**Comment by avangardistic** [comment]
Vendor          = Intel
Model           = Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Features        = MMX,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AES-NI,AVX,AVX2
Hyper-Threading = Yes
Logical CPUs    = 8
CPU cores       = 4
SIMD size       = 8 (256 bit)
NOTE: Your processor is capable of AVX2 but AVX2 support was not compiled in!
Please send a copy of this output to the aircrack team to improve autodetection.

**Comment by jbenden** [comment]
The string `NOTE: Your processor is capable of AVX2 but AVX2 support was not compiled in!` does not appear in the current master branch. Are you SURE you are using the current `master` branch?
