### ISSUE TITLE
airodump-ng Interfaces Windows

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1769]
**Reported by MaxLFarrell on 26 Feb 2016 18:11 UTC**

Using a awus036h adapter on windows 10 with the command
`airodump-ng --bssid xx:xx:xx:xx:xx:x "Wi-Fi 2"`
I am receiving the error
`Adapter <Wi-Fi 2> not supported`
However on aircrack's interface docs ([here](http://www.aircrack-ng.org/doku.php?id=compatibility_drivers)) it says 

> The Alfa AWUS036H is a very popular card with this chipset and it performs well the aircrack-ng suite.

What am I doing wrong?

**Comment by aircrack-ng** [comment]
**Comment by aircrack ng on 27 Feb 2016 13:30 UTC**

It works well on Linux. On Windows, as explained on our website, you have to have a special driver that allows monitor mode and develop your own DLL (or find it online) to help airodump-ng interact with the driver itself.

**Comment by EN10** [comment]
Or use CommView

**Comment by binarymaster** [comment]
@EN10 we don't have to use some suspicious proprietary things, see #1775.

**Comment by ahmed-tea** [comment]
> 
> 
> @EN10 we don't have to use some suspicious proprietary things, see #1775.

@EN10 
@binarymaster Why CommView is suspicious proprietary?

**Comment by templine** [comment]
not supported windows interfaces even in 2021

**Comment by aircrack-ng** [comment]
We actually do, through Airpcap devices. General [wifi adapter support](https://secwiki.org/w/Npcap/WiFi_adapters) is really poor on Windows where you need a specific driver version, and sometimes a specific windows version. Testing showed that even supposedly supported adapter don't always work.

Patches to add support for NPCAP are welcome.
