### ISSUE TITLE
[FEATURE REQUEST] Show stations only

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1776]
**Reported by MagixInTheAir on 4 May 2016 09:06 UTC**

Could it be possible to not show APs in airodump-ng but only stations ?
Thank you.

**Comment by aircrack-ng** [comment]
**Comment by ZeroChaos  on 6 May 2016 15:20 UTC**

it already is, RTFM

**Comment by techtox420** [comment]
I RTFM but I couldn't find anything. Google isn't helping either. Care to push me in the right direction?

**Comment by jbenden** [comment]
Hit `tab` while the program is running... Or at least I think it's `tab`.

**Comment by techtox420** [comment]
Thanks for the quick response! With tab I can mark an AP with the "m" key so that the clients connected to said AP are highlighted. Didn't know that but that's not exactly what I'm looking for. I just want the bottom list to show, not the the top one with the AP list.

**Comment by jbenden** [comment]
Try the `a` key...

**Comment by jbenden** [comment]
... and try it multiple times.

**Comment by techtox420** [comment]
Ah yes, as written in the man page. My god, I'm stupid. I read it, but too quickly. I thought the things listed were CIPHERS. Thank you very much man! Also, very apparant that I look stupid right now. You told me to try it multiple times, as if I'm a complete noob who doesn't understand how that works :P
