### ISSUE TITLE
IEEE oui.txt file is slow or impossible to download

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1792]
**Reported by jeffmcjunkin on 8 Mar 2017 18:28 UTC**

Whenever I install aircrack-ng, I notice the oui.txt file from http://standards-oui.ieee.org/oui/oui.txt can take a long time to download, or even fail entirely. 

From my local Charter connection:
```
$ time wget 'http://standards-oui.ieee.org/oui/oui.txt'
--2017-03-08 10:09:13--  http://standards-oui.ieee.org/oui/oui.txt
Resolving standards-oui.ieee.org (standards-oui.ieee.org)... 140.98.193.27
Connecting to standards-oui.ieee.org (standards-oui.ieee.org)|140.98.193.27|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-03-08 10:16:06--  (try: 2)  http://standards-oui.ieee.org/oui/oui.txt
Connecting to standards-oui.ieee.org (standards-oui.ieee.org)|140.98.193.27|:80... connected.
HTTP request sent, awaiting response... 
```
From a fast Linode VPS:
```
# time curl 'http://standards-oui.ieee.org/oui/oui.txt' >/dev/null
real	2m26.495s
user	0m0.023s
sys	0m0.073s
```

Best case, this 3.5 megabyte file can download in 150 seconds, though commonly it fails to download entirely.

This isn't aircrack-ng's fault, but perhaps aircrack-ng could work around the IEEE issue. 

linuxnet.ca has a sanitized (fixing teh typos and such) mirror of the oui.txt file they maintain in several versions (bz2, gzip, zip, plaintext) at this site: http://linuxnet.ca/ieee/oui/. The plaintext version is directly available at http://linuxnet.ca/ieee/oui.txt. 

Perhaps you'd be willing to update `airodump-ng-oui-update` (https://github.com/aircrack-ng/aircrack-ng/blob/4d3d0ccaa4d67daa68f6fdbb6c13bf64debc6d27/scripts/airodump-ng-oui-update#L5) to point to this alternative URL? In my (admittedly limited) testing the typo-fixed version is an exact replacement.

Again from my local Charter connection:
```
$ time curl -s http://linuxnet.ca/ieee/oui.txt >/dev/null

real	0m5.870s
user	0m0.028s
sys	0m0.048s

$ time curl -s http://linuxnet.ca/ieee/oui.txt.bz2 | bzip2 -d >/dev/null

real	0m1.643s
user	0m0.172s
sys	0m0.012s
```

Ahh, much better.

**Comment by aircrack-ng** [comment]
**Comment by ZeroChaos  on 8 Mar 2017 22:46 UTC**

your distro should have a package containing this information.  if they don't, we get it from the original source.  I don't see a need to update.  Install the package from your distro.

**Comment by mshingote** [comment]
How often oui.txt is get updated?
