### ISSUE TITLE
Besside-ng: Added automatic channel detection of 2GHz and 5GHz channels

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1796]
**Reported by moonrk on 30 Apr 2017 20:11 UTC**

The channels in besside-ng were hardcoded from 1 to 11 unless using the -c option to lock to a specific channel.

I've made the necessary changes to detect the channels that the wifi adapter supports automatically, including 5GHz channels. The scanning process will thus be able to scan channels 1-14, 36-64, 100-144, 149-161 and 165 if they are supported.

This also fixes issue #106.

Tested on Alfa AWUS036NHA and Alfa AWUS036AC wifi adapters.

**Comment by aircrack-ng** [comment]
**Pull Request by moonrk on 30 Apr 2017 20:11 UTC**

Source Location: moonrk:master
Target Location: master

**Comment by aircrack-ng** [comment]
**Comment by strasharo on 2 May 2017 10:56 UTC**

Awesome, this works, just tested it on AWUS036H. Thanks a lot @moonrk .
@Mister-X- , can we have this merged, please? :)

**Comment by aircrack-ng** [comment]
**Comment by Mister X  on 2 May 2017 19:16 UTC**

It's nice to have it in bessides-ng but that needs to be global, in osdep, so airodump-ng can query it. And split it in 2 parts, 2.4GHz and 5GHz.

Other tools also need to be able to query which channels are available (to validate them), so a third function to check that in osdep would be useful.

**Comment by SymbianSyMoh** [comment]
I did this solution to temporary over come the issue :D 

![screen shot 2019-01-04 at 8 46 36 pm](https://user-images.githubusercontent.com/3141848/50719476-fd5b4500-1061-11e9-8ef9-bcd3428a0a59.png)
