### ISSUE TITLE
Add and fix prototypes in the codebase

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1798]
**Reported by neheb on 28 May 2017 20:00 UTC**

Found using -Wmissing-prototypes, -Wstrict-prototypes, and -Wmissing-declarations.

Compile tested but not runtime tested.

**Comment by aircrack-ng** [comment]
**Pull Request by neheb on 28 May 2017 20:00 UTC**

Source Location: neheb:master
Target Location: master

**Comment by aircrack-ng** [comment]
Interesting discussion in the response: https://stackoverflow.com/questions/9542031/no-previous-prototype

**Comment by jbenden** [comment]
This PR would need to be updated to the latest master branch. Additionally, when I attempted a test merge of this PR, I found that there were functions with missing prototypes still.

**Comment by aircrack-ng** [comment]
There is now a branch for this: [prototypes](../tree/prototypes).
