### ISSUE TITLE
Conflict in Airodump-ng when we have multiple Monitors from a wlan

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1828]
**Reported by alimp5 on 15 Feb 2018 08:39 UTC**

Greetings to Aircrack-ng Team,

for example, i want to scan two/three/... channels at the same time with a Wlan interface. So i created two interfaces in Monitor-Mode.
scenario: finding APs are in channel-4 and APs are in channel-10 (i don't want to use **-c** option in airodump-ng).

but when i run the second airodump CMD, I see APs are in channel-4 and channel-10 in both terminals. I don't want to have or see this situation. 
How I can fix this issue just via a Wlan interface !?

> 
> iw wlan1 interface add mon0 type monitor
> iw wlan1 interface add mon1 type monitor

note: I'm using 052-NH-v2 card.

iwconfig result:
```
wlan1     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=28 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

mon0      IEEE 802.11  Mode:Monitor  Tx-Power=28 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off
          
mon1      IEEE 802.11  Mode:Monitor  Tx-Power=28 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off
```

again,, How I can fix this issue just via a Wlan interface !?
at the end, it is possible !? or i should have another wifi card(s) !? [wlan1,.....](wlan0,)

https://imgur.com/a/Y0WRE

Thanks in advance.

**Comment by aircrack-ng** [comment]
**Comment by aircrack ng on 19 Feb 2018 18:35 UTC**

This is not a bug. A wireless card can only be on one channel at a time. You need multiple cards.

**Comment by ChillVibesMushroom** [comment]
> **Comment by aircrack ng on 19 Feb 2018 18:35 UTC**
> 
> This is not a bug. A wireless card can only be on one channel at a time. You need multiple cards.

If I have two cards for the same frequency how would I use both to dos pursuit would I just run airodump twice from both cards ?

**Comment by Mister-X-** [comment]
@ChillVibesMushroom This is a bug report. What you're asking should be a discussion.
