### ISSUE TITLE
Add buildbot for Intel Compiler

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1837]
We have testing with Travis and AppVeyor that covers clang and gcc.

We need to add Intel compiler. However, their licensing term don't allow using it with those 2 solutions above. We need to have an internal buildbot to handle the task in a similar way Travis and Appveyor work.

**Comment by jbenden** [comment]
A feasibility test shows that the Intel compiler *will* run inside of a Docker container. This means that it's possible for this project to succeed.

If this wasn't possible, the whole project wouldn't be...

**Comment by jbenden** [comment]
Operational!

https://buildbot.benden.us/

A badge URL is available too:

[![Intel Compiler Build Status](https://buildbot.benden.us/badges/aircrack-ng.png?left_text=Intel Compiler Build)](https://buildbot.benden.us/)

Added to `README.md` in ed876f53f63415d4b7592f1e900410bc27ac0086

**Comment by jbenden** [comment]
I had to commit 45104d433146527caedb44becd88fe75dbb5da62 to fix spaces in the markdown, that broke GitHub's rendering of the badge.
