### ISSUE TITLE
Support for HCCAPX targets

### ISSUE THREAD

**Issue by ChrisLundquist** [aircrack-ng/aircrack-ng#1841]
Currently there is support to write out HCCAP and HCCAPX file formats, but not to load them in.
On some devices it can be challenging to setup OpenCL (downloading the intel OpenCL SDK for on board graphics for instance, which is then about the same speed as CPUs), and sometimes not worth it when there are only CPUs.

The code in aircrack-ng.c is arguably a little complicated as it covers many concerns from packet parsing, to option parsing, to launching the actual attacks on WEP and WPA (all while being multithreaded).

There are two approaches I'd take to implement this support and I'd like feedback before pursuing one implementation or the other.

Option 1) without any feedback, I'd go for the "smallest viable change".
in `read_thread` and `check_thread` we have some duplication. Adding a `FORMAT_HCCAPX` to the logic on both sides, parsing out the HCAPPX file, converting them from `hccapx_t` into the aircrack structure (roughly the inverse of `do_make_hcappx`), then pushing them onto the `ap_1st` linked list.

This would  add some more duplication, but should be a ~50-100 line change with no major architecture changes.

Option 2) Split out the various loading mechanisms, (we have a few variations of IVS file, pcap file, etc) in a way to remove the duplication of logic between `read_thread` and `check_thread`. The interface could be "given an input file, return a list of `ap`s"

This would be a larger refactor and could introduce some regressions, it should cut down the size of the code though overall, even after adding support for HCCAPX.

Option 2 here has a larger window for merge conflicts as well.

I'm also not entirely clear on the differences between `check_thread` and `read_thread`. If a `bssid` isn't provided we launch N `check_threads`, and what appears to be N `read_threads` after it, but I'm not entirely clear what the difference is between them. Admittedly, I've only been looking at the file for about an hour.

Please let me know if you're interested in this feature, and which way you'd like to go implementation wise!
Thanks!

**Comment by aircrack-ng** [comment]
Option 2 is definitely better.

**Comment by ChrisLundquist** [comment]
Cool, I've implemented this support in the option 2 style and added the framework needed to make it easier to convert the existing loading methods.
https://github.com/aircrack-ng/aircrack-ng/pull/1844/files

**Comment by aircrack-ng** [comment]
Merged: 3e81718
