### ISSUE TITLE
32-bit macOS build failure

### ISSUE THREAD

**Issue by ryandesign** [aircrack-ng/aircrack-ng#1850]
Hi, building aircrack-ng 1.2-rc5 32-bit (`-arch i386`) fails on macOS 10.12.6:

```
libtool: link: ccache /usr/bin/clang++ -Wall -Wno-unused-command-line-argument -O3 -fstack-protector-strong -Wno-array-bounds -masm=intel -pipe -Os -stdlib=libc++ -arch i386 -Wl,-headerpad_max_install_names -arch i386 -o aircrack-ng--generic aircrack_ng__generic-aircrack-ng.o linecount.o  -L/opt/local/lib -lz -lsqlite3 ./.libs/libaclib.a ./.libs/libptw.a -lpthread -lssl -lcrypto -ldl -lm -pthread
Undefined symbols for architecture i386:
  "_GLOBAL_OFFSET_TABLE_", referenced from:
      _shasse2_init in libaclib.a(sha1-sse2.o)
      _shasse2_ends in libaclib.a(sha1-sse2.o)
      _shasse2_data in libaclib.a(sha1-sse2.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile:1637: aircrack-ng--generic] Error 1
```

Building 64-bit (`-arch x86_64`) succeeds.

**Comment by aircrack-ng** [comment]
What were the configure and make commands you ran?

**Comment by jbenden** [comment]
It is questionable to even support 32-bit macOS. All of the underlying system is full 64-bit for quite some time...

**Comment by jbenden** [comment]
PS: This would require assembly modifications in `src/sha1-sse2.S`. There is no entry for a 32-bit macOS PIC.

Also, not all x86 chips have SSE2; however, it could be a requirement for this case.

**Comment by ryandesign** [comment]
Not all users are able to afford recent Macs, and some users may wish to repurpose older Macs. The first models of Intel Macs had 32-bit Intel Core CPUs.

1.2-rc4 built fine for 32-bit.

As far as I know, all Apple products with Intel processors support SSE2. The oldest Intel chip I'm aware of them using was the Pentium M in the Apple TV 1.

Build failures are never a good experience for the user, so I wanted to make sure you were aware of this one. If you don't want to support 32-bit, that's up to you, but maybe it could be detected at configure time and a more user-friendly error message could be printed.

**Comment by jbenden** [comment]
I dig out my Mac and see about fixing the assembly.

Thank you for your detailed response!

-Joe

**Comment by jbenden** [comment]
Would you mind testing the above PR #1853 to see if you have success with that assembly file?

**Comment by jbenden** [comment]
Ping?

**Comment by ryandesign** [comment]
Thanks, with the changes from that PR, it does compile for 32-bit on macOS 10.12.

The last version of macOS that works on 32-bit Macs is 10.6, and under that version's older compiler, there is a compile failure of a .c file, but I don't think it's related to this PR so I'll file a separate ticket.

**Comment by jbenden** [comment]
Thanks!
