### ISSUE TITLE
openwrt compile aircrack-ng-1.2-rc5 failed

### ISSUE THREAD

**Issue by ztpaul** [aircrack-ng/aircrack-ng#1861]
my compile cmd is "autoreconf -i && env CC=gcc-4.8 CXX=g++-4.8 ./configure mips". and got the following error(Please see the detail information in the attachment):
[compile failed.txt](https://github.com/aircrack-ng/aircrack-ng/files/1913570/compile.failed.txt)

  CXX      linecount.o
mips-openwrt-linux-uclibc-g++: error: unrecognized command line option '-masm=intel'
make[5]: *** [linecount.o] Error 1
make[5]: Leaving directory `/data/users/xpon/zhangbo/mac/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/aircrack-ng-1.2-rc5/src'
make[4]: *** [install-recursive] Error 1

**Comment by aircrack-ng** [comment]
Actually, you have to pass the cross-compilers to CC and CXX and there shouldn't be `mips` after `./configure`.

Does it fix the issue?

**Comment by ztpaul** [comment]
Thanks for your reply, can you give me an example?

**Comment by aircrack-ng** [comment]
`env CC=mips-openwrt-linux-uclibc-gcc CXX=mips-openwrt-linux-uclibc-g++ ./configure`

**Comment by ztpaul** [comment]
It works well, my compile cmd is : 
autoreconf -i && env CC=mips-openwrt-linux-uclibc-gcc CXX=mips-openwrt-linux-uclibc-g++ ./configure --host=mips

Thanks a lot.
