### ISSUE TITLE
Floating point exception when I close laptop cover

### ISSUE THREAD

**Issue by interlocuteur** [aircrack-ng/aircrack-ng#1865]
I'm using aircrack-ng 1.2RC1.

This happen very often when I use -w "file" but it never happened when I pipe the wordlist into aircrack -w -

**Comment by aircrack-ng** [comment]
1.2 RC1 is several years old. It is probably fixed by now. 

If this happen with 1.2 final, reopen this issue with more details: the exception details and CPU information.

**Comment by interlocuteur** [comment]
It was a typo.
I'm using 1.2RC4

**Comment by aircrack-ng** [comment]
Probably something due to how it was built (CPU instructions) and most likely rc5 will fix the issue. Update to 1.2 final and reopen if it's still an issue
