### ISSUE TITLE
Logo design: Aircrack

### ISSUE THREAD

**Issue by baranpirincal** [aircrack-ng/aircrack-ng#1869]
Hello, I am graphic designer and I want to contribute to your project with designing a logo for Aircrack. I'm waiting your feedback. Have a nice day!

Best Regards;
Baran Pirincal
Visual Communication Designer

**Comment by aircrack-ng** [comment]
While this is much appreciated, this issue looks a lot like advertising. For such thing, email us info@aircrack-ng.org.

**Comment by jeff-h** [comment]
@aircrack-ng — you're probably wise to be cautious generally, but I can tell you @baranpirincal has begun a great icon for a project I'm involved with (FSNotes) See https://github.com/glushchenko/fsnotes/issues/197
