### ISSUE TITLE
autoreconf fails when inside a directory with a space character

### ISSUE THREAD

**Issue by badrussians** [aircrack-ng/aircrack-ng#1870]
Do not work "official install script", if Desktop folder has space 'Desk top', for example.

    #! /bin/bash

    # /root/Desk top; !!!WITH SPACE!!! (message: /root/Desk no such file or directory)!!!
    scriptPath="$( cd "$(dirname "$0")" ; pwd -P )";
    cd "${scriptPath}";

    tar -zxvf aircrack-ng-1.2.tar.gz
    cd aircrack-ng-1.2
    autoreconf -i
    ./configure --with-experimental
    make
    make install

I think that problem in "configure.ac" file, that syntax I do not know.

**Comment by aircrack-ng** [comment]
Here is how to reproduce the issue:
```
mkdir "desk top"
cd "desk top"
git clone https://github.com/aircrack-ng/aircrack-ng
cd aircrack-ng
autoreconf -i
```

The following error messages keep repeating themselves until hitting Ctrl-C
```
sh: 1: /home/user/desk: not found
cat: /home/user/desk: No such file or directory
cat: top/aircrack-ng/VERSION: No such file or directory
```

**Comment by jbenden** [comment]
Hello,

Please test the "fix-for-1870" branch. I have made changes there which seem to work for myself.

Thanks,
-Joe

**Comment by aircrack-ng** [comment]
You can merge it.

**Comment by badrussians** [comment]
If it helps:
I do not know - is it work or not.
But I tested this (this message time - 30 min):
```
#! /bin/bash
cd '/home/iamuser/Рабочий стол/Рабочий стол 2/aircrack-ng-fix-for-1870'   # it is Dir
autoreconf -i
```
My output:
> iamuser@mycomp:$ '/home/iamuser/Рабочий стол/test.sh' 
> libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
> libtoolize: copying file './ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build/m4/stubs'.
> libtoolize: copying file 'build/m4/stubs/libtool.m4'
> libtoolize: copying file 'build/m4/stubs/ltoptions.m4'
> libtoolize: copying file 'build/m4/stubs/ltsugar.m4'
> libtoolize: copying file 'build/m4/stubs/ltversion.m4'
> libtoolize: copying file 'build/m4/stubs/lt~obsolete.m4'
> configure.ac:69: installing './compile'
> configure.ac:50: installing './config.guess'
> configure.ac:50: installing './config.sub'
> configure.ac:60: installing './install-sh'
> configure.ac:60: installing './missing'
> src/Makefile.am: installing './depcomp'
> parallel-tests: installing './test-driver'

If I run My script as sudo (ubuntu) - no output!

PS: "Рабочий стол" it is name of russian "Desktop" folder

**Comment by aircrack-ng** [comment]
@badrussians, the output you show is normal. Can't reproduce the bug where it doesn't show anything.

**Comment by badrussians** [comment]
I sad early: "If I run My script as sudo (ubuntu) - no output!"
May be no output, because my ubuntu already has installed old version of aircrack-ng (1.2 rc3 from ubuntu repositories). And I not remove this old version of aircrack-ng before i run new installation (my script).

I need 1-2 days to test 'aircrack-ng-fix-for-1870' on basic installation variants on my machine whith my ubuntu system, for except my mistakes. (now this error still reproduces me)

**Comment by badrussians** [comment]
Im tested this (with some ranges of first commented string for "newDirName'):
```
#! /bin/bash
# №!ёЁ~`"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
myDesktopDir='/home/user/Рабочий стол';
oldDirName='aircrack-ng-fix-for-1870';
newDirName="0123456789: ;<= >? @ABCDEFGHIJKLMNOPQRSTUVWXYZ";
cd "${myDesktopDir}";
mv "${oldDirName}" "${newDirName}"
cd "${newDirName}"
autoreconf -i
```
Result - "normal output" (see above)

If run this script second time or more - no output (regardless
 with sudo or not)

if run full install script as sudo on ubuntu x64 16.04.4:
```
#! /bin/bash
myDesktopDir='/home/user/Рабочий стол';
cd "${myDesktopDir}";
cd 'aircrack-ng-fix-for-1870'
autoreconf -i
./configure --with-experimental
make
make install
```
, some lines of output seemed strange to me:
> configure: WARNING: Libtool does not cope well with whitespace in `pwd`
> checking pcap header directories... not found
>   CCLD     libradiotap.la
> ar: ``u' modifier ignored since `D' is the default (see `U')
> linux.c:97:21: warning: ‘szaDriverTypes’ defined but not used [-Wunused-variable]
> nexmon.c: In function ‘get_text_file_content’:
> nexmon.c:185:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(buffer, 1, length, f);
>      ^

if run script without sudo, a few more lines appear (my "short" translation from russian):
> The target «install-exec-am» does not require the execution of commands
> /bin/mkdir -p '/usr/local/share/man/man1'
> /bin/mkdir:  can not create directory /usr/local/share/man/man1: Access is denied
> Makefile:530:  failed to complete the recipe for the "install-man1" target
> make[2]: *** [install-man1] Error 1
> make[2]:  exit from the directory "/home/user/Рабочий стол/aircrack-ng-fix-for-1870 / manpages"
Makefile: 661: failed to complete the recipe for the "install-am" target
> make[1]: *** [install-am]  Error 2
> make[1]:  exit from the directory "/home/user/Рабочий стол/aircrack-ng-fix-for-1870 / manpages"
> Makefile: 557: failed to complete the recipe for the "install-recursive" target
> make: *** [install-recursive]  Error 1

if this all normal, then probably can close this issue 1870.

PS: if i will have time I write at least 2 issues, where  aircrack-ng fails if passwords file name contain comma ",". and output of aricrack-ng has mixed strings (no order in output strings).

**Comment by aircrack-ng** [comment]
@badrussians, all that is perfectly normal.

FYI, when running `make install`, you need root privileges.
