### ISSUE TITLE
F: Failed to spawn binary: No such file or directory

### ISSUE THREAD

**Issue by sersajar** [aircrack-ng/aircrack-ng#1876]
I install Aircrack-ng-git from pamac (gui for pacman in linux arch distros). Almost all binaries work, but aircrack-ng hive me this traceback:

F: Failed to spawn binary: No such file or directory

Any ideas??
If Install older version(year 2015), it works perfectly....

**Comment by aircrack-ng** [comment]
This is because of the trampoline binary. Check the section "Run-time location of SIMD binaries" in the README.MD

**Comment by Shamiq23** [comment]
Greetings,
can you explain steps
Thankyou

**Comment by willbelr** [comment]
If you are an Arch user, you can create a link from /usr/lib to /usr/libexec
