### ISSUE TITLE
Add radiotap headers to cap files dumped by airodump-ng

### ISSUE THREAD

**Issue by alammer** [aircrack-ng/aircrack-ng#1883]
Hi! I added a radiotap headers to the packets that airodump-ng dumpes. The code changes for this do not look too complicated and wireshark work fine with  files. But I would like to know - there was some serious reasons for strip radio information from packet before dump it to .cap file  or it's just happened "historically"?

**Comment by aircrack-ng** [comment]
Duplicate of #448

Yes, so that parsing would only need to be done for plain 802.11 frames. Metadata (frame signal, etc) is included in a structure.

**Comment by paradeda** [comment]
How can insert radiotap header in pcap files ?

**Comment by charliebabbitt1988** [comment]
I thought I had a driver problem, but it turns out that airodump-ng doesn't write the RSSI to the pcap file.  I will have to resort to a different capture method.

Does anyone know if a aircrack-ng fork ever implemented this?

**Comment by vinodcwork** [comment]
Alammer, I’m looking for to modify the code for the same to reflect radio tap on my wlan0 capture with airodump-ng utility , could you please share the snippet of the code and GitHub repo for airodump-ng please.

Thanks
Vinod

**Comment by vinodcwork** [comment]
> Hi! I added a radiotap headers to the packets that airodump-ng dumpes. The code changes for this do not look too complicated and wireshark work fine with files. But I would like to know - there was some serious reasons for strip radio information from packet before dump it to .cap file or it's just happened "historically"?

Hi,

Could you please share the code snippet where to add and recompile ?
