### ISSUE TITLE
Cross-build failure on Void linux arm

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#1888]
Hi,

Trying to update our package to the latest release, cross-compilation fails for arm 32-bit:
https://travis-ci.org/voidlinux/void-packages/jobs/377975294#L1206
and:
https://travis-ci.org/voidlinux/void-packages/jobs/377975296#L1091

Using commit [1499291](https://github.com/aircrack-ng/aircrack-ng/commit/149929109eab1f79c4b90aa423f6d6eb4ee0e882) as suggested in [#1872](https://github.com/aircrack-ng/aircrack-ng/issues/1872) does not help, same result...

Regards.

**Comment by aircrack-ng** [comment]
Looks like armel but you can also try 208c0d4810f24e03b4def637ebe130f8777ef3e1

**Comment by ghost** [comment]
````
  CC       libosdep_la-linux.lo
  CC       libosdep_la-linux_tap.lo
  CC       libosdep_la-common.lo
  CC       libosdep_la-nexmon.lo
linux.c: In function 'get_linux_driver':
linux.c:1302:15: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
     char path[PATH_MAX];
               ^~~~~~~~
               AF_MAX
linux.c:1302:15: note: each undeclared identifier is reported only once for each function it appears in
linux.c:1303:10: warning: unused variable 'link' [-Wunused-variable]
     char link[PATH_MAX];
          ^~~~
linux.c:1302:10: warning: unused variable 'path' [-Wunused-variable]
     char path[PATH_MAX];
          ^~~~
At top level:
linux.c:97:21: warning: 'szaDriverTypes' defined but not used [-Wunused-variable]
 static const char * szaDriverTypes[] = {
                     ^~~~~~~~~~~~~~
make[3]: *** [Makefile:822: libosdep_la-linux.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
````
Well, it doesnt' get better.

**Comment by aircrack-ng** [comment]
It does, that is just a missing include in nexmon.c: `#include <limits.h>`.
