### ISSUE TITLE
Floating pointg exception when I close laptop lid

### ISSUE THREAD

**Issue by interlocuteur** [aircrack-ng/aircrack-ng#1892]
I installed Aircrack-ng 1.2
I get "Floating point exception" if I close lid while aircrack-ng is running.
This happen approx. 1 time every 5 attempts.
Was happening also with 1.2RCx
This is a serious problem since aircrack session may be long and I need to travel will the laptop..
Hardware: Dell Latitude 3540

**Comment by aircrack-ng** [comment]
What does closing the lid do? Suspend?

Have you tried current git master?
