### ISSUE TITLE
Airolib-ng doesn't commit data when importing from stdin and hitting Ctrl-C in the middle

### ISSUE THREAD

**Issue by abhaskumarsinha** [aircrack-ng/aircrack-ng#1893]
I'm using **airlib-ng** and **crunch** to generate password Database and use that Password Database in **aircrack-ng** to crack the Captured Handshake of a WPA2 Wireless Network.

Here are my terminal Commands and Output -

    root@VAIO-PC:~/Desktop/files# crunch 8 8 1234567890abcdefghijklmnopqrstuvwxyz --stdout | airolib-ng testdb -import passwd -
    Crunch will now generate the following amount of data: 25389989167104 bytes
    24213780 MB
    23646 GB
    23 TB
    0 PB
    Crunch will now generate the following number of lines: 2821109907456 
    Database <testdb> does not already exist, creating it...
    Database <testdb> successfully created
    Reading file...
    ^CCrunch ending at 1111y3z4id lines ignored.
    root@VAIO-PC:~/Desktop/files# clear

Now, I've generated a testdb which I'll be using with `-r` switch to crack the handshake file (*.cap).

    root@VAIO-PC:~/Desktop/files# aircrack-ng '/root/Desktop/hs/TEST-NET.cap' -r '/root/Desktop/files/testdb' 
    Opening /root/Desktop/hs/TEST-NET.cap
    Read 4 packets.
    
       #  BSSID              ESSID                     Encryption
    
       1  AA:8E:E8:04:02:EE  TEST-NET                  WPA (1 handshake)
    
    Choosing first network as target.
    
    Opening /root/Desktop/hs/TEST-NET (copy).cap
    Reading packets, please wait...
    
    
                                     Aircrack-ng 1.2 rc4
    
    Quitting aircrack-ng...
    root@VAIO-PC:~/Desktop/files# 

But it quits for an unexpected reason, can anyone here tell me the problem here? Also a .journal file gets deleted. I dunno what's the problem, I tried searching in forums and other website but I didn't find much help regarding this.

Related - [https://tools.kali.org/wireless-attacks/airolib-ng][1]
but it uses a wordlist instead of generating them using crunch.

  [1]: https://tools.kali.org/wireless-attacks/airolib-ng

I think that the password database file is about 50mb and the text password is more that 500 mb, so is my PC running so fast that it completes the whole process in wink of an eye?

# **PS - this is just the copy of question at security.stackexchange.com/ here - [security.stackexchange.com](https://security.stackexchange.com/questions/186541/using-airolib-ng-with-crunch-and-then-using-the-file-using-aircrack-ng-gives-une) because I think it's a bug.**

**Comment by aircrack-ng** [comment]
You forgot to process all those passwords to generate PMKs (--batch option): https://www.aircrack-ng.org/doku.php?id=airolib-ng

**Comment by abhaskumarsinha** [comment]
@aircrack-ng What is processing? why it's needed? How to do it? docs didn't help :(

**Comment by abhaskumarsinha** [comment]
@aircrack-ng I dunno why it's always me, but I used --batch switched, still the same result :(

**Comment by aircrack-ng** [comment]
What is the output with --stats?

**Comment by abhaskumarsinha** [comment]
@aircrack-ng with --stats nothing happens, just shell quits with one line blank

**Comment by abhaskumarsinha** [comment]
I stop that checking process which tests how much lines are good and how many lines are ignored, because I already get 50mb of database which is full of all possible combinations of passwords

Is it needed to complete the check? why? It'd take a lot of hours to finish it, even though the passwords have been generated

**Comment by aircrack-ng** [comment]
What I meant was running `airolib-ng testdb --stats` and there is a result: 0 password.

The bug is that hitting Ctrl-C when running airolib-ng prevents the data from being stored in the DB because it does not commit the transaction.
