### ISSUE TITLE
High CPU Utilization in background - Incremental Fix

### ISSUE THREAD

**Issue by ghostop14** [aircrack-ng/aircrack-ng#1901]
Hi, I still have high CPU utilization with the latest is_background checks.  I had patched the code back in January successfully with a fix I had found in a forum, but the current is_background check doesn't appear sufficient.  CPU still spikes.

Here's the fix I found that works.  Change is_background() to this:
```
static int is_background()
{
	// Additional fix here:
	if (!isatty(fileno(stdin)))
	        // background
	       return 1;

	pid_t grp = tcgetpgrp(STDIN_FILENO);
	if(grp == -1) {
		// Piped
		return 0;
	}
    
	if (grp == getpgrp()) {
		// Foreground
		return 0;
	}
    
	// Background
	return 1;
}
```

**Comment by aircrack-ng** [comment]
What is the forum post URL?

Could you show the exact airodump-ng command you use to reproduce the bug and anything relevant about the system?

**Comment by ghostop14** [comment]
Sure, details to reproduce would definitely help! I can't find the post but I think their issue was due to something slightly different.  It just ultimately led me to the fix.  

One more piece of info, I don't notice it as much on a modern Gen7 Intel system, but on the raspberry pi I run it on it jumps right up.  Possibly because one core getting higher utilization doesn't impact my system there as much.  

Here's how you can reproduce it.  I'm using Python3 to launch it in my app making sure interface is already in monitor mode:

python3
import subprocess
bands='ag'
tmpDir='/tmp'
interface='<some monitor mode interface started with airmon-ng>'
scanProc = subprocess.Popen(['airodump-ng', interface, '-b',bands,'--output-format', 'csv', '--write', tmpDir + '/airodump', '--write-interval', '3'], stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)

**Comment by aircrack-ng** [comment]
On the Pi, it uses more CPU when run with `screen` but it doesn't make any difference when using python.
