### ISSUE TITLE
"bcm43xx-injection-linux-2.6.20.patch" broken link

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#1902]
Can someone pls upload the file "bcm43xx-injection-linux-2.6.20.patch" ? I want to test monitor mode with my broadcom4354. And all links to this file are broken.

**Comment by aircrack-ng** [comment]
There is no need to apply this patch anymore. As you can see, it was for 2.6 kernel which is VERY old and no recent distribution has such kernel anymore.

When you mention something is broken, it is always recommended to tell what exactly is broken. In this specific instance, what links are broken.
