### ISSUE TITLE
airbase-ng AP Client alert

### ISSUE THREAD

**Issue by sepi2048** [aircrack-ng/aircrack-ng#1905]
At this point I am able to grep for clients connecting to my AP, in addition I would like to be able to store the individual Client mac addr to a file. How can I work with the airbase-ng stdout?
> #!/bin/bash
> 
> while true; do
> 
>   if airbase-ng -a 00:00:00:00:00:00 --essid "MyNetwork" -c 6 wlan0mon -q | grep 'Client'; 
>   then
>      echo "Macaddr: $hardw" # How to add client mac addr to a variabe? 
>   fi
> 
>   #insert exit condition here
>   if false; then
>     break
>   fi
> 
>   #5 second sleep
>   sleep 5
> 
> done

**Comment by aircrack-ng** [comment]
This is not a bug or feature request, so this is more appropriate in the forum, in the programming section. Thanks
