### ISSUE TITLE
odd behaviour of airodump-ng looking for wireless-tools

### ISSUE THREAD

**Issue by rofl0r** [aircrack-ng/aircrack-ng#1910]
here's strace log from latest git: https://pastebin.com/exX5tFiu

trying to run airodump results in airodump opening about every path available on that device and running stat on every single file, then failing with the message

>  Can't find wireless tools, exiting.

what's the point of that ? we don't need to run any external program, as the interface is already in monitor mode.

also the "find-binary-in-filesystem" frenzy seems very odd, you could just run the binary using the execl* family of functions which leaves the path-search to the OS.

**Comment by aircrack-ng** [comment]
In some cases, it needs access to the wireless tools and some distributions have their PATH variable misconfigured which would make execl fail to find the binary. So, it is looking in different paths to see if it find them.

How is it a problem?

**Comment by rofl0r** [comment]
what for does it need the wireless tools ?
why is it supposed to find the tools if the user misconfigured his PATH ?
why does it fail to start when the tools were not found ? RC4 works flawlessly without any 3rd party tools.

**Comment by aircrack-ng** [comment]
Check `linux.c` in osdep/: https://github.com/aircrack-ng/aircrack-ng/blob/c4e9a7890d6a59bf3e708cafe01d0616f2a2934b/src/aircrack-osdep/linux.c#L190

If you have a better way to do it, update this issue. If not, this looks more like a question and in such case, better suited for the forum

**Comment by aircrack-ng** [comment]
Feel free to reopen if you have a better way to do this check or if linking to a PR.

**Comment by rofl0r** [comment]
it seems this behaviour can be inhibited by having CONFIG_LIBNL activated (i.e. libnl(-tiny) needs to be installed) so i guess we can shrug this off.

**Comment by rofl0r** [comment]
thinking of it, maybe the error message should be changed to "compiled without libnl support, and thus required wireless tools not found - exiting." so it's clear to the consumer why the tools are suddenly needed.

**Comment by aircrack-ng** [comment]
It doesn't suddenly become required. It's a compile-time thing and it is displayed on the summary screen of `./configure` so there is no way to miss it unless the packager doesn't pay attention to that screen.

**Comment by rofl0r** [comment]
well, it's just that the person getting the message doesn't really have a clue that it's related to compile time options, unless he starts digging in the code.

**Comment by rofl0r** [comment]
hey, thanks: https://github.com/aircrack-ng/aircrack-ng/commit/f64df34d2eb8e182051dcaa14fc0645cca93d552
