### ISSUE TITLE
Failed initializing wireless card(s): wlan0

### ISSUE THREAD

**Issue by alimp5** [aircrack-ng/aircrack-ng#1911]
```
root@kali: airodump-ng wlan0
or
root@kali: airodump-ng wlan0mon

ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211,
ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead.  Make
sure RFMON is enabled: run 'airmon-ng start wlan0 <#>'
Sysfs injection support was not found either.

Failed initializing wireless card(s): wlan0
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
root@kali:  uname -a
Linux Hero-Fi 4.9.59-v7_Re4son-Kali-Pi+ #1 SMP Wed Feb 14 20:50:28 CST 2018 armv7l GNU/Linux

Notes:
Raspberry-Pi 3B
aircrack-ng is already the newest version (1:1.2.0-6)
```

What's the problem !?

**Comment by binarymaster** [comment]
Run `airmon-ng start wlan0` first.

**Comment by alimp5** [comment]
@binarymaster 
I did that.

after upgrading my kali linux (rpi-3b) to the last version via `apt-get update && apt-get upgrade && apt-get dist-upgrade` ,,, I couldn't to launch Aircrack-ng (airdoump-ng).

```
root@kali:  dmesg
[    6.7`z14592] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    6.719808] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC1E1
[    7.020523] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    7.058089] brcmfmac: brcmf_cfg80211_change_iface: brcmf_cfg80211_change_iface, iftype: 2
[    7.061512] brcmfmac: brcmf_cfg80211_update_proto_addr_mode: brcmf_cfg80211_update_proto_addr_mode: ADDR_INDIRECT
[    7.069535] brcmfmac: power management disabled
[    7.600850] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    7.604952] brcmfmac: power management disabled
[    7.863543] brcmfmac: brcmf_cfg80211_add_iface: brcmf_cfg80211_add_iface enter: p2p-dev-wlan0 type 10
[    7.870313] brcmfmac: brcmf_vif_add_validate: brcmf_vif_add_validate, NUM_NL80211_IFTYPES: (13)
[    7.873872] brcmfmac: brcmf_vif_add_validate: brcmf_vif_add_validate, pos->wdev.iftype: (2)
[    7.877467] brcmfmac: brcmf_vif_add_validate: brcmf_vif_add_validate, cfg80211_check_combinations for iftype_num: (0)	val:(0)
[    7.884378] brcmfmac: brcmf_vif_add_validate: brcmf_vif_add_validate, cfg80211_check_combinations for iftype_num: (1)	val:(0)
[    7.891026] brcmfmac: brcmf_vif_add_validate: brcmf_vif_add_validate, cfg80211_check_combinations for iftype_num: (2)	val:(1)
[    7.949955] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    8.101811] EXT4-fs error (device mmcblk0p2): ext4_mb_generate_buddy:758: group 1, block bitmap and bg descriptor inconsistent: 16628 vs 16629 free clusters
[    8.250968] EXT4-fs error (device mmcblk0p2): ext4_mb_generate_buddy:758: group 43, block bitmap and bg descriptor inconsistent: 12876 vs 12877 free clusters
[   84.795311] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   84.795532] brcmfmac: power management disabled
[   85.698218] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[  102.674926] net_ratelimit: 12 callbacks suppressed
[  102.674932] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: Enter
[  102.675310] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: 0058454e 20 36
[  102.675545] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: calling brcmf_fil_cmd_data_set, cmd: 108
[  102.711083] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: Exit
[  102.717978] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  102.718213] brcmfmac: power management disabled
[  109.270541] brcmfmac: brcmf_cfg80211_change_iface: brcmf_cfg80211_change_iface, iftype: 6
[  109.271244] brcmfmac: brcmf_cfg80211_update_proto_addr_mode: brcmf_cfg80211_update_proto_addr_mode: ADDR_INDIRECT
[  218.919125] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: Enter
[  218.919388] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: 0058454e 20 36
[  218.919624] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: calling brcmf_fil_cmd_data_set, cmd: 108
[  218.920334] brcmfmac: nexmon_nl_ioctl_handler: NEXMON: nexmon_nl_ioctl_handler: Exit
[  218.927329] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  242.006716] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  305.126871] EXT4-fs (mmcblk0p2): error count since last fsck: 43
[  305.127060] EXT4-fs (mmcblk0p2): initial error at time 1528611218: mb_free_blocks:1470: inode 2699: block 33658
[  305.127382] EXT4-fs (mmcblk0p2): last error at time 1529163557: ext4_mb_generate_buddy:758
 ```

**Comment by alimp5** [comment]
I found an interesting thing in TX-power:
note: everything is as default.
TX power of band 2.4Ghz is 20 dBm, but in `iwconfig`  I have 31 dBm...

What's happening !?

```
root@kali: iwconfig wlan0
wlan0     IEEE 802.11  Mode:Monitor  Frequency:2.457 GHz  Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on


root@kali:  iwlist wlan0 txpower
wlan0     unknown transmit-power information.


root@kali: iw reg get
global
country 00: DFS-UNSET
	(2402 - 2472 @ 40), (N/A, 20), (N/A)
	(2457 - 2482 @ 20), (N/A, 20), (N/A), AUTO-BW, NO-IR
	(2474 - 2494 @ 20), (N/A, 20), (N/A), NO-OFDM, NO-IR
	(5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW, NO-IR
	(5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW, NO-IR
	(5490 - 5730 @ 160), (N/A, 20), (0 ms), DFS, NO-IR
	(5735 - 5835 @ 80), (N/A, 20), (N/A), NO-IR
	(57240 - 63720 @ 2160), (N/A, 0), (N/A)
```

**Comment by aircrack-ng** [comment]
You have to use `LD_PRELOAD=libfakeioctl.so airodump-ng YOUR_PARAMETERS`

**Comment by alimp5** [comment]
@aircrack-ng 
Hi,
Please checkout below issue:
https://github.com/seemoo-lab/nexmon/issues/237

Welcome back:
@3x-M4ch1nA @steev

**Comment by suhaib124** [comment]
root@kali:~# airmon-ng 

PHY	Interface	Driver		Chipset

phy0	wlan0		88XXau		Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac

root@kali:~# airmon-ng start wlan0mon

Found 3 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

  PID Name
  506 NetworkManager
  591 wpa_supplicant
  794 dhclient

PHY	Interface	Driver		Chipset

phy0	wlan0		88XXau		Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac

root@kali:~# airodump-ng wlan0mon
Interface wlan0mon: 
ioctl(SIOCGIFINDEX) failed: No such device
Failed initializing wireless card(s): wlan0mon


whats the problem i downloaded the driver but still its not working on monitor mode

**Comment by aircrack-ng** [comment]
@suhaib124, as mentioned on the index page of aircrack-ng.org, kill the processes before putting the card in monitor mode. There is also a typo in your first command: you ask to start `wlan0mon` which doesn't exist, it should have been `wlan0`

**Comment by hacker02x** [comment]
root@kali:~# airmon-ng start wlan0

Found 2 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

    PID Name
   2931 NetworkManager
   2943 wpa_supplicant

PHY     Interface       Driver          Chipset

phy0    wlan0           mac80211_hwsim  Software simulator of 802.11 radio(s) for mac80211

                (mac80211 monitor mode already enabled for [phy0]wlan0 on [phy0]wlan0)
root@kali:~# airmon-ng check kill

Killing these processes:

    PID Name
   2943 wpa_supplicant

root@kali:~# airodump-ng wlan0mon
Interface wlan0mon: 
ioctl(SIOCGIFINDEX) failed: No such device
Failed initializing wireless card(s): wlan0mon

**Comment by nabeel0954** [comment]
@aircrack-ng I facing the same issue please helo me

**Comment by hacker02x** [comment]
Check whether the name is wlan0 or wlan1 for your network

**Comment by ghost** [comment]
`sudo apt  install network-manager`
you might need to install network manager

**Comment by sword4869** [comment]
Yeah! I find it is the problem of driver.

I use 'dmesg' and it shows
```
[ 1602.484632] ieee80211 phy1: rt2x00lib_request_firmware: Info - Loading firmware file 'rt2870.bin'
[ 1602.484793] rt2800usb 2-1:1.0: firmware: failed to load rt2870.bin (-2)
```

` rt2870.bin` has benn removed for the latest linux kernel. And the driver is included in `firmware-misc-nonfree`

`apt install firmware-misc-nonfree` or https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/

**Comment by iranzithierry** [comment]
> root@kali:~# airmon-ng
> 
> PHY Interface Driver Chipset
> 
> phy0 wlan0 88XXau Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac
> 
> root@kali:~# airmon-ng start wlan0mon
> 
> Found 3 processes that could cause trouble. Kill them using 'airmon-ng check kill' before putting the card in monitor mode, they will interfere by changing channels and sometimes putting the interface back in managed mode
> 
> PID Name 506 NetworkManager 591 wpa_supplicant 794 dhclient
> 
> PHY Interface Driver Chipset
> 
> phy0 wlan0 88XXau Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac
> 
> root@kali:~# airodump-ng wlan0mon Interface wlan0mon: ioctl(SIOCGIFINDEX) failed: No such device Failed initializing wireless card(s): wlan0mon
> 
> whats the problem i downloaded the driver but still its not working on monitor mode

Bro did you found the solution cz we're having same issues can you help me

**Comment by Mister-X-** [comment]
@Traviss250, not only you created a new bug report for a support request, and that was the wrong repository.

Don't hijack unrelated tickets, and please read what was posted in #2344. If you had bothered to read the next comment, you'd have the solution.

Next time I see something similar to this (or #2344), you get blocked from the whole organization's repos.

**Comment by Numanpaf885** [comment]
I am getting this error while using airodump-ng in termux:
`~ $ airodump-ng wlan0 --encrypt wep`
`Failed to connect to generic netlink.`
`socket(PF_PACKET) failed: Permission denied`
`This program requires root privileges.`
`Failed initializing wireless card(s): wlan0`
I am using this in an android device termux.

**Comment by Mister-X-** [comment]
@Numanpaf885 your issue is completely unrelated, as you can see the message `This program requires root privileges.`. It means you need to run it as root (or use `sudo`).

Please take the time to carefully read error messages. They often tell you what is wrong (and thus how to fix it).
