### ISSUE TITLE
Airbase-ng or Airodump-ng doesn't work correctly 

### ISSUE THREAD

**Issue by alimp5** [aircrack-ng/aircrack-ng#1914]
Greetings!

I have two laptops. 
I launched below airebase command on laptop-1, but laptop-2 (airodump-ng) can't show details of fake AP on screen or in .netxml or .csv files.
but when I'm associating to fake AP, laptop-2(airodump-ng) shows incorrect info in screen.
```
on laptop-1(airbase-ng):
root@Rasbperry3b: airbase-ng -e "WiFi-Max-MTN" -c 1 wlan1mon 
09:42:37  Created tap interface at0
09:42:37  Trying to set MTU on at0 to 1500
09:42:37  Access Point with BSSID A0:F3:C1:17:03:5F started.
09:42:46  Client 2C:59:8A:5C:AB:0C associated (unencrypted) to ESSID: "WiFi-Max-MTN"
09:42:46  Client 2C:59:8A:5C:AB:0C associated (unencrypted) to ESSID: "WiFi-Max-MTN"
09:42:46  Client 2C:59:8A:5C:AB:0C associated (unencrypted) to ESSID: "WiFi-Max-MTN"
09:42:46  Client 2C:59:8A:5C:AB:0C associated (unencrypted) to ESSID: "WiFi-Max-MTN"
09:42:46  Client 2C:59:8A:5C:AB:0C associated (unencrypted) to ESSID: "WiFi-Max-MTN"
09:42:46  Client 2C:59:8A:5C:AB:0C associated (unencrypted) to ESSID: "WiFi-Max-MTN"
```

----------------------------------------------------
```
I launched **airodump-ng wlan2mon** on laptop-2, and I got incorrect info from fake AP:
A0:F3:C1:17:03:5F  -26        0        5    2   2  -1   OPN              <length:  0>
```

my devices:
rt2800usb	Ralink Technology, Corp. RT2870/RT3070
rt2800usb	Ralink Technology, Corp. RT3572

Note: before upgrading to the last version of aircrack, I hadn't this issue.
and now, unfortunately I don't remember the previous used version of aircrack-ng.

Distro:
RaspberryPi-3b:
Linux RPi-3b  4.9.59-v7_Re4son-Kali-Pi+ #1 SMP Wed Feb 14 20:50:28 CST 2018 armv7l GNU/Linux
Asus N56 laptop:
Linux kali 4.16.0-kali2-amd64 #1 SMP Debian 4.16.12-1kali1 (2018-05-28) x86_64 GNU/Linux

I think the root cause of problem is in `airbase-ng` or `airodump-ng` tool. because even I can't see the info of fake AP in airodump-ng tool (aircrack-1:1.2.0-6).

**Comment by alimp5** [comment]
Dear @aircrack-ng 

Any update for this issue !?

Thanks  in advance.

**Comment by aircrack-ng** [comment]
Not yet, I don't have the hardware to test it at this time.

**Comment by reg1reg1** [comment]
This issue persists on Atheros hardware as well. I am not sure whether it is client specific (using an android client). The client keeps getting disassociated and the messages pop up every few seconds.

**Comment by alimp5** [comment]
Hi Again,
@aircrack-ng Greetings!

I installed the latest version of kali-linux on VirtualBox+VmWare machines and on three laptops (Asus N56, Asus 54x, Lenovo ThinkPad) as default OS.
Aircrack can't detect the created Fake-AP by external wifi adapters via airbase-ng or other similar tools. But the created Fake-AP is visible in smart phones.  This event is a strange state/behavior.

But Aircrack-ng via laptop's built-in wifi adapter (such as: QCA9565 wifi chipset) can detect and save the info of Fake-AP(s) in pcap,netxml,xml,csv.... files.

I tested 4 usb adapters: Alfa-052NH-v2,  TP-Link-7200ND,  TP-Link-721N-v1, Alfa-036ACH-1200.
They have problem in fake-ap detection. and airodump-ng can't save info of fake-ap on xml,netxml,csv... files.
But laptop's built-in wifi adapter can detect and show complete info from created fake-ap via airbase-ng or other similar tools.

I think the root cause of problem is in airodump-ng.  because airodump can't work correctly with external usb wifi adapters.

**Comment by alimp5** [comment]
Dear @aircrack-ng
Any comment / update !??.

Thanks in advance

**Comment by gemesa** [comment]
I can not reproduce this with version 1.7 on Fedora with Alfa AWUS036NHA and TP-Link Archer T2U Plus. Issue can be closed if you agree @Mister-X- 

WEP encryption:
```
$ sudo airbase-ng -W 1 -e "WiFi-Max-MTN" -c 9 wlp0s20f0u2 -a 12:34:56:78:90:AB
13:39:52  Created tap interface at0
13:39:52  Trying to set MTU on at0 to 1500
13:39:52  Access Point with BSSID 12:34:56:78:90:AB started.
```

```
$ sudo airodump-ng wlan0mon --bssid 12:34:56:78:90:AB
 CH 11 ][ Elapsed: 0 s ][ 2023-02-12 13:39 ][ Are you sure you want to quit? Press Q again to quit.

 BSSID              PWR  Beacons    #Data, #/s  CH   MB   ENC CIPHER  AUTH ESSID

 12:34:56:78:90:AB  -15        9        0    0   9   54   WEP  WEP         WiFi-Max-MTN
```

No encryption:
```
$ sudo airbase-ng -e "WiFi-Max-MTN" -c 9 wlp0s20f0u2 -a 12:34:56:78:90:AB
13:39:52  Created tap interface at0
13:39:52  Trying to set MTU on at0 to 1500
13:39:52  Access Point with BSSID 12:34:56:78:90:AB started.
```

```
$ sudo airodump-ng wlan0mon --bssid 12:34:56:78:90:AB
 CH  6 ][ Elapsed: 18 s ][ 2023-02-12 13:23 ][ Are you sure you want to quit? Press Q again to quit.

 BSSID              PWR  Beacons    #Data, #/s  CH   MB   ENC CIPHER  AUTH ESSID

 12:34:56:78:90:AB  -16       41        0    0   1   54   OPN              WiFi-Max-MTN
```

Writing output to CSV:
```
$ sudo airodump-ng wlan0mon --bssid 12:34:56:78:90:AB -w myOutput --output-format csv
$ cat myOutput-01.csv

BSSID, First time seen, Last time seen, channel, Speed, Privacy, Cipher, Authentication, Power, # beacons, # IV, LAN IP, ID-length, ESSID, Key
12:34:56:78:90:AB, 2023-02-12 13:55:25, 2023-02-12 13:55:31,  9,  54, OPN, ,   , -16,       21,        0,   0.  0.  0.  0,  12, WiFi-Max-MTN,

Station MAC, First time seen, Last time seen, Power, # packets, BSSID, Probed ESSIDs

```
