### ISSUE TITLE
Configure fails to find OpenSSL on OSX

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1919]
Even though brew reports openssl being installed, `./configure` doesn't find openssl anymore on OSX.

When reinstalling openssl, it mentions to set `PKG_CONFIG_PATH` to `/usr/local/opt/openssl/lib/pkgconfig` and in this case, running `env PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig ./configure` works

**Comment by jbenden** [comment]
This broke with #1908. How to handle? (Although Travis has been testing osx ok...)

**Comment by jbenden** [comment]
Please post `config.log` and the setup of OSX you have.
