### ISSUE TITLE
Problem injecting packets using aireplay-ng on iwlwifi

### ISSUE THREAD

**Issue by Axle7XStriker** [aircrack-ng/aircrack-ng#1920]
I have an **Intel Dual Band Wireless-AC 3168NGW [Stone Peak]** with wireless driver being **iwlwifi**. I am able to listen to the traffic using airodump-ng but I am having problems injecting packets using aireplay-ng and the injection test is also failing on my **linux mint** system. Need help in solving this problem.

**Comment by Axle7XStriker** [comment]
The output produced by aireplay-ng is as follows:-

03:36:16  Trying broadcast probe requests...
03:36:18  No Answer...
03:36:18  Found 1 AP 

03:36:18  Trying directed probe requests...
03:36:18  0C:D2:B5:4E:BB:DA - channel: 3 - 'WR1505N3-BBDA'
03:36:24   0/30:   0%

**Comment by aircrack-ng** [comment]
There can be a lot of reason why it is failing and this doesn't show a bug. Please use the forum for this.
