### ISSUE TITLE
aircrack-ng do not display

### ISSUE THREAD

**Issue by interlocuteur** [aircrack-ng/aircrack-ng#1921]
I tried a recent version of aircrack-ng (got from github on July 3rd 2018).
The program seem to have a problem to display results.
After target selection dialogue, aircrack displays "opening ....cap" as usual.
But right after, the cursor positions to the 2nd line of the screen and nothing else.
The previous screen is not cleared.
No title, no status, no ETA. Seems dead but top shows that the cracking process runs on all available CPUs.
At the end of the cracking process, I get a normal message "Passphrase not in dictionary".

So, it seems there is a bad handling of ncurses.
I got the program from github (zip file) and compiled with experimental and experimental-scripts options.
I tried with 2 different window size.
Tried on 2 different machines with identical results.
Older versions of aircrack-ng (up to 1.2 official) work fine.

**Comment by aircrack-ng** [comment]
Could you upload the pcap file and wordlist somewhere and post the links here?

**Comment by jbenden** [comment]
I've made some modifications as of 2e1cb4e, on the `master` branch. Please let me know if additional improvements are needed. Thanks!

**Comment by jbenden** [comment]
I fixed another issues as of eb059e3.

**Comment by interlocuteur** [comment]
display now work normally.
I even tested for the floating-point exception (issues 1865 and 1892) and it seerms to be fixed.

Good work and excellent response time.
Thanks
