### ISSUE TITLE
Aircrack segfault when engine .so doesn't open

### ISSUE THREAD

**Issue by ChrisLundquist** [aircrack-ng/aircrack-ng#1924]
In the old world I would invoke `aircrack-ng--avx2`.
I have a check out, updated to master, and recompiled and saw we don't have this target anymore and we use shared objects.

I only ran `./configure` and `make` so `make install` never happened.

The library it wanted was here.
```
find ~/aircrack-ng/ -name "libaircrack-crypto-x86-avx2.so"
/home/clundquist/aircrack-ng/src/aircrack-crypto/.libs/libaircrack-crypto-x86-avx2.so
```

```
$ ~/aircrack-ng/src/aircrack-ng  deduped.hashcat -w ~/dictionaries/rockyou.txt --debug 7
Could not open '/usr/local/lib/libaircrack-crypto-x86-avx2.so'.
Opening deduped.hashcat
Read 130 packets.

   #  BSSID              ESSID                     Encryption

   1  AE:4E:3F:DA:71:40  1221#207-5G               WPA (1 handshake)
# ...
 130  90:94:E4:FC:D7:88  yoga for bhoga            WPA (1 handshake)

Index number of target network ? 130

Opening deduped.hashcat
Segmentation faultlease wait...
```
Note `Could not open '/usr/local/lib/libaircrack-crypto-x86-avx2.so'.`

```
(lldb) bt
* thread #1, name = 'aircrack-ng', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x0000000000000000
    frame #1: aircrack-ng`main(argc=<unavailable>, argv=<unavailable>) at aircrack-ng.c:6968
    frame #2: libc.so.6`__libc_start_main(main=(aircrack-ng`main at aircrack-ng.c:5677), argc=4, argv=0x00007fffffffe408, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffe3f8) at libc-start.c:310
    frame #3: 0x000055555555c09a aircrack-ng`_start + 42
(lldb) frame select 1
frame #1: aircrack-ng`main(argc=<unavailable>, argv=<unavailable>) at aircrack-ng.c:6968
   6965		if (ap_cur->crypt == 3)
   6966		{
   6967		crack_wpa:
-> 6968			dso_ac_crypto_engine_init(&engine);
   6969	
   6970			if (opt.dict == NULL && db == NULL)
   6971			{
```
```
(lldb) print engine
(ac_crypto_engine_t) $0 = {
  essid = 0x0000000000000000
  essid_length = 0
  thread_data = {
    [0] = 0x0000000000000000
     # ...
    [255] = 0x00000000000000
```

It seems like we should probably bail if we can't initialize our engines, or fall back to `-generic` with warning. Alternatively, we could search for `.libs/libaircrack-crypto-x86-avx2.so` relative to the executable as a work around for source checkouts.

I'm sure that sooner or later, folks will forget to `make install` when working on the engine and test a different version than expected.

**Comment by jbenden** [comment]
You have to either:

1. Install it. (obviously, you don't wish too. lol)
2. Run from INSIDE the development folder path.

You probably are looking for option two, so be inside of `~/aircrack-ng` and then run `./src/aircrack-ng`.

**Comment by jbenden** [comment]
The reasoning is because `dlopen` requires a known path to load the shared object. This has two facets to it: installed and development. Handling development case is done by determining if the program(s) are being executed from the base root of the development folder (`abs_top_builddir`) and if so, it knows where the libraries should be.

If that case fails, it assumes it's been installed and looks in the OS shared library directory.

For source code level reasoning, the concerning code is [here](https://github.com/aircrack-ng/aircrack-ng/blob/3ab3731f9f8289437368c8fcdb0b8e3b7b90ec73/src/aircrack-util/crypto_engine_loader.c#L216) in `crypto_engine_loader.c` around line 216.

**Comment by ChrisLundquist** [comment]
Thanks!

I ended up doing `make install` but it took me a second to see the error of failing to open the engine. (it scrolled off the screen after listing the networks, then it segfaulted.)

Yep yep, exiting there seems reasonable!
