### ISSUE TITLE
Big Endian failure test

### ISSUE THREAD

**Issue by LocutusOfBorg** [aircrack-ng/aircrack-ng#1925]
this happens on a Big Endian machine
```
./src/wpaclean out /home/locutusofborg/aircrack-ng-1.3/test/wpa.cap
Pwning /home/locutusofborg/aircrack-ng-1.3/test/wpa.cap (1/1 100%)
Bad file - skipping /home/locutusofborg/aircrack-ng-1.3/test/wpa.cap
Done
```

see: https://buildd.debian.org/status/fetch.php?pkg=aircrack-ng&arch=s390x&ver=1%3A1.3-1&stamp=1531479016&raw=0

do you have any clue? it fails on mips and s390x, so I presume an endianess problem

**Comment by LocutusOfBorg** [comment]
https://buildd.debian.org/status/package.php?p=aircrack-ng&suite=unstable

**Comment by aircrack-ng** [comment]
That pcap is little endian, so yes, an endianness issue. It should be fairly easy to fix

**Comment by LocutusOfBorg** [comment]
hello, do you have a patch?

**Comment by aircrack-ng** [comment]
Not yet

**Comment by jbenden** [comment]
I do not have an easy way to test currently, but would you please try the following patch?

Thanks!
-Joe

[osdep_cigam.patch.txt](https://github.com/aircrack-ng/aircrack-ng/files/2394634/osdep_cigam.patch.txt)

**Comment by LocutusOfBorg** [comment]
it seems to make not that much difference...
https://launchpadlibrarian.net/389202148/buildlog_ubuntu-cosmic-s390x.aircrack-ng_1%3A1.3-2ubuntu1_BUILDING.txt.gz

**Comment by jbenden** [comment]
Thanks. I'll have to gain access to a BE machine for development and testing, then. :(

**Comment by LocutusOfBorg** [comment]
can't you just do:
```
pbuilder-dist sid s390x create
pbuilder-dist sid s390x login
```
it requires:
- debian based system
- qemu-user
- some minutes
(or use launchpad ppa)

**Comment by jbenden** [comment]
Oh, I'll check into that thought...

I've got into a SPARC machine and made a new patch; however, I couldn't test completely because `libcrypto.so.1.1` is tossing a SIGILL.

On the other hand, it does make further progress...

-Joe

[osdep_cigam.patch.txt](https://github.com/aircrack-ng/aircrack-ng/files/2397908/osdep_cigam.patch.txt)

**Comment by jbenden** [comment]
I'm trying on a POWER7 system, currently...

**Comment by jbenden** [comment]
It works on POWER7 BE machine.

Do note that current `master` branch has a known failing test, unrelated to this issue.

**Comment by LocutusOfBorg** [comment]
I confirm it worked correctly, pushed in both Debian and Ubuntu machines, thanks a lot!

BTW there are some test failures on some Debian ports, if you want to take a look
https://buildd.debian.org/status/package.php?p=aircrack-ng&suite=unstable
(nothing really important, they might be due to compiler issues or something else!)
