### ISSUE TITLE
airodump-ng: error while loading shared libraries: libaircrack-osdep.so.0

### ISSUE THREAD

**Issue by farshield** [aircrack-ng/aircrack-ng#1927]
Ubuntu 16.04
gcc-7
Tested with fc35d55

When running from an installation path:

```sh
$ airodump-ng  # path is at /usr/local/sbin/airodump-ng
airodump-ng: error while loading shared libraries: libaircrack-osdep.so.0: cannot open shared object file: No such file or directory
```
Error goes away if the executable is run from the repository directory:

```sh
/projects/aircrack-ng/src/airodump-ng
```

Same behavior with or without `--enable-shared` option.

`make check` runs fine.

**Comment by aircrack-ng** [comment]
What was the configure command?

**Comment by farshield** [comment]
Just plain ol' `./configure`. Also tried with `./configure --enable-shared` but I get the same error.
Here is the output of `./configure`: https://gist.github.com/farshield/ade9c4dd521810b2ebb4428697ddd768

**Comment by mouzmike** [comment]
I get the same error with gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609 as @farshield mentioned.
Creating a symbolic link for the dependent library like _sudo ln -s /usr/local/lib/libaircrack-osdep.so.0.0.0 /usr/lib/libaircrack-osdep.so.0_ does the trick for now and allows you to execute from any directory.

**Comment by kimocoder** [comment]
I got the same, for now I did the same as the above and it works at least.
Running om Kali 2018.2 kernel v4.16.12

**Comment by ghost** [comment]
I had same problem ..refer this link
https://github.com/aircrack-ng/aircrack-ng/issues/171

**Comment by jbenden** [comment]
Libtool has a notion of its' own versioning scheme; that solves the issue of having multiple versions of the same shared library present on a machine. Unfortunately, Linux chose to not follow this specification (nor another similar one). So, Linux machines expect a simple `<filename>.so` to be present and linked to the versioned shared library.[1]

I've modified our build system to follow Linux convention from now on.

[1]: https://www.gnu.org/software/libtool/manual/html_node/Release-numbers.html#Release-numbers

**Comment by Warllock** [comment]
I had same error with Aircrack 1.3...

It helped me simply update or install Ubuntu packages:
sudo apt-get install libssl-dev libnl-3-dev libnl-genl-3-dev ethtool

**Comment by 7heaven** [comment]
simply call 'ldconfig' after 'make install' fix this problem

work for me

**Comment by haliliceylan** [comment]
@7heaven Thanks Mate !

**Comment by srgonzalez** [comment]
@7heaven  Thank you very much!

**Comment by Pentest0fu** [comment]
@7heaven thanks mate , you saved my night!

**Comment by squintz** [comment]
Worked for me also. Thanks.
