### ISSUE TITLE
airodump-ng: missing RXQ column

### ISSUE THREAD

**Issue by psyborg55** [aircrack-ng/aircrack-ng#1928]
when use -c for channel option RXQ is properly displayed, but when running airodump in freq mode -C this is not displayed

**Comment by aircrack-ng** [comment]
The signal quality can only be calculated when data is received consistently and it isn't the case when the card is hopping channels, hence why it is disabled when hopping channels

**Comment by psyborg55** [comment]
this sounds like a reply from someone first time hearing of aircrack-ng suite...

nobody mentioned channel hopping, it is running on same chan/freq in both cases, but no RXQ value is shown if frequency is chosen as input instead of channel.

obviously, airodump-ng won't accept -c 240 so i have to use -C 2327

**Comment by aircrack-ng** [comment]
Channel 240 is 5.7GHz.

2327MHz is out of the 2.4GHz band

**Comment by psyborg55** [comment]
with ath hamradio patch 240 = 2327.

anyway, the behavior is the same on a regular 2.4 channel. RXQ shown only when channel (-c) is specified

**Comment by aircrack-ng** [comment]
Could you link to that patch
