### ISSUE TITLE
aircrack-ng doesn't work with nexmon

### ISSUE THREAD

**Issue by 3x-M4ch1nA** [aircrack-ng/aircrack-ng#1929]
As of a couple months ago, on my Kali ARM for rpi3, when I run "airmon-ng start wlan0", it returns: "not a raspberry pi 3 or Zero Wireless. Cannot put into monitor mode".

Re4son (the main contributor of Kali ARM) says it's because aircrack no longer supports nexmon. So implemented a code "mon0up" to put in monitor mode. It uses iw to bring it up. 

I CAN, however use "airodump-ng mon0" after issuing "mon0up". It just can't be put into monitor mode through aircrack. Which kinda sucks because so many repos use aircrack to initiate monitor mode. So for all those types of things, I have to use external wifi.

Any help, or info of this supposed issue?

**Comment by aircrack-ng** [comment]
It's because you have a newer Rpi and at the time, the hardware revision string wasn't known. As soon as it was released, it was added. However, the repository/system still had an old version.

Airodump-ng has been tested and works. Check out #1882 and db004e7f88837b430f497b3331bdf304696cfe2b

**Comment by 3x-M4ch1nA** [comment]
@aircrack-ng, tyvm

But it did return the same error on old rpi3 (as well as rpi3b+), and zero w.

I will do as suggested and check it out

**Comment by aircrack-ng** [comment]
Reopen the ticket after installing the latest kernel as mentioned in #1882 and updated nexmon driver if using git master still fail. We'll need details on the setup (software and hardware)
