### ISSUE TITLE
airolib-ng doesn't benefit from AVX2 or multiple CPUs

### ISSUE THREAD

**Issue by ofersadan85** [aircrack-ng/aircrack-ng#1930]
I've tested airolib-ng and aircrack-ng on multiple machines, mainly:

- Windows 10 x64 without avx2 (with avx) with 4 CPU cores and 4GB RAM
- Ubuntu 18.04 with avx2 with 8 CPU cores and 4GB RAM

The results for aircrack-ng vary greatly because of the different (and relatively new) implementations of avx2 instructions. The results for these machines (for aircrack-ng -S test) are ~2,500 passwords/sec for the windows-avx-4cpu machine and ~10,000 passwords/sec for the ubuntu-avx2-8cpu machine.

However, it seems that airolib-ng did not benefit from the same speed boosts of recent versions. The result of running airolib-ng on the same database are in both cases ~300 PMK/sec, even though the difference in speeds for aircrack-ng is 4x times faster and the underlying calculation of PMKs should basically be the same. Obviously, airolib-ng does some I/O on the database so it's expected to be slower than aircrack-ng, but there should be some difference in speed when comparing different architectures.

Moreover, I've monitored both computers CPU usage when running both commands, while aircrack-ng makes full use of the cpu in all machines (90%-100% CPU usage), airolib-ng only uses 15%-30% of CPU on both machines while it's running.

I admit full ignorance about the way these programs are written and the way the source codes implements both calculations, but i'm guessing it would be trivial to implement the faster / more sophisticated algorithms already written for aircrack-ng on airolib-ng as well. If i'm missing something crucial here that makes this impossible or hard, please explain.

EDIT: Just to note, i've also tested this with both recent versions (1.2 and 1.3)

**Comment by ofersadan85** [comment]
Just to update, I've ran some more tests with virtual machines, it seems like when there is one CPU core, it's usage is 100%, if there's 2 CPU cores, the usage is 50%, 4 CPUs = 25% usage and so on... so it seems the major issue here is not utilizing multiple cores.

**Comment by ChrisLundquist** [comment]
I don't know too much about Airolib, but it looks like it mostly works with SQLite. SQLite, at least older versions, didn't thread very well as there was a lot of lock/mutex contention.

I vaguely recall newer versions improving this, and getting closer to innodb performance.

Aircrack-ng is all memory based and doesn't do too much locking which allows it to scale better.
Likewise, if you're using airolib-ng on a spinning disk, disk latency would also cause a notable slow down.

If you're using airolib/sqlite to generate something like a rainbow table, you'd likely be disk write limited.

on your linux box, you can check this with `iostat -xm 10 10` while airolib is running. if you see `/dev/sda` or `/dev/nvmes0p1` at `100% util` that could be it

**Comment by aircrack-ng** [comment]
@ChrisLundquist disk speed are quite high. Years ago, tests shown 80000 keys/sec on average on spinning disks.

Some of the workaround, other than no use of modern CPU instructions, is to use as many airolib-ng instances as CPUs on the system.

**Comment by ofersadan85** [comment]
@aircrack-ng about running airolin-ng with multiple instances - won't all instances attempt to compute the same "next in line" PMKs? In other words, is it safe to use the same database file with multiple worker processors accessing it?

**Comment by aircrack-ng** [comment]
No, it locks a batch to process

**Comment by ofersadan85** [comment]
Checking in 2.5 years later (with version 1.6 - same problem exists) ... any progress?
