### ISSUE TITLE
Non-Altivec PowerPC target simd build failure

### ISSUE THREAD

**Issue by rc-matthew-l-weber** [aircrack-ng/aircrack-ng#1941]
Build details:
- aircrack-ng-1.3
- GCC4.7 and 7.x were both tested
- Building for a e500v2 SPE archtecture (ie no altivec)
```
  CC       libaircrack_crypto_la-crypto_engine.lo
  CC       libaircrack_crypto_ppc_altivec_la-memory.lo
  CC       libaircrack_crypto_ppc_altivec_la-sha1-git.lo
memory.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
  CC       libaircrack_crypto_ppc_altivec_la-simd-intrinsics.lo
sha1-git.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
  CC       libaircrack_crypto_ppc_altivec_la-wpapsk.lo
simd-intrinsics.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
simd-intrinsics.c:147:18: error: unknown type name 'vtype'
simd-intrinsics.c: In function 'dispatch':
simd-intrinsics.c:671:3: warning: implicit declaration of function 'SIMDmd5body' [-Wimplicit-function-declaration]
simd-intrinsics.c:671:16: error: 'vtype' undeclared (first use in this function)
simd-intrinsics.c:671:16: note: each undeclared identifier is reported only once for each function it appears in
simd-intrinsics.c:671:23: error: expected expression before ')' token
simd-intrinsics.c: At top level:
simd-intrinsics.c:905:18: error: unknown type name 'vtype'
simd-intrinsics.c:1386:19: error: unknown type name 'vtype'
simd-intrinsics.c:1928:21: error: unknown type name 'vtype'
simd-intrinsics.c:2547:21: error: unknown type name 'vtype'
make[3]: *** [libaircrack_crypto_ppc_altivec_la-simd-intrinsics.lo] Error 1
```

Additional build log: http://autobuild.buildroot.net/results/87e82a5e8d0b1c1ff10ec3e59d25bcd56b329075/build-end.log
Buildroot autobuilder material for re-creating: http://autobuild.buildroot.net/results/87e82a5e8d0b1c1ff10ec3e59d25bcd56b329075/

**Comment by aircrack-ng** [comment]
Could you try current master to make sure the problem is still there?

Could you also paste the output of `lscpu` or the equivalent `cat /proc/cpuinfo`?

**Comment by rc-matthew-l-weber** [comment]
Verified still there on the tip of master (f031293ed3846b7c47d6f6c780c779249aa65c99)
```
  CC       libaircrack_crypto_ppc_power8_la-sha1-git.lo
  CC       libaircrack_crypto_ppc_power8_la-memory.lo
simd-intrinsics.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
simd-intrinsics.c:147:18: error: unknown type name 'vtype'
simd-intrinsics.c: In function 'dispatch':
simd-intrinsics.c:671:3: warning: implicit declaration of function 'SIMDmd5body' [-Wimplicit-function-declaration]
simd-intrinsics.c:671:16: error: 'vtype' undeclared (first use in this function)
simd-intrinsics.c:671:16: note: each undeclared identifier is reported only once for each function it appears in
simd-intrinsics.c:671:23: error: expected expression before ')' token
simd-intrinsics.c: At top level:
simd-intrinsics.c:905:18: error: unknown type name 'vtype'
simd-intrinsics.c:1386:19: error: unknown type name 'vtype'
simd-intrinsics.c:1928:21: error: unknown type name 'vtype'
memory.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
simd-intrinsics.c:2547:21: error: unknown type name 'vtype'
Makefile:1012: recipe for target 'libaircrack_crypto_ppc_altivec_la-simd-intrinsics.lo' failed
make[3]: *** [libaircrack_crypto_ppc_altivec_la-simd-intrinsics.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
sha1-git.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
memory.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
wpapsk.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
simd-intrinsics.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
simd-intrinsics.c:147:18: error: unknown type name 'vtype'
simd-intrinsics.c: In function 'dispatch':
simd-intrinsics.c:671:3: warning: implicit declaration of function 'SIMDmd5body' [-Wimplicit-function-declaration]
simd-intrinsics.c:671:16: error: 'vtype' undeclared (first use in this function)
simd-intrinsics.c:671:16: note: each undeclared identifier is reported only once for each function it appears in
simd-intrinsics.c:671:23: error: expected expression before ')' token
simd-intrinsics.c: At top level:
simd-intrinsics.c:905:18: error: unknown type name 'vtype'
simd-intrinsics.c:1386:19: error: unknown type name 'vtype'
simd-intrinsics.c:1928:21: error: unknown type name 'vtype'
simd-intrinsics.c:2547:21: error: unknown type name 'vtype'
Makefile:1047: recipe for target 'libaircrack_crypto_ppc_power8_la-simd-intrinsics.lo' failed
make[3]: *** [libaircrack_crypto_ppc_power8_la-simd-intrinsics.lo] Error 1
sha1-git.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
crypto_engine.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]
wpapsk.c:1:0: warning: -mvsx requires hardware floating point [enabled by default]

```


I can't easily provide the lscpu output as our Buildroot autobuilder is just cross-compile build testing a series of architectures.  We support a whole suite of powerpc targets, some with and w/o SPE, Altivec, etc.

The following cross toolchains should reproduce the issue.
https://toolchains.bootlin.com/downloads/releases/toolchains/powerpc64-e5500/tarballs/powerpc64-e5500--glibc--stable-2018.02-2.tar.bz2
https://toolchains.bootlin.com/downloads/releases/toolchains/powerpc-e500mc/tarballs/powerpc-e500mc--glibc--stable-2018.02-2.tar.bz2

**Comment by rc-matthew-l-weber** [comment]
Unsure of best practice, but directly commented on commit here:
https://github.com/aircrack-ng/aircrack-ng/commit/97838c6b903d33c8403a4bdcae60b8619fad7538

**Comment by jbenden** [comment]
Please try without any `CFLAGS` given. I suspect that the compiler doesn't support the needed Altivec flag(s), so it cannot build with it - even if you've specified it.

If it still fails, I would need a complete build log, including commands and env vars, that were tried.

Thanks,
-Joe

**Comment by rc-matthew-l-weber** [comment]
I've actually not supplied any cflags for altivec as part of my build.  I'm just setting a e500 specific SPE ABI that conflicts with altivec (ie my target supports SPE not altivec and altivec targets don't have SPE).  attached are my config.status/log
[config.log](https://github.com/aircrack-ng/aircrack-ng/files/2322197/config.log)

[config.status.txt](https://github.com/aircrack-ng/aircrack-ng/files/2322201/config.status.txt)

**Comment by jbenden** [comment]
Please try out this patch:

```
diff --git a/build/m4/aircrack_ng_simd.m4 b/build/m4/aircrack_ng_simd.m4
index 71e1c06..2bcc41f 100644
--- a/build/m4/aircrack_ng_simd.m4
+++ b/build/m4/aircrack_ng_simd.m4
@@ -138,7 +138,6 @@ then
     AX_CHECK_COMPILE_FLAG([-mabi=altivec], [
         AX_APPEND_FLAG(-mabi=altivec, [ppc_altivec_[]_AC_LANG_ABBREV[]flags])
         AC_SUBST(ppc_altivec_[]_AC_LANG_ABBREV[]flags)
-        ALTIVEC_FOUND=1
     ])
 
     AX_CHECK_COMPILE_FLAG([-mvsx], [
```

It seems it must NOT accept an ABI switch as an acceptable answer to determining if it works. The previous test in that file fails (can't have both enabled), but enabling this one causes the whole build to fail...

Thanks,
-Joe

**Comment by rc-matthew-l-weber** [comment]
That worked, I've attached the similar logs. I've also kicked off a altivec build too and will verify that case.

[config.status.txt](https://github.com/aircrack-ng/aircrack-ng/files/2325159/config.status.txt)
[config.log](https://github.com/aircrack-ng/aircrack-ng/files/2325160/config.log)

**Comment by rc-matthew-l-weber** [comment]
Here's the logs from a successful e6500/power8 build with altivec
[config.status.txt](https://github.com/aircrack-ng/aircrack-ng/files/2325401/config.status.txt)
[config.log](https://github.com/aircrack-ng/aircrack-ng/files/2325402/config.log)

Good on my end.
