### ISSUE TITLE
Hello, I've got a problem:fixed channel wlan1mon: -1

### ISSUE THREAD

**Issue by maozhifeng** [aircrack-ng/aircrack-ng#1948]
Hello teacher, I have been working on modifying the kernel source of android phone and compiling successfully recently. I have installed it on my phone, which can correctly identify the tp-wn722n v1 network card and can normally use the airmon-ng command. However, when I use the commands of airodump and aireplay-ng, the error message appears in the upper right corner :fixed channel wlan1mon: -1. I tried to patch the channel - negative - one - maxim.lt.ds.mot.ad patch to repair the kernel, found that the patch does not apply to my mobile phone kernel source
I know that adding the --ignore-negative-one after the command prevents errors from happening, but I still want to fix it in the kernel because I want to use the wifite software. Please give me a patch to modify the kernel of my mobile phone. Thank you.
Sorry, I am a Chinese People，so my English is limited, but I really want to finish the kernel patch, so please do help me. Thanks again.
My phone kernel source:https://github.com/LineageOS/android_kernel_leeco_msm8996

**Comment by maozhifeng** [comment]
I used Linux deploy as the application to install kali Linux. The principle should be the same as kali nethunter.

**Comment by aircrack-ng** [comment]
As mentioned on the main page of the website at the bottom right, you have to kill the network managers prior to putting the card in monitor mode. That error is an indication another tools is using the wireless card.

**Comment by maozhifeng** [comment]
You mean I don't need to patch the kernel? But after I ran the kill manager command, the problem persisted:


root@localhost:~# airmon-ng check kill
root@localhost:~# airmon-ng start wlan1 && airodump-ng wlan1mom

CH  9 ][ Elapsed: 0 s ][ 2018-09-03 04:42

 BSSID              PWR  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID

 68:9F:F0:FF:DD:A8  -63        2        0    0  11  54e  WEP  WEP         CU_tGqa
 E4:D3:32:A3:B2:36  -55        4        0    0   1   54  WPA2 CCMP   PSK  TP-LINK_B236
 68:9F:F0:FF:A8:70  -76        4        0    0   1   54  OPN              CU_2tVn
 96:74:2A:AF:72:B1  -76        2        0    0   1   54  WPA2 CCMP   MGT  CMCC
 84:74:2A:AF:72:B1  -76        2        0    0   1   54  OPN              CMCC-WEB
 A6:74:2A:AF:72:B1  -76        2        0    0   1   54  OPN              EMS-FREE
 68:9F:F0:FF:A8:08  -37        3        0    0  10  54e  WEP  WEP         CU_TrkS
 68:9F:F0:FF:EB:F0  -81        2        0    0  10   54  WPA2 CCMP   PSK  CU_QnX9
 68:9F:F0:FF:D9:B0  -63        4        0    0  10   54  WPA2 CCMP   PSK  CU_2r6T
 68:9F:F0:FF:A8:60  -65        5        0    0  11   54  OPN              CU_P2YX

 BSSID              STATION            PWR   Rate    Lost    Frames  Probe



root@localhost:~# airmon-ng check kill
root@localhost:~# airodump-ng -w hack -c 10 --bssid 68:9F:F0:FF:A8:08 wlan1mon

 CH 10 ][ Elapsed: 18 s ][ 2018-09-03 04:42 ][ fixed channel wlan1mon: -1

 BSSID              PWR RXQ  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID

 68:9F:F0:FF:A8:08  -36 100      190        0    0  10  54e  WEP  WEP         CU_TrkS

 BSSID              STATION            PWR   Rate    Lost    Frames  Probe


root@localhost:~# aieplay-ng -0 0 -a 68:9F:F0:FF:A8:08  wlan1mon
04:48:58  Waiting for beacon frame (BSSID: 68:9F:F0:FF:A8:08) on ch
nnel -1
04:48:58  Couldn't determine current channel for wlan1mon, you shou
d either force the operation with --ignore-negative-one or apply a
ernel patch
root@localhost:~#

**Comment by aircrack-ng** [comment]
It seems to work fine the first time you do it. For the second time, there may be a tool using it. Run `airmon-ng check` when it happens to see if it sees a process that interferes. If not, then you need to find the one process using the wireless card and let us know so it can be added.

Another thing, please format the output using the ticks as explained in GitHub markdown formatting guide. It makes it easier to read.

**Comment by maozhifeng** [comment]
Sorry, I did not use the network card to find the occupied process.
I was wondering if it was because I put the network card driver htc_9271. Fw in the mobile /vendor/firmware/ directory. However, after I remove the driver from the mobile directory /vendor/firmware/, when I use the airmon-ng command in kali Linux, I can only display the phone's built-in network card. However, using the lsusb command, I can display the at9271 network card.

root@localhost:~# airmon-ng

PHY     Interface       Driver          Chipset

phy0    p2p0            cnss_wlan_pci   Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
phy0    wlan0           cnss_wlan_pci   Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)

root@localhost:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
root@localhost:~#

**Comment by maozhifeng** [comment]
I have installed the ar9271 driver in kali Linux
root@localhost:~# ls /lib/firmware/ath9k_htc/
htc_7010-1.dev.0.fw  htc_9271-1.dev.0.fw

But the drivers installed in kali Linux are not working

**Comment by aircrack-ng** [comment]
As mentioned, could you please use the 3 ticks to make the screen outputs more readable?

The driver is ath9k_htc, not htc_9271.

If the firmware wasn't loaded correctly, the interfaces wouldn't be present or airmon-ng would fail to put it in monitor mode.

Regarding that QCA6174, that is an entirely different device than the WN722N v1. The driver being used for it doesn't look like it supports monitor mode. And in any case, that device has a crappy firmware that crashes all the time which makes it useless.

Now, please use the [forum](https://forum.aircrack-ng.org/) for any further comment, this is for issue reporting and so far, you are trying to figure out how to use the device properly. I strongly recommend you use the code tags in the forum for the commands and their outputs.
