### ISSUE TITLE
QCA9377 airodump-ng unable to find any network

### ISSUE THREAD

**Issue by SharkEzz** [aircrack-ng/aircrack-ng#1949]
My computer is running Arch Linux (Linux 4.18.5 with latest linux-firmware)
It's an ACER Aspire E5-575G-57YQ with a Qualcomm Atheros QCA9377 wireless card.
airmon-ng report that the driver "ath10k_pci" is used.

Steps followed:

Put the wireless card in monitor mode -> airmon-ng start wlp3s0
The card is well in monitor mode after that : named wlp3s0mon.
I kill "wpa_supplicant" and "NetworkManager" in order to avoid any conflicts (same issue if I kill them before putting the card in monitor mode)

Scan for available network : airodump-ng wlp3s0mon
But I can wait an infinite time, airodump-ng will not find any networks... I can only see that the running time is increasing and the channels moving.

I tried once with a Gentoo based system (Calculate-Linux) and it worked fine but with Ubuntu,Debian,Arch Linux,Manjaro; it didn't worked.

I have no idea about what can cause this issue...

If you want any logs, just ask :+1:

**Comment by aircrack-ng** [comment]
You have to kill network managers PRIOR to putting the card in monitor mode as explained on the main page of the website.

As mentioned in a lot of other threads in the forum, as a general rule, when there is an issue, there might be some clues in `dmesg`.

Please take this to the [forum](https://forum.aircrack-ng.org/) first and if it turns out it's an issue in airodump-ng, then we'll let you know so you can open a bug report.

**Comment by msuleman67h** [comment]
I am having the same issue. It used to work. Now it doesn't show anything. What was the solution to this?

**Comment by pscyk** [comment]
same issue , no network shows up in monitor mode

**Comment by aircrack-ng** [comment]
If tcpdump or wireshark don't report any packet as well, that's a driver issue and there is nothing we can do. In that case, check for errors in dmesg and file a detailed issue in the linux-wireless mailing list.

If packets are reported in these tools (in monitor mode), then definitely update the ticket.

**Comment by ghost** [comment]
> If tcpdump or wireshark don't report any packet as well, that's a driver issue and there is nothing we can do. In that case, check for errors in dmesg and file a detailed issue in the linux-wireless mailing list.
> 
> 
> 
> If packets are reported in these tools (in monitor mode), then definitely update the ticket.


Wireshark does show packets on my system but airdump-ng doesn't show any Probes

**Comment by aircrack-ng** [comment]
@slythno don't create a new bug when there is no need to. As explained in #2300, take it to the forum.
