### ISSUE TITLE
aircrack-ng AVX2 detection bug

### ISSUE THREAD

**Issue by exaghost** [aircrack-ng/aircrack-ng#1950]
Hi !
I think there is a bug in AVX2 detection in aircrack-ng 1.3 Debian and Windows x64 OSes. I have an Intel i5 3337U CPU, that lacks AVX2, just AVX. Aircrack-ng says I have AVX2.

**Comment by jbenden** [comment]
Hello,

I am curious as to the output of running:

```
aircrack-ng -u
```

Would you mind posting this output here?

Thanks,
-Joe

**Comment by exaghost** [comment]
Hi !
That's strange. :S

Microsoft Windows [Version 10.0.17134.228]

d:\Programok\aircrack-ng-1.3-win\bin\32bit>aircrack-ng -u
Vendor          = Intel
Model           = Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
Features        = MMX,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AES-NI,AVX
Hyper-Threading = No
CPU cores       = 4
SIMD size       = 4 (128 bit)
SIMD size in use= 4 (128 bit)

d:\Programok\aircrack-ng-1.3-win\bin\64bit>aircrack-ng -u
Vendor          = Intel
Model           = Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
Features        = MMX,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AES-NI,AVX
Hyper-Threading = No
CPU cores       = 4
SIMD size       = 4 (128 bit)
SIMD size in use= 4 (128 bit)

Seems OK on Windows 10 x64 :$ I'll test it on Debian....

**Comment by exaghost** [comment]
Ahhhh I got it !
d:\Programok\aircrack-ng-1.3-win\bin\64bit>aircrack-ng --simd-list
avx2 avx sse2 generic
That's what i remember...

**Comment by jbenden** [comment]
The option `--simd-list` shows all available run-time modules available. It doesn't mean that your machine HAS them, but rather that the software would USE avx2, if available. :)
