### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726) on airgraph-ng

### ISSUE THREAD

**Issue by Squishy33** [aircrack-ng/aircrack-ng#1951]
hi,
i just recently installed using `sudo apt-get install airgraph-ng ` airgraph-ng and im getting an SSL certificate error, and for all aircrack-ng suite it's the only one whoz giving this error. the command that i have tried is,

`sudo airgraph-ng -i testsample.txt -o image.png -g CPG`

I tried both graphic type and both returned the same SSL error. I would appreciate an assistance with this.
im running `kali2-amd64 #1 SMP Debian 4.16.16-2kali1 (2018-06-25) x86_64 GNU/Linux`
 thanx

**Comment by aircrack-ng** [comment]
First thing to do is `apt update && apt dist-upgrade` then reboot.

Then try again and report the exact (whole output) error message, including the command.

**Comment by Squishy33** [comment]
it's been resolved. the problem was that the link for oui.txt `http://standards.ieee.org/regauth/oui/oui.txt ` has been obsolete the new link is `http://standards-oui.ieee.org/oui.txt` which need to be changed in `libOuiParse.py`
