### ISSUE TITLE
airodump-ng: error while loading shared libraries: libaircrack-osdep-1.3.0.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by augustomurri** [aircrack-ng/aircrack-ng#1952]
root@raspberrypi:/home/pi# airodump-ng wlan1mon
airodump-ng: error while loading shared libraries: libaircrack-osdep-1.3.0.so: cannot open shared object file: No such file or directory

anyone can help?

**Comment by aircrack-ng** [comment]
Use the current git master. It was fixed in 02b66f3 and c6ca3f3. More details can be found in #1927

Reopen the ticket if it still happens

**Comment by RemiZlatinis** [comment]
Run "sudo ldconfig" after clean install and try again.
