### ISSUE TITLE
[Airodump-ng] maximum speed supported by the AP displayed not correct

### ISSUE THREAD

**Issue by 3l33t** [aircrack-ng/aircrack-ng#1955]
what's wrong ?
help me please

![imageedit_2_4666515417](https://user-images.githubusercontent.com/33633735/45599520-17233e80-ba17-11e8-9eff-a5e5e9da5f26.jpg)

**Comment by aircrack-ng** [comment]
It doesn't look wrong, those AP are 802.11n. First one most likely have 1 stream and the others, 2 or 3 streams.

Could you put the pcap somewhere with just the beacons for all 3 APs?

**Comment by aircrack-ng** [comment]
Please reopen the ticket when the pcap is availble
