### ISSUE TITLE
airmon-ng improvement request

### ISSUE THREAD

**Issue by ZerBea** [aircrack-ng/aircrack-ng#1965]
Please consider to activate monitor mode for the physical interface instead of creating a logical 
monitor mode interface.
A logical interface is just a normal interface, unless you use it in combination, in which case having to shift between different channels, or having to share a single channel, cuts the throughput by (roughly) a factor of 1/N, where N is the number of interfaces on the same physical device.
If you leave the physical interface manged, it will slow us down.

**Comment by ZeroChaos-** [comment]
Sorry, can you break this down for me like I'm not an expert?  I have no idea what you are trying to say here.

mac80211 does have a "phy" interface which is then linked to a "logical" interface, but you cannot directly sniff on the phy interface afaik.  airmon-ng doesn't keep multiple vifs around unless you pass --elite, in which case, stop passing --elite if you don't like that, that's literally all it does

**Comment by ZerBea** [comment]
Sorry my fault. I did not notice that airmon-ng use iw to add(!) a monitor mode interface:
(iw phy ${PHYDEV} interface add ${1%mon} 
But it's not a big problem. I'll warn the user about this behavior if he want to use hcxdumptool on monitor interface created by airmon-ng.
