### ISSUE TITLE
Airmong-ng Raspi headless

### ISSUE THREAD

**Issue by Jazzbil** [aircrack-ng/aircrack-ng#1967]
I have rasp3 installed on Kali Linux full using headless connection with ssh
Rasberry using brodcam wifi wlan0 connect my phone for ssh 
And I have WiFi card realtek 8187 WiFi card wlan1 using for monitor mode 

When I start monitor mode on wlan1 all WiFi card disable and I lose my ssh connection is it normal . How can I solve this problem ?

**Comment by aircrack-ng** [comment]
This is not an issue with the tools. Please use the forum which is better suited for support.
