### ISSUE TITLE
Windows - Wireless network adaptar not supported

### ISSUE THREAD

**Issue by stefan9999991** [aircrack-ng/aircrack-ng#1969]
Hello,

When I try to use the deauth function from your program aireplay-ng I get the following error:
`Adapter <wlan#mon> not supported`

I did some research and found this:
https://github.com/aircrack-ng/aircrack-ng/issues/1769

This still didnt help me. Can someone explain what I need to do to get this function to work.
My network card is a **Intel(R) Dual Band Wireless-AC 8265**.

Thanks,
Stefan

**Comment by binarymaster** [comment]
It makes no sense to open such issues before #1775 is resolved.

**Comment by stefan9999991** [comment]
> It makes no sense to open such issues before #1775 is resolved.

It makes no sense that its taking 7 months and there still no solution...

**Comment by aircrack-ng** [comment]
Duplicate
