### ISSUE TITLE
The requested URL /aircrack-ng-0.9.3-win.zip was not found on this server.

### ISSUE THREAD

**Issue by stefan9999991** [aircrack-ng/aircrack-ng#1971]
When I click aircrack-ng-0.9.3-win.zip from:
https://www.aircrack-ng.org/doku.php?id=downloads

I get this error:
Not Found
The requested URL /aircrack-ng-0.9.3-win.zip was not found on this server.

**Comment by aircrack-ng** [comment]
Rename the extension to .piz. It's a workaround due to an ISP issue.

Just FYI, this version is only useful if you have an Airpcap device.
