### ISSUE TITLE
Aircrack-ng tests intermittently fails on DragonflyBSD

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1973]
# Issue type

Defect - Compilation or `make check` issue

# Defect
## How to reproduce the issue

OS: DragonflyBSD 5.22 
Revision: 9d2a96c
Packages installed: pkgconf shtool libtool gcc7 automake autoconf pcre sqlite3 gmake cmocka libgcrypt

Some tests intermittently fail, returning exit code 1 and output is normal (not crashing).

### GCC 7

Using  `env CC=gcc7 CXX=g++7 CFLAGS="-ggdb -O0" ./configure --disable-dependency-tracking --with-gcrypt`, running tests fails Aircrack-ng tests 13,14, 15 and 16. Failures are intermittent and sometimes it passes all and most of the time a combination of one or more of the mentioned tests fail. No segfault, it just doesn't exit with 0.

Without the CFLAGS above, test 2, 3 and/or 4 also fails intermittently.

**Note:** CMAC is marked as supported

### GCC 5.4.1 (default)

Using `./configure --disable-dependency-tracking --with-gcrypt`, tests 2, 3,4 8, 9, 13, 15 and 16 intermittently fail.

**Note:** CMAC is marked as unsupported

**Comment by aircrack-ng** [comment]
As mentioned in #1974, make check rarely succeeds.

**Comment by jbenden** [comment]
In the `configure` line, add the environment variable `MAKE=gmake` to permit the Autoconf scripting to function. Additionally, remove the `--disable-dependency-tracking` flag, as it is not required.

**Comment by jbenden** [comment]
Tests are running, with occasional `SEGFAULT` turning `_exit` inside of the function `clean_exit`.

I am seeing similar results on FreeBSD CI system. So, there is a problem with cleanly shutting down.

**Comment by jbenden** [comment]
I've gotten test 14 to run, show the loaded packet count, shows that it has a target; then doesn't actually run the cracking session. This has to be a bug here.

**Comment by jbenden** [comment]
Debugging shows a few queue problems. This will need to wait, for now.
