### ISSUE TITLE
Aircrack-ng fails to open crypto lib (missing) on AVX512 CPU

### ISSUE THREAD

**Issue by george369** [aircrack-ng/aircrack-ng#1975]
Getting this error when trying to run aircrack-ng:

```
Could not open '/usr/lib/x86_64-linux-gnu/libaircrack-crypto-x86-avx512.so': /usr/lib/x86_64-linux-gnu/libaircrack-crypto-x86-avx512.so: cannot open shared object file: No such file or directory
```

What version of aircrack-ng are you running?
Version 1.4

And what is the output of lscpu?
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
Stepping:            4
CPU MHz:             3312.006
BogoMIPS:            6624.01
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            14080K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat arch_capabilities
```

Is it coming from a package or compiled from source?
Same error occurs either or.

If package, what OS?
```
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2018.4"
VERSION_ID="2018.4"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```

Running with VMWare on a Win10 machine.

If from source, what was the ./configure command?
./configure

Tried a fresh install of Kali but no luck. Also tried fresh installs of aircrack with and without avx512 (specified in ./configure command).

Thank you!

**Comment by jbenden** [comment]
Hello,

I think it's detected that AVX512F is available, and looking for the shared libraries.

If you do NOT want AVX512F, then there is a bug - it shouldn't have crashed without it present.

If you DO want AVX512F, then an additional `./configure` parameter is needed.

Best regards,
-Joe

**Comment by george369** [comment]
Hi Joe thank you for your reply. 
The error is persistent even if AVX512 is specified in the ./configure parameter.
Either, or, the libraries cannot be detected. 
Have tried both cases WITH and WITHOUT AVX512 enabled and the outcome is the same.
Thanks.

**Comment by jbenden** [comment]
Would you mind posting the `config.log` and all output of `./configure  --with-avx512=yes && make V=1 && make check V=1`.

Thanks in advance!
-Joe

**Comment by george369** [comment]
A. Performed a clean installation of Kali.

B. Manually performed/installed the following:
  1) apt-get install pkg-config
  2) apt-get install libssl-dev
  3) apt-get install libnl-3-dev linbl-genl3-dev
  4) apt-get install libtool
  5) apt-get install autotools-dev
  6) apt-get install autoconf

C. Install aircrack 1.4 and use ./configure --with-experimental --with-avx512

Program works. It is still puzzling to me why this error showed up but in any case now program works fine. The program does not work if avx-512 is not specified in the ./configure command.

**Comment by RootSrc** [comment]
Hi there, I unfortunately have been having this exact same problem, first it was apparent to be on my Parrot install, tried reinstalling v1.4 manually with no avail, so thinking this might be a distro problem I tried it two times with a fresh install of Kali Linux, same problem coming straight from the pre installed package:

`Could not open '/usr/lib/x86_64-linux-gnu/libaircrack-crypto-x86-avx512.so': /usr/lib/x86_64-linux-gnu/libaircrack-crypto-x86-avx512.so: cannot open shared object file: No such file or directory`

Trying again on Kali performing an install of v1.4 manually, it had seemed to work fine with the `/configure --with-avx512=yes && make V=1 && make check V=1` until I ran it with a test cap file, as it was trying to crack it the "Current passphrase:" part would show unknown characters, then crash with a Seg fault mid way through.

Finally the way I had fixed it at last by again installing manually and searching for the avx-512.so file, and doing the following cp command: 

`cp aircrack-ng/src/aircrack-crypto/.libs/libaircrack-crypto-x86-avx.so /usr/lib/x86_64-linux-gnu/libaircrack-crypto-x86-avx512.so`

This seemed to fix it so far, nothing unusual happening.

**Comment by jbenden** [comment]
Thanks for the detailed report.

I've made a change to load the maximum possible engine, based on what's on disk vs. what the CPU supports. Local testing on an AVX2 machine, with AVX512F compiled, does correctly load the AVX2 engine, now.

Thanks!
-Joe

**Comment by atulbhagat** [comment]
When i type aircrack-ng 
It shows

Could not open '/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so': dlopen failed: library "/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so" not found.

**Comment by atulbhagat** [comment]
Could not open '/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so': dlopen failed: library "/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so" not found

**Comment by termux4me2** [comment]
Could not open '/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so': dlopen failed: library "/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so" not found
