### ISSUE TITLE
Auto Update in KALI !

### ISSUE THREAD

**Issue by talal2** [aircrack-ng/aircrack-ng#1976]
Hi !
When i do ===> 'apt-get update && apt-get dist-upgrade' in kali,, aircrack doesn't receive latest update automaticaaly, i need to compile from source code .
Is their any solution to get updated with kali commands ?

                             Thanks in advance ;-) :-)

**Comment by aircrack-ng** [comment]
Kali has the latest, 1.4, as of a few days ago. It just takes a little while for new versions to hit the repository. It took less than 2 weeks.

You could use our packagecloud.io repository, but it's best to wait; it's unknown how apt/dpkg will behave when the update hits Kali repository.
