### ISSUE TITLE
Programs link with installed libaircrack-osdep library instead of just-built library

### ISSUE THREAD

**Issue by ryandesign** [aircrack-ng/aircrack-ng#1977]
On macOS, aircrack-ng 1.3 installed libaircrack-osdep.0.dylib while aircrack-ng 1.4 now builds libaircrack-osdep-1.3.0.dylib. If aircrack-ng 1.3 is installed while aircrack-ng 1.4 is built, the aircrack-ng 1.4 programs are built linked against the installed aircrack-ng 1.3 osdep library instead of the just-built aircrack-ng 1.4 osdep library. Then, when aircrack-ng 1.3 gets uninstalled and aircrack-ng 1.4 gets installed, the programs are broken because they are linked with a library that no longer exists:

```
$ /opt/local/sbin/airodump-ng
dyld: Library not loaded: /opt/local/lib/libaircrack-osdep.0.dylib
  Referenced from: /opt/local/sbin/airodump-ng
  Reason: image not found
Abort trap: 6
```

# Issue type

- Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed

# System information

- OS: macOS High Sierra
- CPU: x86_64
- Wireless card and chipset (if relevant):

# Aircrack-ng version

- Version: 1.4
- Commit Revision hash:

# Defect
## How to reproduce the issue

I'm on macOS; not sure if this issue is macOS-specific
Install aircrack-ng dependencies to particular prefix
Install aircrack-ng 1.3 in that prefix
Build aircrack-ng 1.4 in that prefix
Use `otool -L` to inspect the programs that got built

Actual:

```
$ otool -L ./airodump-ng
./airodump-ng:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/local/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.10.0)
	/opt/local/lib/libaircrack-osdep.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Expected:

```
$ otool -L ./airodump-ng
./airodump-ng:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/local/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.10.0)
	/opt/local/lib/libaircrack-osdep-1.3.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

The reason for the problem is that the `-L` flags are in the wrong order. Looking, for the sake of an example, at the compile line for airodump-ng, when aircrack-ng 1.3 is installed:

```
libtool: link: ccache /usr/bin/clang -pthread -Wall -Wno-unused-command-line-argument -O3 -std=gnu99 -Wpointer-arith -Wstrict-overflow=2 -Wstrict-prototypes -fvisibility=hidden -fstack-protector-strong -Wno-array-bounds -o airodump-ng airodump_ng-airodump-ng.o  -L/opt/local/lib -lpthread -lz -lpcre -Laircrack-osdep -laircrack-osdep ./.libs/libaclib.a -Laircrack-util /path/to/src/aircrack-util/.libs/libaircrack-util.a -lcrypto -ldl -lm -pthread
```

Here's that same compile line when aircrack-ng is not installed:

```
libtool: link: ccache /usr/bin/clang -pthread -Wall -Wno-unused-command-line-argument -O3 -std=gnu99 -Wpointer-arith -Wstrict-overflow=2 -Wstrict-prototypes -fvisibility=hidden -fstack-protector-strong -Wno-array-bounds -o .libs/airodump-ng airodump_ng-airodump-ng.o  -L/opt/local/lib -lpthread -lz -lpcre -Laircrack-osdep /path/to/src/aircrack-osdep/.libs/libaircrack-osdep.dylib ./.libs/libaclib.a -Laircrack-util /path/to/src/aircrack-util/.libs/libaircrack-util.a -lcrypto -ldl -lm -pthread
```

Odd differences:

1. When aircrack-ng 1.3 is installed, the program gets written to `airodump-ng` instead of `.libs/airodump-ng`. I don't know why this is happening but it doesn't seem to cause any other problems.
2. When aircrack-ng 1.3 is installed, the program links with `-Laircrack-osdep -laircrack-osdep` instead of `-Laircrack-osdep /path/to/src/aircrack-osdep/.libs/libaircrack-osdep.dylib`. In the second form, the `-Laircrack-osdep` flag is unnecessary since the full path to the built dylib is specified. The first form `-Laircrack-osdep -laircrack-osdep` would work were it not for the fact that dependency flags `-L/opt/local/lib -lpthread -lz -lpcre` are specified first, so any libaircrack-osdep in /opt/local/lib will be found first.

**Comment by jbenden** [comment]
Hello,

With the merge of #2016; the built libraries should now be linked.

Please let us know if problems persist.

Thanks,
-Joe
