### ISSUE TITLE
Assertion failed: (ap_cur->wpa.state > 0), function main, file aircrack-ng.c, line 6738.

### ISSUE THREAD

**Issue by maydinal** [aircrack-ng/aircrack-ng#1978]
See below

**Comment by maydinal** [comment]
hello;

I am trying to run aircrack-ng on mac os high sierra with below content:

```
aircrack-ng -1 -a 2 -b <BSSID> <airport_sniff_file> -w <password_list>

but it creates below error:

Opening airportSniffXoP4FY.cap.
Read 21422 packets.

1 potential targets

Assertion failed: (ap_cur->wpa.state > 0), function main, file aircrack-ng.c, line 6738.
Abort trap: 6
```

I uninstalled and reinstalled aircrack-ng package (aircrack-ng-1.4.high_sierra.bottle.tar.gz) as needed but no change
I also ran airodump-ng-oui-update but still no change, same error message is thrown.

attached is the airport sniff file for your analysis

fyi
best regards.

**Comment by maydinal** [comment]
[sniff.zip](https://github.com/aircrack-ng/aircrack-ng/files/2481612/sniff.zip)

**Comment by aircrack-ng** [comment]
The following network triggers it:

`aircrack-ng -a 2 airportSniffXoP4FY.cap -w <wordlist> -b FC:4A:E9:5C:B1:8C`

It also happens on Linux and using git master (155b9afd).

**Comment by maydinal** [comment]
so what is your recommendation  for resolution?
or I am doing something wrong that needs to be corrected by me ?
thanks for the clarification,
kind regards

**Comment by aircrack-ng** [comment]
The bug is confirmed, so it will be fixed and a new test will probably be added. We already have a few tests for WPA1 and WPA2 and as mentioned the bug only happens for some networks in the capture file, not all of them.

FYI, `-1` is not necessary and it is ignored because it's for PTW only (which is a WEP thing). `-a` is very rarely needed, only when a network is incorrectly detected.

**Comment by maydinal** [comment]
thanks for the update and command process advise.
I will be waiting for the fix,
kind regards

**Comment by tgoods** [comment]
Hello, I'm experiencing the same issue on marshmallow for the nexus 6. I've tried it on my two routers and am getting the "assertion failed" error message in both cases. When trying the same attacks on the same routers with my main build, I'm not receiving any error messages. I'm in the process of adding dictionaries to my arm build but have only tried the attack on my nexus using a crunch feed. I'll let you know if the dictionary attack works.

**Comment by tgoods** [comment]
Yep. No luck with the dictionary attack. Any idea if a recent update required aircrack to be dependent on other packages? Maybe those packages could have something to do with it (If said packages aren't  compatible, or installed by default with said builds)?

**Comment by walidr** [comment]
I am having the same error as maydinal, is there any news regarding this bug guys ?

**Comment by jbenden** [comment]
Hi!

I've found that the "in question" network has no data available (eapol). It seems to be a blank entry. Is this right?

```
(gdb) print *ap_cur
$5 = {bssid = "\374J\351\\\261\214", essid = "NetMASTER Uydunet-B189\000\000\000\000\000\000\000\000\000\000", lanip = "\000\000\000", ivbuf = 0x0, uiv_root = 0x0, ivbuf_size = 0, 
  nb_ivs = 0, nb_ivs_clean = 0, nb_ivs_vague = 0, crypt = 3, eapol = 0, target = 1, st_1st = 0x0, stations = 0x7ffff0030b00, wpa = {stmac = "\000\000\000\000\000", 
    snonce = '\000' <repeats 31 times>, anonce = '\000' <repeats 31 times>, pmkid = '\000' <repeats 15 times>, keymic = '\000' <repeats 15 times>, eapol = '\000' <repeats 255 times>, 
    eapol_size = 0, keyver = 0 '\000', state = 0 '\000'}, ptw_clean = 0x0, ptw_vague = 0x0}
(gdb) print ap_cur.wpa 
$6 = {stmac = "\000\000\000\000\000", snonce = '\000' <repeats 31 times>, anonce = '\000' <repeats 31 times>, pmkid = '\000' <repeats 15 times>, keymic = '\000' <repeats 15 times>, 
  eapol = '\000' <repeats 255 times>, eapol_size = 0, keyver = 0 '\000', state = 0 '\000'}
```

If this *is* a blank entry, I should filter it out as unable to process. If it is valid, then the assertion should be removed.

Ideas?

Thanks,
-Joe

**Comment by aircrack-ng** [comment]
Yes, it only happens when the network has no data and advertised as "No Data - WEP or WPA" and when `-a 2` is used, thus forcing WPA mode.
