### ISSUE TITLE
aircrack-ng-1.4's DEFAULT_STATIC_LIB_SEARCH_PATHS can cause compilation failures

### ISSUE THREAD

**Issue by ikelos** [aircrack-ng/aircrack-ng#1979]
# Issue type

- Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed

# System information

- OS: Gentoo Linux
- CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz GenuineIntel
- Wireless card and chipset (if relevant): Not relevant

# Aircrack-ng version

- Version: 1.4
- Commit Revision hash: Release version (still present in 155b9afd)

# Defect
## How to reproduce the issue

Attempt to compile aircrack-ng-1.4 on a multilib system, where `/usr/lib` is not the native architecture.

```
  CXXLD    aircrack-ng
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libsqlite3.so when searching for -lsqlite3
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libz.so when searching for -lz
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libcrypto.so when searching for -lcrypto
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/libhwloc.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1270: aircrack-ng] Error 1
```

This is because the `ax_ext_have_static_lib.m4` file added in 1.4 lists a fixed set of directories to check for libraries (`DEFAULT_STATIC_LIB_SEARCH_PATHS`).  These include `/usr/lib` but do not include `/usr/lib64`, for example.  If the distribution in use allows a multilib architecture and stores 32-bit libraries in `/usr/lib` and 64-bit libraries in `/usr/lib64`, the compiler will find the 32-bit libraries and then fail to link them for having an incompatible/wrong format.

[config.log](https://github.com/aircrack-ng/aircrack-ng/files/2495665/config.log)

## Related issues

[Definition of DEFAULT_STATIC_LIB_SEARCH_PATHS](https://github.com/aircrack-ng/aircrack-ng/blob/master/build/m4/ax_ext_have_static_lib.m4#L55)

**Comment by ChrisLundquist** [comment]
as a work around does `./configure LDFLAGS="-L/usr/lib64/"` help?

**Comment by ikelos** [comment]
Yep, that does appear to allow completion of the compilation.

**Comment by ChrisLundquist** [comment]
@jbenden knows way more about this stuff. My first thought is we may need to bring in `pkg-config`.
I haven't used it too much though, so I don't have an informed opinion.

An alternative stop gap could be to include `/usr/lib64` and friends into the hard coded list (which would at least let things work out of the box)

A third option would be to document the need to add `LDFLAGS=-L...` and `CFLAGS=-I...` on some platforms for configure (which seems even less ideal).

For cross compiling we'd probably need/want `./configure --sysroot ... --host ...` but that's probably a little more out there, and has lots of sharp edges with some gcc toolchains having the option specified internally. `gcc -v | grep sysroot` -> `--with-sysroot=/`

**Comment by alonbl** [comment]
Hi,
Can you please checkout #1982?
Thanks!

**Comment by ikelos** [comment]
Hi @alonbl,

Thanks for the patch!  5:)  Unfortunately that still fails when compiling with sqlite support, because of the following hard coded paths:

https://github.com/aircrack-ng/aircrack-ng/blob/master/build/m4/ax_lib_sqlite3.m4#L86
https://github.com/aircrack-ng/aircrack-ng/blob/master/build/m4/ax_lib_sqlite3.m4#L95

which probably also require use of the STATIC_LIB_LIBDIR variable.  When those are changed (and your patch is applied, with the appropriate environment variable set), compilation completes.

**Comment by ikelos** [comment]
If it's possible to do, I think using `pkg-config` would resolve a great many of these issues, but I don't know how hard converting the existing autotools stuff over to using it would be.

**Comment by alonbl** [comment]
I tried to fix the sqlight3 issue, please check.
I fully agree that writing standard autoconf code with pkg-config and other best practices will be much simpler and compatible, however, looking at the current implementation, huge work was invested in a proprietary build system, I think it will be easier to accept #1982 to resolve issue than rewrite.

**Comment by ikelos** [comment]
Sure, there's clearly been a lot of work on the current implementation.  I've rechecked #1982 and with the `HOST_LIBDIR_NAME` variable set it does allow complete compilation.  Thanks for the speedy update!  5:)
