### ISSUE TITLE
pcap files saved by airodump-ng,  if opend by omnipeek, the channel always be 1

### ISSUE THREAD

**Issue by sigusr1** [aircrack-ng/aircrack-ng#1985]
AP is working on channel 3, however, when I  open the pcap file captured by airodump-ng, the channel displayed 
in omnipeek always be channel 1.

The master branch has the problem too.
My os is ubuntu 16.04 LTS.
My wireless card info : Intel Corporation wireless 8260(rev 2a)

**Comment by aircrack-ng** [comment]
Channel isn't saved in the PCAP by airodump-ng, so omnipeek most likely assumes channel 1.
