### ISSUE TITLE
Aircrack-ng 1.4 segfault when loading IVS file

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1989]
# Issue type

- Defect - Crash
- Defect - Unexpected behavior (confirmed in the forum)

# Aircrack-ng version

- Version: 1.4

# Defect
## How to reproduce the issue

Aircrack-ng 1.4 fails to load [ivsonly-01.ivs.zip](https://github.com/aircrack-ng/aircrack-ng/files/2568727/ivsonly-01.ivs.zip) where 1.3 works just fine.

```
root@kali:~# aircrack-ng ivsonly.ivs 
Opening ivsonly.ivse wait...
Read 12763 packets.

   #  BSSID              ESSID                     Encryption

   1  34:62:88:F3:03:82                            Unknown

Choosing first network as target.

Opening ivsonly.ivse wait...
Segmentation fault
```

Aircrack-ng 1.3 fails to crack it (not an issue, most likely due to not having enough IVs) but loads it, sees ESSID/encryption just fine and is able to start cracking it:

```
root@kali:~# aircrack-ng ivsonly.ivs 
Opening ivsonly.ivs
Read 12763 packets.

   #  BSSID              ESSID                     Encryption

   1  34:62:88:F3:03:82  NULL-WEP                  WEP (12762 IVs)

Choosing first network as target.

Opening ivsonly.ivs
Attack will be restarted every 5000 captured ivs.
Starting PTW attack with 12762 ivs.
...
```

## Original issue

https://forum.aircrack-ng.org/index.php/topic,2277.0.html

**Comment by aircrack-ng** [comment]
There is more to the issue. According to the forum post:

> Aircrack will ask to choose the BSSID with the corresponding line number: in this case the Encryption is still "Unknown", but after choosing the target AP/BSSID, Aircrack-ng will start its work.

**Comment by jbenden** [comment]
The program does two passes on loading PCAPs now.

The first pass does not load any AP detail (like IVs, EAPOL, etc), but is used to enumerate networks for selection. (This is why the information is unknown at the prompt.) The second pass actually loads the data for the selection.

We can't change this around much, or we'll be unable to load many gigabyte large data-sets.

**Comment by jbenden** [comment]
Oopps...

**Comment by aircrack-ng** [comment]
Closing this, as #1997 describes the second part of the issue.
