### ISSUE TITLE
Passphrase not in directory

### ISSUE THREAD

**Issue by YahavBahat** [aircrack-ng/aircrack-ng#1990]
When I try to crack the WiFi password, using the handshake key in the .cap file, The cracking procedure is always gets stuck at 97.xx percent, with the error:
Passphrase not in dictionary.
,After multiple times of trying. I'm using the rockyou.txt word lists. 
I don't think this is the source of the problem or if something went wrong there, but I edited the rockyou text and put the real password just for test and it didn't work again either, but then I edited it back, again I don't think its the problem but I'm beginner in this.

**Comment by aircrack-ng** [comment]
This sounds like a technique issue, please take it to the forum and we'll reopen this bug if it is confirmed (and it will need more details as explained when "Bug report" was selected).

**Comment by ZerBea** [comment]
Maybe the detection of handshakes doesn't work like expected:
https://github.com/aircrack-ng/aircrack-ng/issues/1993
