### ISSUE TITLE
"no EAPOL data" message on a file that could be cracked with older versions

### ISSUE THREAD

**Issue by richardpringle** [aircrack-ng/aircrack-ng#1995]
# Issue type

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: MacOS 10.14
- CPU: irrelevant
- Wireless card and chipset (if relevant): Also irrelevant

# Aircrack-ng version

- Version: master
- Commit Revision hash: 75e2e4bd52800da86a73fef9e1bcd0c22c4bcbae

# Defect
## How to reproduce the issue

Run `aircrack-ng` on the attached file. You will get the message: 
```
Packets contained no EAPOL data; unable to process this AP.
```

However, `aircrack-ng@1.0` works fine when WPA is specified. The key is `38370216` (don't worry, the packets came from a sandbox environment that is meant to be hacked).

## Related issues

#1978 -> I would have posted in there but the issue is closed.

# File:
[capture.tar.gz](https://github.com/aircrack-ng/aircrack-ng/files/2637242/capture.tar.gz)

**Comment by richardpringle** [comment]
If this is by design, please explain and feel free to close the issue.

**Comment by jbenden** [comment]
For some reason, I am unable to find an IVS or PCAP inside of that tarball. It recursively decompresses to an eventual zero byte file.

If this is in error, please post a correct file; otherwise, I've closed the ticket.
