### ISSUE TITLE
Aircrack-ng hangs with ivs file

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#2002]
# Issue type

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: Linux
- CPU: Irrelevant
- Wireless card and chipset (if relevant): Irrelevant

# Aircrack-ng version

- Version: 1.5.2

# Defect
## How to reproduce the issue

Aircrack-ng hangs with [ivsonly-01.ivs.zip](https://github.com/aircrack-ng/aircrack-ng/files/2568727/this) IVS file. It fails to crack and hitting Ctrl-C doesn't exit.

```

                            Aircrack-ng 1.5.2


                 [00:00:02] Tested 99406 keys (got 12762 IVs)

   KB    depth   byte(vote)
    0   21/ 24   82(15360) 42(15104) 61(15104) 8D(15104) C1(15104) 
    1   20/ 21   55(15580) 65(15360) E6(15360) FB(15360) 58(15324) 
    2   22/  2   92(15324) 43(15212) 02(15104) 42(15104) 93(15104) 
    3    4/  5   CC(17116) 6D(16604) F2(16384) 6A(16348) 8A(16312) 
    4   17/  4   DE(15836) 1C(15652) 75(15652) D1(15652) 0B(15616) 

Failed. Next try with 15000 IVs.
^C
Quitting aircrack-ng...
^C
Quitting aircrack-ng...
^C
Quitting aircrack-ng...
```

## Related issues

Same file as #1989 

Forum post: https://forum.aircrack-ng.org/index.php/topic,2417.0.html

**Comment by aircrack-ng** [comment]
Culprit is b6465ed.

Commit right before it, 575bc2b, works just fine.

**Comment by TeusDev** [comment]
This still happening for me! How to fix ?

**Comment by aircrack-ng** [comment]
Download latest sources, compile, install, done. Or alternatively, download 1.5.2, patch with the 2 commits referencing this issue.

**Comment by TeusDev** [comment]
> Download latest sources, compile, install, done. Or alternatively, download 1.5.2, patch with the 2 commits referencing this issue.

can u link me to some kind of tutorial how to patch with commits? i'm completely noob in linux and'stuff...

**Comment by aircrack-ng** [comment]
There is no tutorial because git commits are patches and can just be applied with `patch`

So, just download 1.5.2 source, unpack it, download the patches (click on the links then hit raw then save that content (use wget on the URL), then patch it: `patch -i patch.diff`. You may have to adjust `-N` (`-Np1` or `-Np0`) but that's about it. Then finally compile it like normal.

Sometimes patch don't apply anymore, so you have to edit the code manually.
