### ISSUE TITLE
Compiling Error 

### ISSUE THREAD

**Issue by timeisflowing** [aircrack-ng/aircrack-ng#2005]

**Comment by aircrack-ng** [comment]
Default gcc version for 18.04 is 7 and you're running 4.8.5.

Even forcing 4.8, current git doesn't fail:
```
apt install gcc-4.8 g++-4.8
autoreconf -i
env CC=gcc-4.8 CXX=gcc-4.8 ./configure
make
```

We'll need more details on your system:
- Output of ./configure (or autogen.sh) or at least output from the summary screen of configure.
- Any reason you're running such an old compiler? And why it's the default compiler on your system
- Aircrack-ng version
- Anything else useful about your system/CPU?

Please don't include screenshot of text, copy and paste text then use the ticks as mentioned in the template for bug reports for any console command and/or output.

**Comment by timeisflowing** [comment]
I'm using amd CPU

i Just tried gcc version 7.3.0 compiled no problem, the problem is because of all the old compilers. 

(Old compilers very little safe compile) :+1: 

config.log attached
[config.log](https://github.com/aircrack-ng/aircrack-ng/files/2706391/config.log)

I thought maybe it would help.

**Comment by aircrack-ng** [comment]
Can't reproduce the issue. There something unusual to your system compared to a default Ubuntu 18.04 (or even .1). If you find what caused or can find a way for us to reproduce the issue, please reopen this ticket.
