### ISSUE TITLE
airodump write newest result in output file

### ISSUE THREAD

**Issue by codenoid** [aircrack-ng/aircrack-ng#2008]
after a client disconnected, airodump-ng still write the old data of client

**Comment by aircrack-ng** [comment]
Yes. Could you elaborate on what should be done and what files you are talking about?

If you are talking about the text files (csv, xml), they also contain a last seen that can be processed by any tool that needs to filter out disconnected clients.

**Comment by codenoid** [comment]
hold for a while, i still find way to "real-time" reading data from airodump-ng, what i already try is redirect  airodump-ng stdout to file, and get detail from the xml, i'll try the `last seen` section, thank you
