### ISSUE TITLE
error installing: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by astonly** [aircrack-ng/aircrack-ng#2019]
S-MacBook-Pro:aircrack-ng Stas$ autoreconf -i
S-MacBook-Pro:aircrack-ng Stas$ ./configure --with-experimental
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking target system type... x86_64-apple-darwin18.2.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin18.2.0 file names to x86_64-apple-darwin18.2.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin18.2.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking for brew... /usr/local/bin/brew
checking for /usr/local/Homebrew... yes
checking for /opt/local/include... no
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include... no
checking Default static library search path...  		/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0 		/opt/lib/x86_64-apple-darwin18.2.0 		/opt/lib 		/usr/local/lib/x86_64-apple-darwin18.2.0 		/usr/local/lib 		/usr/lib/x86_64-apple-darwin18.2.0 		/usr/lib 		/lib 		/opt/lib/x86_64-apple-darwin18.2.0 		/opt/lib 	
checking for OPENSSL_init in -lcrypto... yes
checking openssl/crypto.h usability... yes
checking openssl/crypto.h presence... yes
checking for openssl/crypto.h... yes
checking whether gcrypt is enabled... 
checking for OpenSSL or libgcrypt... OpenSSL
checking openssl/cmac.h usability... yes
checking openssl/cmac.h presence... yes
checking for openssl/cmac.h... yes
checking for python... python
dyld: Library not loaded: @rpath/Python
  Referenced from: /Users/Stas/Library/Enthought/Canopy_64bit/User/bin/python
  Reason: image not found
checking for greadlink... no
checking for readlink... readlink
checking for hwloc... no
checking pcap header directories... not found
checking pcap.h usability... yes
checking pcap.h presence... yes
checking for pcap.h... yes
checking for pcap_open_live in -lpcap... yes
checking for libpcre... yes
checking for rfkill... no
checking for SQLite3 header... not found
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
checking for sqlite3_open in -lsqlite3... yes
checking for SQLite3 library version >= 3.0.0... yes
cat: /include/sqlite3.h: No such file or directory
./configure: line 23119: test: !=: unary operator expected
configure: WARNING: Cannot find SQLITE_VERSION macro in sqlite3.h header to retrieve SQLite version!
checking for zlib... no
checking for cmocka... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether to add -D_FORTIFY_SOURCE=2 to CPPFLAGS... yes
checking whether gcc is Clang... yes
checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... no
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for pthread_create in -lpthread... yes
checking for pthread_setaffinity_np... no
checking for library containing gethostbyname... none required
checking for library containing socket... none required
checking for dlopen in -ldl... yes
checking for sin in -lm... yes
checking for posix_memalign... yes
checking whether to build with code coverage support... no
checking for valgrind... no
checking for C compiler vendor... clang
checking for C compiler version... 10.0.0
checking CFLAGS for maximum warnings... -Wall
checking CXXFLAGS for maximum warnings... -Wall
checking whether C compiler accepts -O3... yes
checking whether C compiler accepts -std=gnu99... yes
checking whether C compiler accepts -fno-strict-aliasing... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wstrict-overflow=2... yes
checking whether C compiler accepts -fvisibility=hidden... yes
checking whether C compiler accepts -fstack-protector-strong... yes
checking whether C compiler accepts -Wno-array-bounds... yes
checking for C++ compiler vendor... clang
checking for C++ compiler version... 10.0.0
checking CFLAGS for maximum warnings... (cached) -Wall
checking CXXFLAGS for maximum warnings... (cached) -Wall
checking whether C++ compiler accepts -O3... yes
checking whether C++ compiler accepts -fvisibility=hidden... yes
checking whether C++ compiler accepts -fstack-protector-strong... yes
checking whether C++ compiler accepts -Wno-array-bounds... yes
checking for C compiler vendor... (cached) clang
checking for C compiler version... (cached) 10.0.0
checking whether C compiler accepts -mavx2... yes
checking whether C compiler accepts -mavx... yes
checking whether C compiler accepts -msse2... yes
checking whether C compiler accepts -mmmx... yes
checking for C++ compiler vendor... (cached) clang
checking for C++ compiler version... (cached) 10.0.0
checking whether C++ compiler accepts -masm=intel... yes
checking whether C++ compiler accepts -mavx2... yes
checking whether C++ compiler accepts -mavx... yes
checking whether C++ compiler accepts -msse2... yes
checking whether C++ compiler accepts -mmmx... yes
checking for malloc in -lduma... no
checking for C compiler vendor... (cached) clang
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating manpages/Makefile
config.status: creating scripts/Makefile
config.status: creating scripts/airdrop-ng/Makefile
config.status: creating scripts/airdrop-ng/doc/Makefile
config.status: creating scripts/airgraph-ng/Makefile
config.status: creating scripts/airgraph-ng/man/Makefile
config.status: creating scripts/versuck-ng/Makefile
config.status: creating src/Makefile
config.status: creating src/aircrack-crypto/Makefile
config.status: creating src/aircrack-util/Makefile
config.status: creating src/include/Makefile
config.status: creating src/aircrack-osdep/Makefile
config.status: creating src/aircrack-osdep/radiotap/Makefile
config.status: creating test/Makefile
config.status: creating test/test-env.sh
config.status: creating test/cryptounittest/Makefile
config.status: creating test/unit/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

aircrack-ng 1.5.2_rev-c4c67825

  Build Environment:
    Build Machine:               x86_64-apple-darwin18.2.0
    Host Machine:                x86_64-apple-darwin18.2.0
    Target Machine:              x86_64-apple-darwin18.2.0

    Install Prefix:              /usr/local

  Compiler Environment:
    C Compiler:                  gcc
    C++ Compiler:                g++
    Python:                      python

    CFLAGS:                       -I/usr/local/opt/openssl/include
    CXXFLAGS:                     -I/usr/local/opt/openssl/include
    CPPFLAGS:                     -I/usr/local/opt/openssl/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_FORTIFY_SOURCE=2
    LDFLAGS:                      -L/usr/local/opt/openssl/lib
    LIBS:                         -ldl -lm

    Optimized CFLAGS:              -Wall -Wno-unused-command-line-argument -O3 -std=gnu99 -fno-strict-aliasing -Wpointer-arith -Wstrict-overflow=2 -Wstrict-prototypes -fvisibility=hidden -fstack-protector-strong -Wno-array-bounds
    Optimized CXXFLAGS:            -Wall -Wno-unused-command-line-argument -O3 -fvisibility=hidden -fstack-protector-strong -Wno-array-bounds -masm=intel
    Optimized CPPFLAGS:           -Wno-unused-command-line-argument
    Optimized LIBS:              

  Target Environment:
    OS:                          darwin
    ASAN:                        no
    CPU L1 cache-line size:      64

  Crypto Libraries:
    Crypto Engine:               openssl
    Gcrypt:                      
    OpenSSL:                     -lcrypto

  Required Libraries:
    Ethtool:                     not required
    Libnl:                       not required

  Optional Libraries:
    Airpcap:                     no
    Cmocka:                      yes
    DUMA:                        no
    Hwloc:                       no
    Jemalloc:                    no
    Pcap:                        yes
    Pcre:                        yes
    Sqlite:                      yes
    Tcmalloc:                    no
    Zlib:                        no

  Features:
    CMAC Support:                yes
    Experimental Extra Scripts:  no
    Experimental Features:       yes

S-MacBook-Pro:aircrack-ng Stas$ make
Making all in manpages
make[1]: Nothing to be done for `all'.
Making all in scripts
make[2]: Nothing to be done for `all-am'.
Making all in src
Making all in aircrack-crypto
make[2]: Nothing to be done for `all'.
Making all in aircrack-util
make[2]: Nothing to be done for `all'.
Making all in include
make[2]: Nothing to be done for `all'.
Making all in aircrack-osdep
Making all in radiotap
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all-am'.
  CCLD     easside-ng
Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _own in easside_ng-easside-ng.o
      _decrypt_packet in easside_ng-easside-ng.o
      _redirect_sendip in easside_ng-easside-ng.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [easside-ng] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by jbenden** [comment]
Hello,

You're missing `zlib`.

-Joe

**Comment by astonly** [comment]
Hi Joe, thank you for suggestion. 
i installed zlib (brew install zlib) but it did not help (getting the same error) 
anything else i can do?

**Comment by astonly** [comment]
actually, i was able to figure it out with directories (it did not see zlib). thank you Joe

**Comment by pablobryan** [comment]
Hi what was the solution? I'm getting the same error.

**Comment by pablobryan-analytects** [comment]
> actually, i was able to figure it out with directories (it did not see zlib). thank you Joe

Hi what was the solution? I'm getting the same error.
