### ISSUE TITLE
aireplay-ng deauth error under Arch Linux

### ISSUE THREAD

**Issue by Gamer-one** [aircrack-ng/aircrack-ng#2021]
# Issue type

**REMOVE THOSE WHICH DO NOT APPLY**
- Defect - Crash
- Defect - Incorrect value displayed/received/stored
- Defect - Unexpected behavior

# System information
-Laptop: Thinkpad X1 Yoga
- OS: Arch Linux 
- CPU: i7-6600u 
- Wireless card and chipset (if relevant): "Network controller: Intel Corporation Wireless 8260 (rev 3a)"

# Aircrack-ng version

- Version: Aircrack-ng 1.5.2
- Commit Revision hash:  rev 1d658e26 - (C) 2006-2018 Thomas d'Otreppe

# Defect
## How to reproduce the issue

when trying to deauth my mobile phone hens "-c" form my router "-a" , after scaning using kismet in mon mode using:
aireplay-ng -0 0 -a xx:xx:xx:xx:xx:xx -c xx:xx:xx:xx:xx:xx wlp4s0mon

i get this error message:
after  sudo aireplay-ng -0 0 -a xx:xx:xx:xx:xx:xx -c xx:xx:xx:xx:xx:xx wlp4s0mon
======================================================================

23:36:45  Waiting for beacon frame (BSSID: xx:xx:xx:xx:xx:xx) on channel 6
Pre-condition Failed: ri != NULL
Aborted

=======================================================================

## Related issues

i think the airodump-ng has an issue some how related to this one on the same hardware running :
sudo airodump-ng wlp4s0mon

i get:
======================================================================
Pre-condition Failed: caplen >= 24
Aborted
======================================================================

**Comment by aircrack-ng** [comment]
It should be solved by #2010 which is the `dedup-function` branch. Could you give a try to that branch and report back?

**Comment by Gamer-one** [comment]
hi @aircrack-ng thanks for the suggestion, the branch seems to work flawlessly in both tools "aireplay-ng and airodump-ng", haven't noticed any issues.
