### ISSUE TITLE
Airtun-ng doesn't accept wpa2-psk cli switch as option

### ISSUE THREAD

**Issue by newkent** [aircrack-ng/aircrack-ng#2022]
Hey there,

OS: Kali 2018(newest build), wireless driver rtl8192cu, adapter tp-link(don't remember exact model).
I have an issue with airtun-ng. It doesn't accept a wpa2 password as command line argument (also, see attached screenshots).

Trying:
```
root@spartan:~# airtun-ng -a 06:25:9C:*:*:* -e y******* -p ********** wlan0mon
Encryption key already specified.
"airtun-ng --help" for help.
```

Also it's interesting that man page doesn't contain -p option, but -help does.
I tried to reboot, reload drivers, upgrade system, but nothing helps.

Also, tried to specify password in this way: 
`airtun-ng -a 06:25:9C:*:*:* -e y*******:********** wlan0mon`

Ok, when I specify bssid:password, the at0 interface is creating, but of course there is no unencrypted traffic on the interface since there is no correct password specified :( 

```
root@spartan:~# ifconfig at0
at0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::*:*:*:*  prefixlen 64  scopeid 0x20<link>
        ether 5a:48:ab:*:*:*  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 516 (516.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

<img width="1426" alt="airtune-error" src="https://user-images.githubusercontent.com/12031336/52454009-947c5680-2b52-11e9-8bda-6a1a0a8d976a.png">

<img width="1421" alt="dmesg_ifconfig_at0" src="https://user-images.githubusercontent.com/12031336/52454010-947c5680-2b52-11e9-81c2-842838daef31.png">

**Comment by aircrack-ng** [comment]
Next time, please follow the bug report format shown, it makes it easier to read them.
