### ISSUE TITLE
Can't compile aircrack-ng

### ISSUE THREAD

**Issue by lpgasparotto** [aircrack-ng/aircrack-ng#2023]
I'm using Fedora 29 but make command ask for an older libbdf version:
`  CCLD     libaircrack-util.la
ar: error while loading shared libraries: libbfd-2.20.51.0.7-6.fc14.so: cannot open shared object file: No such file or directory
make[2]: *** [Makefile:647: libaircrack-util.la] Error 127
make[2]: se sale del directorio '/home/luispa/src/aircrack-ng/src/aircrack-util'
make[1]: *** [Makefile:1954: all-recursive] Error 1
make[1]: se sale del directorio '/home/luispa/src/aircrack-ng/src'
make: *** [Makefile:583: all-recursive] Error 1
`
Thank you very much.

**Comment by jbenden** [comment]
This package is a part of binutils. Is this package installed?

**Comment by jbenden** [comment]
Please ensure these are all installed:

```
sudo yum install libtool pkgconfig sqlite-devel autoconf automake openssl-devel libpcap-devel pcre-devel rfkill libnl3-devel gcc gcc-c++ ethtool hwloc-devel libcmocka-devel git make file expect
```

Thanks,
-Joe

**Comment by aircrack-ng** [comment]
Please reopen if this is still an issue and the dependencies have been installed.
