### ISSUE TITLE
i have EAPOL HMAC how i can use it

### ISSUE THREAD

**Issue by hicham12x** [aircrack-ng/aircrack-ng#2026]
Please read the following:

  - Always test with current git master before opening a feature request
  - Use the search function to see if the feature you're about to request isn't a duplicate. If an existing issue is open and you have new information, update it
  - One feature/topic request per ticket
  - Don't worry about any of the items on the right panel (Assignee, Labels or Milestone), we will take care of them

**REMOVE ALL OF THE ABOVE TEXT**

# Description

Describe the feature/topic. Even though the following is more geared toward bug reporting, it is an excellent read to provide useful details: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

If output/file content is relevant, add an example enclosed in backticks.

GitHub markdown guide: https://guides.github.com/features/mastering-markdown/

**Comment by aircrack-ng** [comment]
Please use the forum for support. Make sure to read the documentation before posting.
