### ISSUE TITLE
PMKID length check incorrect ?

### ISSUE THREAD

**Issue by vom513** [aircrack-ng/aircrack-ng#2029]
# Issue type

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: Kali linux 2019.1
- CPU: Intel 64-bit (C2D U9400) 
- Wireless card and chipset (if relevant): N/A

# Aircrack-ng version

- Version: 1.5.3
- Commit Revision hash: eccf8cc5

# Defect
## How to reproduce the issue

FYI: all my byte counts are WITHOUT newlines.  So as I mention I'm using "echo -n" to ensure I'm not picking up newlines.

Running aircrack-ng with a PMKID with a 4-character ESSID gives the error "Input is too short !".  This PMKID works just fine in hashcat itself.  The short nature of the ESSID seems to be what is triggering this based on the format laid out in:

https://hashcat.net/forum/thread-7717.html

Non-working PMKID string: 67 bytes
Working PMKID string: 79 bytes

Not quite sure what the magic cutoff is in terms of length.  And on that note, according to the discussion here:

https://stackoverflow.com/questions/4919889/is-there-a-standard-that-defines-what-is-a-valid-ssid-and-password 

An SSID has no minimum length.  0 indicates a probe.  So for a non-probe, I would assume the minimum is 1-byte.  So then the minimum length for the PMKID check would be 61 bytes ?  (I'm testing this with echo -n and wc -c).  The only variable length that I see in the PMKID format is the ESSID.  So then the range would be 61 - 123 bytes (ascii)?

Also I suppose we have to be really clear as the string itself is ascii, but it represents the raw data (i.e. hex values for ASCII characters for the ESSID).  Hopefully that makes sense and I'm not needlessly confusing things.

If you want some of the PMKIDs let me know and also how to get them privately to you.

## Related issues

N/A

**Comment by jbenden** [comment]
Thank you for the excellent bug report!

I've reduced the count to everything required and at least 1 character for ESSID.

Please let me know if the problem still persists.

Thanks,
-Joe
