### ISSUE TITLE
AirDrop-ng does not start - PyLorcon2 is not defined

### ISSUE THREAD

**Issue by torerobo** [aircrack-ng/aircrack-ng#2033]
I have not encountered any errors.
Did everything according to the instructions https://github.com/aircrack-ng/aircrack-ng/tree/master/scripts/airdrop-ng

AirDrop-ng does not start
```
python airdrop-ng -i wlan1mon -t airodump.csv -r rulefile.txt
```

I get the error 

```
################################################# #
# Welcome to AirDrop-ng #
#################################################

Traceback (most recent call last):
   File "aircrack-ng / scripts / airdrop-ng / airdrop-ng", **line 1006,** in <module>
     except PyLorcon2.Lorcon2Exception, e:
NameError: name 'PyLorcon2' is not defined
```

OS Parrot 4.18

**edit**: Fixed formatting

**Comment by aircrack-ng** [comment]
Please follow bug filing guidelines

**Comment by aircrack-ng** [comment]
You need to install the dependencies as explained in the [README](https://github.com/aircrack-ng/aircrack-ng/blob/master/scripts/airdrop-ng/README).

**Comment by torerobo** [comment]
You hurry to close the problem. I have installed and checked all dependencies. And even wrote about it. Check readme yourself on your PC

**Comment by aircrack-ng** [comment]
The bug can be reproduced when the dependencies aren't installed and it goes away after it is.

**Comment by torerobo** [comment]
Please check the readme, I think you need to change the source of the dependencies. All dependencies were successfully installed, but an error occurred.

**Comment by torerobo** [comment]
https://github.com/aircrack-ng/aircrack-ng/blob/master/scripts/airdrop-ng/README

**Invalid documentation**

**Comment by aircrack-ng** [comment]
Open a PR with the documentation update. It works just fine on Kali.
