### ISSUE TITLE
Question: is it possible to pause airolib-ng in batch mode.

### ISSUE THREAD

**Issue by frankenstein91** [aircrack-ng/aircrack-ng#2036]
I am currently creating a database with Airolib-ng. the process is very long and I would like to interrupt it to let it continue working later. is this possible, or would the process start from the beginning and ignore the previous work?

thank you

**Comment by aircrack-ng** [comment]
Support is done through the forum. This is a bug tracker.

Here is the answer to your question: Yes, you can pause it.

**Comment by frankenstein91** [comment]
Then we make a function extension request from the topic. Can you please include the "Yes" in the documentation?

**Comment by aircrack-ng** [comment]
Where exactly?

**Comment by frankenstein91** [comment]
There are two possible ideas for me, one in the man pages or in the help option with --help. I can't find continuing in either one.

**Comment by aircrack-ng** [comment]
9e97c73

**Comment by frankenstein91** [comment]
Thank you for making this tool easier to use. I think you could use Ctrl + C for pausing?
