### ISSUE TITLE
including the '--new-session' flag cause aircrack to quit, saying "No networks found, exiting" when using  capture file known to work

### ISSUE THREAD

**Issue by SaltyCybernaut** [aircrack-ng/aircrack-ng#2038]
# Issue type

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information
## Test 1
- OS: Parrot 4.6
- CPU: Intel Atom x7-Z8750
## Test 2
- OS: Ubuntu 18.04.2
- CPU: Intel Core i7-6500U

# Aircrack-ng version
## Test 1
- Version: 1.5.2 (from the OS repo)
- Commit Revision hash: unknown
## Test 2
- Version: 1.5.2 rev c8308eba (compiled from git master branch)
- Commit Revision hash: c8308eba

# Defect
## How to reproduce the issue

1. acquire/generate capture file with WPA handshake
2. run: `aircrack-ng -w work-list.txt example.cap` to confirm aircrack does not have a problem with the capture file
3. run: `aircrack-ng --new-session current.session -w work-list.txt example.cap` or `aircrack-ng -N current.session -w work-list.txt example.cap` and observe aircrack fail to parse a valid capture file

# Output
## Test 1
    "aircrack-ng --help" for help.

    Quitting aircrack-ng...
    Opening temp-01.capease wait...   <- yes, that is a separate bug in the output.
    Unsupported file format (not a pcap or IVs file).
    Read 0 packets.

    No networks found, exiting.

    Quitting aircrack-ng...

## Test 2

`aircrack-ng -w test/password.lst test/wpa2.eapol.cap -N something`

    "/home/<USER>/scratch-pad/aircrack-ng/.libs/aircrack-ng --help" for help.

    Quitting aircrack-ng...

**Comment by aircrack-ng** [comment]
Can't reproduce test 1 with git master. Reopen with the command if it still happens

**Comment by inakiuy** [comment]
Same here.
Aircrack-ng version 1.5.2, Kali linux on a Raspberry pi 3

If I run the command whitout -N runs fine but if I try to create a new session, aircrack fails to start with the mesage:
````
root@kali:~# aircrack-ng -a 2 --bssid XX:YY:ZZ:AA:BB:CC -N session_test -w ./rockyou_cleaned.txt handshake-test-XX:YY:ZZ:AA:BB:CC.cap
"aircrack-ng --help" for help.

Quitting aircrack-ng...
Opening handshake-test-XX:YY:ZZ:AA:BB:CC.cap
Unsupported file format (not a pcap or IVs file).
Read 0 packets.

0 potential targets

No matching network found - check your bssid.

Quitting aircrack-ng...
````

**Comment by oussema146** [comment]
i had the same problem 
   

aircrack-ng /home/kali/Desktop/hack1-01.cap -w /home/kali/Desktop/rockyou.txt
Reading packets, please wait...
Opening /home/kali/Desktop/hack1-01.cap
Read 5679 packets.

No networks found, exiting.


Quitting aircrack-ng...
