### ISSUE TITLE
SUPPORT

### ISSUE THREAD

**Issue by mclaudiopt** [aircrack-ng/aircrack-ng#2047]
HELLO
i am a camera that i dont know password..anyway this tool can discover it?
thanks

Please read the following:

  - Always test with current git master before opening a feature request
  - Use the search function to see if the feature you're about to request isn't a duplicate. If an existing issue is open and you have new information, update it
  - One feature/topic request per ticket
  - Don't worry about any of the items on the right panel (Assignee, Labels or Milestone), we will take care of them

**REMOVE ALL OF THE ABOVE TEXT**

# Description

Describe the feature/topic. Even though the following is more geared toward bug reporting, it is an excellent read to provide useful details: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

If output/file content is relevant, add an example enclosed in backticks.

GitHub markdown guide: https://guides.github.com/features/mastering-markdown/

**Comment by Booooozo** [comment]
lol
