### ISSUE TITLE
Fixed MS-CHAPv2 Challenge

### ISSUE THREAD

**Issue by danidemis** [aircrack-ng/aircrack-ng#2049]
Hi, I would like you to consider adding a function, the ability to set a fixed challange (ex: 11:22:33:44:55:66:77:88) for MS-CHAPv2 authentication in hostapd-wpe. You could easily go back to the password through rainbow tables or a free service like the one offered by https://crack.sh/ . 

Thanks

**Comment by tuian** [comment]
Any update for this?

@jbenden @danidemis @aircrack-ng

**Comment by Neutrino3316** [comment]
I find a comment by @Rogdham which is related.

https://github.com/OpenSecurityResearch/hostapd-wpe/issues/30#issuecomment-731602868


> The MsCHAPv2 specification is different from NetNTLMv1, although similar.
> 
> The main difference is that the challenge is computed as follows:
> 
> ```python
> ChallengeHash = SHA1(PeerChallenge + AuthenticatorChallenge + Username)[:7]
> ```
> 
> where `AuthenticatorChallenge` is chosen by the server, but `PeerChallenge` is chosen by the client (and `Username` as well of course).
> 
> So it is unfortunately not possible to set the `ChallengeHash` to `11:22:33:44:55:66:77:88`.
