### ISSUE TITLE
aircrack-ng crushed error:brcmf_proto_bcdc_msg failed w/status -110

### ISSUE THREAD

**Issue by shadowlesswalker** [aircrack-ng/aircrack-ng#2057]
I am studying the aircrack-ng tool on kali linux for raspberry. When i used aireplay-ng command to do a WiFi DeAuth attack practice, some errors just happend and the whole brcmfmac driver just crushed. Then i cant't used any command with any Aircrack-ng tool normally util i reboot the OS.
The error messages printed as  bellow:
![0](https://user-images.githubusercontent.com/22036602/58805604-fa7f7300-8646-11e9-9170-57d3c9be58cb.jpg)
Is this a bug ? Can anyone help me solve this problem?

**Comment by ZeroChaos-** [comment]
oh it's a bug alright, probably in the nexmon firmware you are using.  it's not what one might call "stable".  at any rate it's not an aircrack-ng bug
