### ISSUE TITLE
Issue | Wrong Channel

### ISSUE THREAD

**Issue by jihubjjhbj** [aircrack-ng/aircrack-ng#2063]
Aye, I get this error:
`<removed-for-privacy>  wlan1mon is on channel 2, but the AP uses channel 11`

When executing:

`# aireplay-ng --deauth 999 -a <removed-for-privacy> wlan1mon`

I'm experimenting on my home system using an N150 ThinkPenguin USB Adaptor.

**OS**: Parrot OS Live USB

**Comment by aircrack-ng** [comment]
Set channel to 11, try again.
