### ISSUE TITLE
Error | Channel is Wrong

### ISSUE THREAD

**Issue by FrakTheMob22** [aircrack-ng/aircrack-ng#2064]
**Issue**:

I get this error:

`<removed-for-privacy>  wlan1mon is on channel 2, but the AP uses channel 11`

When executing:

`#aireplay-ng --deauth 999 -a <removed-for-privacy> wlan1mon`

I'm using this on my home system with an N150 USB Adaptor from ThinkPenguin.

**OS**: ParrotOS Live USB

**Comment by aircrack-ng** [comment]
You need to change the channel to 11
