### ISSUE TITLE
Using Kali to communicate with airserv-ng in OPENWRT

### ISSUE THREAD

**Issue by TeusDev** [aircrack-ng/aircrack-ng#2065]
# Issue don't work as intended to be 

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: Kali Linux Latest - SAMSUNG LAPTOP (np300e4c ad5BR)
- CPU: i5 3210M
- Wireless card and chipset (if relevant): Archer C60 OPENWRT

# Aircrack-ng version

- Version: 
OpenWRT Archer C60 - Aircrack-ng 1.2 rc1
Laptop Kali - Aircrack-ng 1.5.2
- Commit Revision hash: ? //i don't know what is that - i'm newbie

# Defect
## How to reproduce the issue

[OPENWRT]
"wlan1     ESSID: unknown
          Access Point: ####################
          Mode: Monitor  Channel: 1 (2.412 GHz)
          Tx-Power: 20 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: unknown
          Encryption: unknown
          Type: nl80211  HW Mode(s): 802.11bgn
          Hardware: unknown [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes  PHY name: phy1

root@OpenWrt:~# airserv-ng -d wlan1
Opening card wlan1
Setting chan 1
Opening sock port 666
Serving wlan1 chan 1 on port 666" //OK, its working!

[KALI LAPTOP]
"root@kali:~# airodump-ng 192.168.1.10:666
Connecting to 192.168.1.10 port 666...
Connection successful
Connecting to 192.168.1.10 port 666...
Connection successful
airodump-ng: osdep.c:46: wi_set_ht_channel: Assertion `wi->wi_set_ht_channel' failed.

 CH  0 ][ Elapsed: 0 s ][ 2019-07-19 00:49                                     
                                                                               
 BSSID              PWR  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID
                                                                               
 A  -83        2        0    0   1  130  WPA2 CCMP   PSK  A
 B  -80        2        0    0   1  130  WPA2 CCMP   PSK  B
 C  -91        2        0    0   1  130  WPA2 CCMP   PSK  C
 D  -37        4        0    0   1  270  WPA2 CCMP   PSK  D
 E  -56        4        0    0   1  195  WPA2 CCMP   PSK  E
                                                                               
 BSSID              STATION            PWR   Rate    Lost    Frames  Probe     
                                                                               
Connecting to 192.168.1.10 port 666...
Failed to connect
Can't reopen 192.168.1.10:666"

// looking again in openwrt ssh terminal

[OPENWRT]
"Connect from 192.168.1.171
Connect from 192.168.1.171
Death from 192.168.1.171
Assertion failed: plen <= *len && plen > 0 (network.c: net_get: 134)
Aborted"

**Comment by aircrack-ng** [comment]
Duplicate of #1926

**Comment by TeusDev** [comment]
> Duplicate of #1926

@aircrack-ng this is probablly due to version mismatch between the openwrt router (1.2) and kali (1.5.2), is there somehow i can install 1.2 version on kali or 1.5.2 version on openwrt?
-using openwrt opkg only install 1.2 version atm
