### ISSUE TITLE
Airport -z | -s not showing the network interface details in MAC OS X

### ISSUE THREAD

**Issue by imharish-sivakumar** [aircrack-ng/aircrack-ng#2069]
I was downloaded the aircrack-ng using brew and all the dependencies I have downloaded but in the mac, people are using this airport for knowing the network interface ssid and other details but it is not showing for me

for me it is showing the netwerk coverage detail like : 
AirPort: On, Connected: connected_network_name (110%)

**Comment by aircrack-ng** [comment]
macOs isn't supported yet

**Comment by Oppen** [comment]
What's missing? Maybe I can give a hand.
