### ISSUE TITLE
aircrack-ng -p 1 does not work correctly

### ISSUE THREAD

**Issue by icebluey** [aircrack-ng/aircrack-ng#2071]
# Issue type

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: Ubuntu 16.04
- CPU: Intel Core i5
- Wireless card and chipset (if relevant): N/A

# Aircrack-ng version

- Version: 1.5.2
- Commit Revision hash: c2e20a4a

# Defect
## How to reproduce the issue

Aircrack-ng uses 2 CPUs when one is requested when running `aircrack-ng -p 1 -w password.txt 1.cap`

```
\# top
  PID   USER      PR  NI    VIRT    RES    SHR          S  %CPU %MEM     TIME+ COMMAND                                                       
31882 root        20   0  179924   7868   4420 S  200.3      0.2       0:24.69 aircrack-ng 
```

**Comment by aircrack-ng** [comment]
Edit: next time, please fill in as explained.

**Comment by jbenden** [comment]
This is not a bug.

The program uses multiple threads for various tasks. The `-p` option only controls the number of threads used for brute-forcing the passphrase.

Best regards,
-Joe
