### ISSUE TITLE
[airdecap-ng] WDS traffic is partially decrypted

### ISSUE THREAD

**Issue by jacobopantoja** [aircrack-ng/aircrack-ng#2072]
# Issue type
- Defect - Unexpected behavior (obvious or confirmed in the forum)
# Aircrack-ng version

- Version: 1.5.2 rev
- Commit Revision hash: c2e20a4a

When decrypting WDS traffic, only packets destined to the AP are decrypted (packets sent by the AP are not).
This is because BSSID is not univocally neither to Receiver Address (RA) nor Transmitter Address (TA), but depends upon the direction of the traffic. Same applies to station address.

In my opinion, it is mandatory to specify BSSID in the command line to be able to properly identify STA and BSSID from the packet.

**Comment by jacobopantoja** [comment]
Pull request #2073 proposed to solve the issue

**Comment by aircrack-ng** [comment]
See 81d2a0c, c4c1605, 81f3b8e, and db0c282
