### ISSUE TITLE
'make integration' fails on Arch Linux x64

### ISSUE THREAD

**Issue by viliuspovilaika** [aircrack-ng/aircrack-ng#2074]
# 'make integration' failure

**Failure points:**
- Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- FAIL: `test/test-aireplay-ng-0001.sh`
- FAIL: `test/test-aireplay-ng-0002.sh`
- FAIL: `test/test-aireplay-ng-0003.sh`
- FAIL: `test/test-aireplay-ng-0004.sh`
- FAIL: `test/test-aireplay-ng-0005.sh`
- FAIL: `test/test-aireplay-ng-0006.sh`
- FAIL: `test/test-aireplay-ng-0007.sh`
- PASS: test/test-airbase-ng-0001.sh
- FAIL: `test/test-airbase-ng-0002.sh`
- SKIP: test/test-airbase-ng-0003.sh
- PASS: test/test-airodump-ng-0001.sh
- FAIL: `test/test-airodump-ng-0002.sh`
- FAIL: `test/test-aireplay-ng-0003.sh`
- FAIL: `test/test-aireplay-ng-0004.sh`
- FAIL: `test/test-aireplay-ng-0005.sh`

# Other information
- OS: Linux 5.2.9-arch1-1-ARCH x86_64 GNU/Linux
- Version: latest
config.log: https://pastebin.com/XuVDzbTJ
integration-test-suite.log: https://pastebin.com/fng3mp2z

# Defect
## How to reproduce the issue

Default installation procedure with the Operating System specified above.

**Comment by ZerBea** [comment]
Can't reproduce that issue:
$ uname -r
5.2.9-arch1-1-ARCH

$ autoreconf -i
$ ./configure --with-experimental
$ make check
...
PASS: test/test-hex_string_to_array.sh
PASS: test/test-aircrack-ng-0001.sh
PASS: test/test-aircrack-ng-0002.sh
PASS: test/test-aircrack-ng-0003.sh
PASS: test/test-aircrack-ng-0004.sh
PASS: test/test-aircrack-ng-0005.sh
PASS: test/test-aircrack-ng-0006.sh
PASS: test/test-aircrack-ng-0007.sh
PASS: test/test-aircrack-ng-0008.sh
PASS: test/test-aircrack-ng-0009.sh
PASS: test/test-aircrack-ng-0010.sh
PASS: test/test-aircrack-ng-0011.sh
PASS: test/test-aircrack-ng-0012.sh
PASS: test/test-aircrack-ng-0013.sh
PASS: test/test-aircrack-ng-0014.sh
PASS: test/test-aircrack-ng-0015.sh
PASS: test/test-aircrack-ng-0016.sh
PASS: test/test-aircrack-ng-0017.sh
PASS: test/test-aircrack-ng-0018.sh
PASS: test/test-aircrack-ng-0019.sh
PASS: test/test-aircrack-ng-0021.sh
PASS: test/test-airdecap-ng-0001.sh
PASS: test/test-airdecap-ng-0002.sh
PASS: test/test-airdecap-ng-0003.sh
PASS: test/test-airdecap-ng-0004.sh
PASS: test/test-wpaclean-0001.sh
PASS: test/test-wpaclean-0002.sh
PASS: test/test-alltools.sh
PASS: test/test-airolib-ng-0001.sh
PASS: test-encrypt-wep
PASS: test-calc-pmk
PASS: test-calc-mic
PASS: test-calc-ptk
PASS: test-encrypt-ccmp
PASS: test-decrypt-ccmp

Testsuite summary for aircrack-ng 1.5.2_rev-c2e20a4a
 TOTAL: 35
 PASS:  35
 SKIP:  0
 XFAIL: 0
 FAIL:  0
 XPASS: 0
 ERROR: 0

Did you try a fresh git clone?

**Comment by aircrack-ng** [comment]
As shown in the logs, it mentions that process could interfere. Kill them using `airmon-ng check kill`, then run it again., it will work. If any test doesn't pass after that, feel free to reopen the ticket and update it.

Please enclose the output between code tags, the three ticks (or "Insert code" icon.
