### ISSUE TITLE
aireplay-ng -3 cannot parse ARP requests (but visible on tcpdump)

### ISSUE THREAD

**Issue by uf0o** [aircrack-ng/aircrack-ng#2081]
# Issue type

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux (running on VMWare Fusion)
- CPU: intel i7 
- Wireless card and chipset (if relevant): 
alpha AWUS036H / rtl8187

# Aircrack-ng version
 Aireplay-ng 1.5.2

- Version:
- Commit Revision hash:

# Defect
## How to reproduce the issue
Hello,

I am not able to retrieve any ARP request via this command

root@kali:~/Desktop# aireplay-ng -3 -b 5a:ef:68:0d:15:5c -h B0:70:2D:51:D8:97      wlan0mon
20:51:01  Waiting for beacon frame (BSSID: 5A:EF:68:0D:15:5C) on channel 11
Saving ARP requests in replay_arp-0907-205101.cap
You should also start airodump-ng to capture replies.
 373 packets (got 0 ARP requests and 0 ACKs), sent 0 packets...(0 pps)

Yes, I have done all the necessary tshooting several times, and I am even able to see the ARP traffic coming from other stations via tcpdump.
I have also tried:

- deauth the client
- change the source macaddress with my card/victim
- flushed the arp cache from the victim

Indeed I got the ARPs...

root@kali:~# tcpdump -i wlan0mon arp  -en
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on wlan0mon, link-type IEEE802_11_RADIO (802.11 plus radiotap header), capture size 262144 bytes
00:26:25.381902 205928295us tsft 1.0 Mb/s 2462 MHz 11b -9dBm signal antenna 1 DA:ff:ff:ff:ff:ff:ff BSSID:5a:ef:68:0d:15:5c SA:b0:70:2d:51:d8:97 LLC, dsap SNAP (0xaa) Individual, ssap SNAP (0xaa) Command, ctrl 0x03: oui Ethernet (0x000000), ethertype ARP (0x0806), length 28: Request who-has 192.168.1.131 tell 192.168.1.131, length 28

root@kali:~/Desktop# aireplay-ng | grep Thomas
  Aireplay-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
root@kali:~/Desktop# uname -a
Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

So I suspect a bug since I have tried everything is possible...and I doubt is a driver issue as I am receiving the packets to the OS (tcpdump)

**Comment by aircrack-ng** [comment]
Let's confirm in the [forum](https://forum.aircrack-ng.org/index.php/topic,3107.0.html) first. Once confirmed, reopen the bug, and make sure to edit the main one to format it (code tags mostly).
