### ISSUE TITLE
WPA Handshake crack stucks at 96.50%

### ISSUE THREAD

**Issue by LordEliasTM** [aircrack-ng/aircrack-ng#2082]
I used a 700MB wordlist to crack a WPA Handshake and it stuck at 96.50%

**Comment by aircrack-ng** [comment]
Please follow the guidelines next time, it makes it easier to read reports that way.

Any specific wordlist? Or did you make it yourself?

What version of aircrack-ng? What command did you run? What OS?

**Comment by aircrack-ng** [comment]
Could you try current git master and report back? A similar issue has been fixed
