### ISSUE TITLE
address device 

### ISSUE THREAD

**Issue by Shkiper174** [aircrack-ng/aircrack-ng#2083]
Hi there! 
Are there any options to get the real mac-address of a device that is not connected to any network and scans in the background?

**Comment by aircrack-ng** [comment]
Yes, 802.11 packet capture tools. One of them is Airodump-ng, look at the `(not associated)` devices in the client section at the bottom

**Comment by aircrack-ng** [comment]
This is a bug tracker, please keep any other support questions in the [forum](https://forum.aircrack-ng.org/), and make sure to consult the [documentation](https://aircrack-ng.org/doku.php) first.

To save you time, the answer is in Airodump-ng, on the bottom section, with the clients, the ones marked **(not associated)**
