### ISSUE TITLE
Incorrect value displayed in CPU information with Core i5 4288U

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#2084]
# Issue type

- Defect - Incorrect value displayed/received/stored
- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: macOS Mojave (10.14.6)
- CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz

# Aircrack-ng version

- Version: 1.5.2?
- Commit Revision hash: f300f73

# Defect

The output of `aircrack-ng -u` is the following:

```
$ ./aircrack-ng -u
Vendor          = Intel
Model           = Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
Features        = MMX,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AES-NI,AVX,AVX2
Hyper-Threading = No
CPU cores       = 4
SIMD size       = 8 (256 bit)
SIMD size in use= 4 (128 bit)
```

It should be:

```
$ ./aircrack-ng -u
Vendor          = Intel
Model           = Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
Features        = MMX,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AES-NI,AVX,AVX2
Hyper-Threading = Yes
Logical cores   = 4
CPU cores       = 2
SIMD size       = 8 (256 bit)
SIMD size in use= 4 (128 bit)
```

This CPU has 2 cores and 4 threads, as seen on [ARK](https://ark.intel.com/content/www/us/en/ark/products/75991/intel-core-i5-4288u-processor-3m-cache-up-to-3-10-ghz.html).

## How to reproduce the issue

Run `aircrack-ng -u` in a terminal on macOS mojave.

## Related issues

[Forum post](https://forum.aircrack-ng.org/index.php/topic,3178)

## Notes

[...] it looks like it's using `__cpuid_count` (a compiler intrinsic) to get the core count.  The following snippet using hwloc produces the correct physical core count:

`nthreads = hwloc_get_nbobjs_by_type(top, HWLOC_OBJ_CORE)`

**Comment by grr** [comment]
> Version: 1.5.2?
> Commit Revision hash: Unknown

it was actually tested against latest git master (f300f73)

and the missing behavior description doesn't mention the resulting effect:
> When using aircrack-ng, it is using 4 cpus even though my CPU only has 2 physical cores. It does have 4 logical cores because of hyperthreading. Using more threads than the number of CPUs results in thread contention that actually hurts performance

**Comment by jbenden** [comment]
Please try the following patch against current `master` branch.

I've tested against a few Intel and AMD machines, this patch seems to report the correct results.

Thanks,
-Joe

[cpus.diff.txt](https://github.com/aircrack-ng/aircrack-ng/files/3644383/cpus.diff.txt)

**Comment by grr** [comment]
Looks like it works, though the size of the the "SIMD size in use" has now changed from 4 to 8. Don't know if that's important.

```$ /tmp/urk/bin/aircrack-ng -u
Vendor          = Intel
Model           = Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
Features        = MMX,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AES-NI,AVX,AVX2
Hyper-Threading = Yes
Logical CPUs    = 4
Threads per core= 2
CPU cores       = 2
SIMD size       = 8 (256 bit)
SIMD size in use= 8 (256 bit)
```

**Comment by jbenden** [comment]
Thank you for testing the patch file.

I have committed all changes to the `master` branch. If this problem continues to persist, please let us know; otherwise, thank you for your excellent bug report.

Best regards,
-Joe
