### ISSUE TITLE
Airmon-ng can't enable monitor mode on wifi card anymore

### ISSUE THREAD

**Issue by Skroppo** [aircrack-ng/aircrack-ng#2086]
I have a Samsung-Q330 using a Broadcom Inc. and subsidiaries BCM4313 802.11bgn Wireless Network Adapter. I have never had a problem before until now. All of a sudden it refuses to enable monitor mode on the WiFi card.

I have updated everything and reinstalled the OS to which it still won't work,

Here's the output when I run airmon-ng:

https://pastebin.com/LDm6uyp3

I even tried using the "check kill" command but it still didn't do anything:

https://pastebin.com/8idCAmvv

OS Info:

Distributor ID: Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic

**Comment by ZeroChaos-** [comment]
It says monitor mode enabled for prism0, what is the problem? Also, please don't use pastebins for bug reporting.

**Comment by Skroppo** [comment]
> It says monitor mode enabled for prism0, what is the problem? Also, please don't use pastebins for bug reporting.

I don't know what prism0 is and I'm using the command "airmon-ng start wlp2s0" not "prism0". Sorry about the pastebins, I didn't want to make the report too long.

**Comment by aircrack-ng** [comment]
Even though it will add 'mon' at the end of the interface in most cases, this rule has exceptions and this is one of them. In case something went wrong, airmon-ng would say so as well. It show how important it is to read ALL output messages.

Don't worry about making bug report too long. The issue with using external resources is that later on, they will become unavailable, information will be lost and bug report will become useless and impossible to understand. If we ever think they are, they will be edited.

prism0 'should' work. Bear in mind wl is closed source.
