### ISSUE TITLE
Error while installing on Ubuntu

### ISSUE THREAD

**Issue by termelon** [aircrack-ng/aircrack-ng#2091]
using Ubuntu 19.04, 
I tried to install the git version as the older version is having trouble with large password files. 

here are the options I used , 
`autoreconf -i`
`./configure`
`make`

I'm receiving the following error,
```
ar: `u' modifier ignored since `D' is the default (see `U')

/usr/bin/ld: cannot find -lnl-genl-3

collect2: error: ld returned 1 exit status

make[2]: *** [Makefile:2984: libaircrack-osdep.la] Error 1

make[1]: *** [Makefile:4798: all-recursive] Error 1

make: *** [Makefile:2573: all] Error  2
```

The full logs of each commands are attached with this,
I did some search in stackoverflow and some Kali forums,  they are advising to use the `./configure`
option with `--enable-shared` flag, but even after that there is no change. Please help me to sort this out.

**Comment by termelon** [comment]
[autoreconf.txt](https://github.com/aircrack-ng/aircrack-ng/files/3800974/autoreconf.txt)
[make.txt](https://github.com/aircrack-ng/aircrack-ng/files/3800975/make.txt)
[configure.txt](https://github.com/aircrack-ng/aircrack-ng/files/3800976/configure.txt)
[config.log](https://github.com/aircrack-ng/aircrack-ng/files/3800977/config.log)

**Comment by aircrack-ng** [comment]
Have you installed all the dependencies as mentioned in README.md? Looks like libnl-genl-3-dev is missing. 1.6 or current compiles fine using the latest Kali.
