### ISSUE TITLE
Analog wifi authentication

### ISSUE THREAD

**Issue by mingzhizhiren** [aircrack-ng/aircrack-ng#2093]
Now I have a set of whitelisted MAC addresses for the target AP and I know the AP password, but the MAC in the whitelist may be used by people. Can I use the aircrack-ng to simulate the AP's authentication process in batches using my set of MACs? (AP encryption method is WPA/WPA2-PSK)
Because I saw on the documentation that I can only simulate the WEP login process.

**Comment by aircrack-ng** [comment]
The question isn't really clear, you may want to rephrase it. However, do this on the forum, as this is a question and not a bug report. Please don't ignore the bug reporting guidelines.
