### ISSUE TITLE
consider tagging a new release

### ISSUE THREAD

**Issue by anthraxx** [aircrack-ng/aircrack-ng#2097]
Seems a year passed without a new release but tons of improvements have been done. What do you folks think, could we get a new release? :smile:

**Comment by aircrack-ng** [comment]
unless there is any blocker, release should happen very soon.

**Comment by qhaas** [comment]
It has been about 1.5 years since [1.6](https://github.com/aircrack-ng/aircrack-ng/releases/tag/1.6) was released in 1/2020, hopefully we get a newer tagged release soon.
