### ISSUE TITLE
New clients appended after coloring don't get auto-colored

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#2109]
# Issue type

- Defect - Incorrect value displayed/received/stored
- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: Linux

# Aircrack-ng version

- Version: 1.5.2
- Commit Revision hash: 1f07048

# Defect
## How to reproduce the issue

When starting airodump-ng, hit the 'o' key. It will automatically color clients linked to AP shown in the top section. However, newly added APs don't get colors. If there are unassociated clients, they will also get the same color as the other client (see PR #2088).

**Comment by 29G** [comment]
­
