### ISSUE TITLE
new idea to autosave in txt file when cracked wpa file 

### ISSUE THREAD

**Issue by mario198532** [aircrack-ng/aircrack-ng#2116]
Hi all i have new idea to create in autosave when is cracked wpa file to txt file .
Example
Network: Name1
Password: example
Mac Address: FF:FF:FF:FF:FF:FF

Thanks

**Comment by aircrack-ng** [comment]
It already exists: `-l <file>: Write the key into a file. Overwrites the file if it already exists.`

**Comment by mario198532** [comment]
Not exist in gui version thanks
