### ISSUE TITLE
Aircrack-ng keeps going through wordlist even after finding the right password.

### ISSUE THREAD

**Issue by Booooozo** [aircrack-ng/aircrack-ng#2117]
Hi,

I am running the latest version of aircrack-ng. When I try to crack my own wifi password with aircrack-ng it goes through the wordlist and finds the right password and displays it momentarily but then continues to go through wordlist. I have attatched a video link below:
https://drive.google.com/file/d/187566ux700AbK-t-U0wJSvdx9pw7BeBC/view?usp=sharing

I even tried using a different handshake file from my friend's wifi with his permission and even then I have the same issue, I tried using a raspberry pi with kali linux but even then I have the same issue.

The password is only shown after going through the entire wordlist, even Windows running the latest version has the same issue:
https://drive.google.com/open?id=1LW4YnJjrTZ166AxSap9RvQpxJ-TVeoHa

**Comment by Booooozo** [comment]
The password is only shown after going through the entire wordlist, even Windows has the same issue:
https://drive.google.com/open?id=1LW4YnJjrTZ166AxSap9RvQpxJ-TVeoHa

**Comment by aircrack-ng** [comment]
Try with 1.6, and report back.

Please also follow the bug reporting format that was suggested.

**Comment by Booooozo** [comment]
> Try with 1.6, and report back.
> 
> Please also follow the bug reporting format that was suggested.

Yeah I will follow it next time while posting a bug report, but even while running the latest compiled version on Kali linux 2019.4 the same issue persists, this issue also persists when running huge wordlists:
https://drive.google.com/file/d/1Vv0qej1RCnjmkASLDUYQkGHyjIBKOJRB/view?usp=sharing

**Comment by aircrack-ng** [comment]
1.6 hasn't made it in Kali yet, it's still 1.5.2.

Just FYI, latest version of Kali is 2020.1

**Comment by Booooozo** [comment]
Oh, I didn't know. Because when using ubuntu live USB yesterday it worked with no problem. Anyway thanks for the help
