### ISSUE TITLE
[1.6] [Fails to build] blk_SHA1_Final: Assertion `((uintptr_t) hashout % 4UL) == 0' failed

### ISSUE THREAD

**Issue by samueloph** [aircrack-ng/aircrack-ng#2118]
Hello, this is a bug report coming from Debian,

After I uploaded 1.6 to unstable, our builders farm detected some issues[0], the main one being the one described in the title:
```
blk_SHA1_Final: Assertion `((uintptr_t) hashout % 4UL) == 0' failed
```
There was 11 test failures for i386[1]
And 23 for s390x[2]

These are the most critical ones from the Debian POV as they're officially supported archs, though you can see build logs for the other failed archs from [0] as well, if interested.

Thanks

[0]https://buildd.debian.org/status/package.php?p=aircrack-ng
[1]https://buildd.debian.org/status/fetch.php?pkg=aircrack-ng&arch=i386&ver=1%3A1.6-1&stamp=1581034439&raw=0
[2]https://buildd.debian.org/status/fetch.php?pkg=aircrack-ng&arch=s390x&ver=1%3A1.6-1&stamp=1581034389&raw=0

**Comment by jbenden** [comment]
I believe it's safe to remove the assert; as this part of code is not SIMD. Could you add the removal of the line as a patch, to see if it all builds? This should at least fix i386, and may fix s390.

**Comment by samueloph** [comment]
@jbenden alright, just did an upload to Debian Experimental with the following patch:
https://salsa.debian.org/pkg-security-team/aircrack-ng/commit/cb72edde68a2967734532d8c62c749a9680f52ea

Build information will be available here in one hour (roughly):
https://buildd.debian.org/status/package.php?p=aircrack-ng&suite=experimental

Thanks!

**Comment by samueloph** [comment]
@jbenden two of those tests got different errors on s390x now[3]:
```
FAIL: test/test-airdecap-ng-0005.sh
===================================

Unexpected decrypted file: /tmp/tmp.qEgR9Kl43V
FAIL test/test-airdecap-ng-0005.sh (exit status: 1)

FAIL: test/test-airdecap-ng-0006.sh
===================================

Failed decrypting
FAIL test/test-airdecap-ng-0006.sh (exit status: 1)
```

FWIW these two failures seems to also be affecting powerpc, ppc64 and sparc64.

[3] https://buildd.debian.org/status/fetch.php?pkg=aircrack-ng&arch=s390x&ver=1%3A1.6-2&stamp=1581210899&raw=0

**Comment by samueloph** [comment]
As a last resort, we can always set s390x as non supported for the aircrack-ng package, just making sure it's not some bug that affects other archs (amd64, i386, arm64...) that went undetected.

**Comment by jbenden** [comment]
After researching on a sparc64 machine, I've found the tests fail because the resulting PCAP's generated are in big endian format, where as the unit test checks a known MD5 sum of a little endian file.

I'd recommend disabling the file MD5 comparison performed in the unit tests, for packaging purposes. My testing shows it is only two airdecap-ng tests that fail, due to BE vs. LE files generated.

**Comment by jbenden** [comment]
Hello, commits 7ebd425acab2edd04272dd32273a6baf55e2a55f and 9156f10ffa0e2673609a33cc587cb0818e97c473 fix the endian problem (always generate little-ending pcap & read radiotap length as little-endian) for all big-endian machines.

All tests now pass sparc64 big-endian machine.

**Comment by jbenden** [comment]
PS: commit ed5662225c9ec24efdb42b8d629f7dd38e8ad952 solves the original, first problem of the assert.

**Comment by samueloph** [comment]
@jbenden great,

I uploaded the patched package to Debian Unstable yesterday, it already got synced to Ubuntu 20.04, it should downstream to Kali soon.

Thanks for the quick feedback :)

**Comment by samueloph** [comment]
FWIW Kali, Debian Testing and Ubuntu 20.04 all have 1.6 now :)
