### ISSUE TITLE
airgraph-ng python libraries conflict with python-graphviz

### ISSUE THREAD

**Issue by mnhauke** [aircrack-ng/aircrack-ng#2119]
During installation the following files are written into %{python3_sitelib}/graphviz/
```
/usr/lib/python3.7/site-packages/graphviz/__init__.py
/usr/lib/python3.7/site-packages/graphviz/__pycache__/__init__.cpython-37.pyc
/usr/lib/python3.7/site-packages/graphviz/__pycache__/libDumpParse.cpython-37.pyc
/usr/lib/python3.7/site-packages/graphviz/__pycache__/libOuiParse.cpython-37.pyc
/usr/lib/python3.7/site-packages/graphviz/__pycache__/lib_Airgraphviz.cpython-37.pyc
/usr/lib/python3.7/site-packages/graphviz/libDumpParse.py
/usr/lib/python3.7/site-packages/graphviz/libOuiParse.py
/usr/lib/python3.7/site-packages/graphviz/lib_Airgraphviz.py
```
The problem is that the following files are already owned by python-graphviz package:
```
/usr/lib/python3.7/site-packages/graphviz/__init__.py
/usr/lib/python3.7/site-packages/graphviz/__pycache__/__init__.cpython-37.pyc
```
Such situations are really bad for distribution packagers since those introduce unnecessary file conflicts and must be handled somehow.

For the openSUSE package that means that I just don't package airgraph-ng it's libraries:
https://pmbs.links2linux.org/package/view_file/home:mnhauke:branches:Extra/aircrack-ng/aircrack-ng.spec?expand=1

A quick search on the the internet showed that others also already ran into this issue:
e.g. https://bugs.archlinux.org/task/65403

**Comment by aircrack-ng** [comment]
Please follow the bug report format next time.

Version: 1.6

**Comment by jbenden** [comment]
Maybe all files should land inside a proper named folder within `libexec` which includes actual bin scripts; then inside `/usr/bin` a shim exists that sets the python lib directory and passes off control to the bin script. I've seen this technique used before and it seems to work good.

Alternatively, the inner packages need renamed to have a prefix of `aircrack`, for instance.

Thoughts, comments, or suggestions are welcomed,
-Joe
