### ISSUE TITLE
cracking error

### ISSUE THREAD

**Issue by AnkurYogi** [aircrack-ng/aircrack-ng#2120]
Packets contained no EAPOL data; unable to process this AP.
![IMG_20200211_225358](https://user-images.githubusercontent.com/55404644/74261695-87f58580-4cf3-11ea-9b52-c3bdbb16a972.jpg)
![IMG_20200211_225358](https://user-images.githubusercontent.com/55404644/74261787-a9ef0800-4cf3-11ea-80d3-5bcefb068b02.jpg)

**Comment by aircrack-ng** [comment]
This is a bug tracker, for support, use our forum.

This is most like a technique issue, check our documentation first.
