### ISSUE TITLE
pmkid key not found

### ISSUE THREAD

**Issue by boo6ster** [aircrack-ng/aircrack-ng#2125]
I followed these instructions:
https://miloserdov.org/?p=2122
https://miloserdov.org/?p=2255

To capture packages, I used commview for wifi instead of wireshark. I made an incorrect login from the other wifi card to get 1 handshake message containing pmkid. I exported the packets from commview to pcap wireshark format. In wireshark I have marked two packets of the hotspot I'm interested in - message 1 containing pmkid and beacon. I exported two marked packets in wireshark to a pcap file. Aircrack-ng.exe correctly detects the network with the message wpa 0 handshake with pmkid. After running brute force, aircrack-ng says no password has been found. The correct password was in the password list file.
When I used wireshark to capture packets, the effect was the same. Key not found.

Windows 8x64, commview for wifi 7, wireshark 3.2.1, aircrack-ng 1.6

When I used kali linux 2020.1 to capture packets I used airodump and wireshark to export two marked packets for aircrack. The effect was the same. Key not found.

Are the above instructions incorrect? what is wrong?

Can aircrack break a pmkid with two packets / pcap wireshark files containing a handshake 1/4 message with pmkid and beacon broadcast without using hcxdumptool, hcxtools and hashcat?

**Comment by aircrack-ng** [comment]
Please upload the capture file.

Next time, please fill the bug report as explained.

**Comment by boo6ster** [comment]
I did another arduous test on the same network using bettercap, hcxdumptool, hcxtools and hashcat on kali linux. Hashcat also did not find the password from the file. I used software connectify hotspot for windows to attack because I do not have access to any other wifi with a password that would send pmkid in M1 :) It is possible that pmkid from this software is erroneous or is not supported for this type of attack. If it's a false alarm on my part, I'm sorry.

**Comment by aircrack-ng** [comment]
I'm assuming this can be closed. Reopen if incorrect.

**Comment by IDREESah** [comment]
Key not found in the world list, using aircrack-ng what should I do to decrypt the handshake cap file?

**Comment by bans875** [comment]
Hello everyone, I'm also experiencing the same issue, key not found.
