### ISSUE TITLE
zd1211rw PROBLEM (Injection and compilation)

### ISSUE THREAD

**Issue by gianfelicevincenzo** [aircrack-ng/aircrack-ng#2128]
Hi. I have an adapter wireless zydas with chipset zd1211rw and not work properly with inejction mode.
I followed [this](https://www.aircrack-ng.org/doku.php?id=zd1211rw) guide but nothing worked...and the compilation was unsuccessful.

`
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.9.0-11-common/scripts/Makefile.build:309: set di istruzioni per l'obiettivo "/home/vincenzogianfelice/Scaricati/compat-wireless-2010-10-10/compat/main.o" non riuscito
make[5]: *** [/home/vincenzogianfelice/Scaricati/compat-wireless-2010-10-10/compat/main.o] Errore 1
/usr/src/linux-headers-4.9.0-11-common/scripts/Makefile.build:560: set di istruzioni per l'obiettivo "/home/vincenzogianfelice/Scaricati/compat-wireless-2010-10-10/compat" non riuscito
make[4]: *** [/home/vincenzogianfelice/Scaricati/compat-wireless-2010-10-10/compat] Errore 2
/usr/src/linux-headers-4.9.0-11-common/Makefile:1543: set di istruzioni per l'obiettivo "_module_/home/vincenzogianfelice/Scaricati/compat-wireless-2010-10-10" non riuscito
make[3]: *** [_module_/home/vincenzogianfelice/Scaricati/compat-wireless-2010-10-10] Errore 2
Makefile:152: set di istruzioni per l'obiettivo "sub-make" non riuscito
make[2]: *** [sub-make] Errore 2
Makefile:8: set di istruzioni per l'obiettivo "all" non riuscito
make[1]: *** [all] Errore 2
make[1]: uscita dalla directory "/usr/src/linux-headers-4.9.0-11-amd64"
Makefile:66: set di istruzioni per l'obiettivo "modules" non riuscito
make: *** [modules] Errore 2
`

How can I solve it? Is there another way?

(debian 9.11, kernel 4.9 amd64) 

**modinfo**:

```
filename:       /lib/modules/4.9.0-11-amd64/kernel/drivers/net/wireless/zydas/zd1211rw/zd1211rw.ko
firmware:       zd1211/zd1211_uphr
firmware:       zd1211/zd1211b_uphr
firmware:       zd1211/zd1211_ub
firmware:       zd1211/zd1211b_ub
firmware:       zd1211/zd1211_ur
firmware:       zd1211/zd1211b_ur
version:        1.0
author:         Daniel Drake
author:         Ulrich Kunitz
description:    USB driver for devices with the ZD1211 chip.
```

**Comment by ZeroChaos-** [comment]
Your kernel is NINE years newer than the driver you are trying to install.
If you didn't break your system yet it should "just work"

**Comment by gianfelicevincenzo** [comment]
Therefore, I assume that in 9 years progress has been made ... so it should work quietly ... and instead (with the updated drivers from the debian repo) why doesn't it work?

**Comment by ZeroChaos-** [comment]
I don't see any errors reported other than compiling 10 year old drivers for no reason.  If you have an aircrack-ng error please feel free to report it.

**Comment by gianfelicevincenzo** [comment]
I explain better. I wanted to compile from the sources because I thought that the drivers provided by my distribution did not have some injection patches. This is what **aireplay-ng -9** reports (with driver of debian 9 - **firmware-zd1211**):

```
20:58:12  Trying card-to-card injection...
20:58:12  Attack -0:           OK
20:58:12  Attack -1 (open):    OK
20:58:12  Attack -1 (psk):     OK
20:58:12  Attack -2/-3/-4/-6:  OK
20:58:17  Attack -5/-7:        Failed
20:58:17  Injection is working!
```

The attacks **-5** and **-7** not work..

(I see that you have closed the post ... do I open a new one?)

**Comment by ZeroChaos-** [comment]
Not all drivers support sending or receiving fragments. Sorry about your
luck, try a different wifi card.

**Comment by gianfelicevincenzo** [comment]
What a pity...!!
One last question .... could it be that because of this problem, the attack with reaver doesn't work? because i noticed that when **aireplay** brings me this problem, reaver doesn't work properly either

Unfortunately, at the moment I don't have any other wireless adapter to try with ..
