### ISSUE TITLE
Ralink 3070 (rt2800usb) problem with fragmentation

### ISSUE THREAD

**Issue by gianfelicevincenzo** [aircrack-ng/aircrack-ng#2129]
Hi. Trying with:
`aireplay-ng -9 -i <interface_ap_simulation> <interface_monitor>`

report this error:

`01:55:14  Attack -5/-7:        Failed`

why?

(debian 9.11, kernel 4.9 amd64)

**modinfo**:

```
filename:       /lib/modules/4.9.0-11-amd64/kernel/drivers/net/wireless/ralink/rt2x00/rt2800usb.ko
license:        GPL
firmware:       rt2870.bin
description:    Ralink RT2800 USB Wireless LAN driver.
version:        2.3.0
```

**Comment by aircrack-ng** [comment]
A few things:
- Please follow the bug reporting format
- That is support, which is done in the forum, this is a bug tracker.
- Update your Debian, this is considered oldstable, soon to be EOLed. You will benefit from a lot of improvements.
