### ISSUE TITLE
Workflow problems caused by the code formatting checks in the build system

### ISSUE THREAD

**Issue by dmfreemon** [aircrack-ng/aircrack-ng#2132]
The build system currently uses an old version (v3.6 or v3.8) of clang for its code formatting verification.

These old versions of clang are not available in the current software repositories of distros (I'm referring to Fedora here, I have not checked others).  It seems a bit much to expect individuals wishing to contribute a PR to build old clang software from source on their workstations just to be able to run code formatting verification before submitting a PR.

Newer versions of clang are not compatible with v3.6/v3.8 (meaning that the code formatter uses different rules).

As a result, developers on current distros (again, Fedora in my case) cannot run code formatting verification locally on their workstation.

So we end up with a workflow loop of:

1. commit changes
2. push
3. submit PR
4. review code formatting failures reported by the build system
5. commit changes that only contain code formatting changes
6. push
7. go back to step 4

Examples of this can be seen in:

https://github.com/aircrack-ng/aircrack-ng/pull/2102
https://github.com/aircrack-ng/aircrack-ng/pull/2105

However, we also want to keep the git history as clean as possible, so the maintainers discourage commits that contain only code formatting changes.  The issue is that that would require either (a) changing git history that has already been pushed, or (b) require more work to rebase, etc., just for formatting changes, and even then, I don't _think_ (not 100% sure) we can rebase into the same branch that the github PR is pointing to (so would we also have to create a new PR in github for every code formatting commit?) 

My suggestion would be to use a different code formatting checker (that applies consistent rules over time), or relax the rules that are enforced so that the rules are simple and obvious to anyone just looking at other code in the codebase, and so only "obviously bad" formatting is caught by the build system.

Related:
https://github.com/aircrack-ng/aircrack-ng/issues/2101

**Comment by aircrack-ng** [comment]
AFAIK, you can just push the fix in the branch used of your PR. And step 7 shouldn't be needed as you can take the diff on Travis web interface.

Could you suggest a clang version that is available on currently supported Fedora, CentOS (8), Ubuntu (16.04, 18.04, 19.10 and future 20.04), Debian (10, testing).

We're open to use something else. Any other code formatting checker you know that applies rules consistently across versions?

I also remember there being clang-format docker somewhere.
