### ISSUE TITLE
where is “test” directory of the source files in opensuse os?

### ISSUE THREAD

**Issue by anlexN** [aircrack-ng/aircrack-ng#2133]
# System information
- OS: opensuse
- CPU: intel
- Wireless card and chipset (if relevant): intel

# Aircrack-ng version
- Version: 1.6

**Comment by aircrack-ng** [comment]
Details would be helpful. How did you install aircrack-ng, what OS version, and anything else to help us figure out what the problem is?

**Comment by anlexN** [comment]
For openSUSE Tumbleweed run the following as root:
```
zypper addrepo https://download.opensuse.org/repositories/security/openSUSE_Tumbleweed/security.repo
zypper refresh
zypper install aircrack-ng
```

**Comment by aircrack-ng** [comment]
What were you expecting exactly from that test/ directory? These are tests to ensure aircrack=ng is working properly, which is used mostly when developing it.

**Comment by anlexN** [comment]
I am learning aircrack-ng, so i need to know anything about it. and i can't build it from source in opensuse by myself. so can you help me ?

**Comment by aircrack-ng** [comment]
Check the wiki, it has instructions (also in README.md). For support, please use the forum, this is a bug tracker.
