### ISSUE TITLE
wrong use of libsqlite3 API 'sqlite3_bind_text'

### ISSUE THREAD

**Issue by Zero0one1** [aircrack-ng/aircrack-ng#2135]
According to the API documentation of libsqlite3, the fourth argument should be "the number of bytes", not "the number of character". So maybe it should be "sizeof()" instead of "strlen()" in
https://github.com/aircrack-ng/aircrack-ng/blob/c4981c7176edbb13043d1f42095ca2bb642c254b/src/airolib-ng/airolib-ng.c#L873

**Comment by aircrack-ng** [comment]
No, as this is a pointer, and a sizeof would give the size of the pointer.
