### ISSUE TITLE
how can i inject tcp packets to a wpa network without being connected to the network by just knowing the password?

### ISSUE THREAD

**Issue by minanagehsalalma** [aircrack-ng/aircrack-ng#2139]

**Comment by aircrack-ng** [comment]
No. FYI, next time please use the forum, this isn't a bug.

**Comment by minanagehsalalma** [comment]
> No

@aircrack-ng  why ?



> FYI, next time please use the forum, this isn't a bug.

Thanks i will keep that in mind.
