### ISSUE TITLE
amd64 Support for RTL8814AU

### ISSUE THREAD

**Issue by Chasbmw** [aircrack-ng/aircrack-ng#2144]
Have been trying to install RTL8812au driver for the following:
Processor:  AMD A8-7310 / Radeon R4
Ram: 8GB
Product ID:  00325-80000-00000-AAOEM /  HP 15-BA009DX
System - 64bit / x64 processor
Operating System:  Linux Mint 19.3
Wlan Adapter:   AWUS1900 / USB interface (rtl8814au)

Seems no option for amd64 processor in makefile or am I missing something in the install procedures.  Using make & make install will not give any error on default config (for x86) but does not load into the module when I look at lsmod.  lsusb does see the adapter with right Realtek code..
All three adapters are markes "y" in makefile.

Any ideas? 

Charles
charles.drummond@gmail.com

**Comment by username7291** [comment]
Have you tried make ARCH=x86_64 ?
That drivers are often not portable, the author test these on one single system(only alpha test).
You need to change stuff if your system is different than his. So much about linux compatiblity.

**Comment by Chasbmw** [comment]
Thanks I will try that...

**Comment by Chasbmw** [comment]
Put the variable ARCH=x86_64 in the Features section.  Worked like a charm on AMD processors.  Thanks

Charles
charles.drummond@gmail.com

**Comment by aircrack-ng** [comment]
Wrong repository
