### ISSUE TITLE
CAN'T USE DEAUTH ON SECOND TRY

### ISSUE THREAD

**Issue by mpethekiller** [aircrack-ng/aircrack-ng#2148]
Hello i'm new int this github forum, i have a problem with deauth function cant kick the client on second try. I mean 1 day ago i try to use aircrack and it works to kick someone from my hotspot.
but now i even cant kick when i use deauth on all channel.

sorry for my bad english. hope someone understand and give me some solution. thanks

**Comment by username7291** [comment]
How you see that the client is still connected? Do you tryed to access for example a webpage?
airodump-ng dont process deauth/correctness of handshakes and still show that the client is connected without restarting.
I for example have a criminal Neighbor that trys to connect with a wrong pass to my AP, airodump-ng shows this as connected but the AP clearly shows as blocked/handshake failed.
You need to be on the same channel like the AP, some clients reconnect automatic everytime(you see Handshake in airodump), some not. 
Its required that you post much more details, like output of the program. Just with this is no bugreport, more a question for a help board.

**Comment by mpethekiller** [comment]
Thanks for your response.
> How you see that the client is still connected? Do you tryed to access for example a webpage?
Yes I tryed open YT in the client and can still streaming..

> You need to be on the same channel like the AP, some clients reconnect automatic everytime(you see Handshake in airodump), some not.
How to see if your channel same like your AP ? (Newbie question sry)

> Its required that you post much more details, like output of the program. Just with this is no bugreport, more a question for a help board.
Oh and one more the ACKS show 0|0 , is it because my adapter wireless ? 

Thanks again.,

**Comment by aircrack-ng** [comment]
This is a bug tracker. You're looking for the forum: https://forum.aircrack-ng.org
