### ISSUE TITLE
Can't quit or stop aircrack-ng

### ISSUE THREAD

**Issue by HibaShoukath123** [aircrack-ng/aircrack-ng#2149]
I can't quit aircrack-ng when I press either ctrl+c or q. I need to do that because I want to pause then continue.

**Comment by aircrack-ng** [comment]
Bug report format is provided so we can best help fix issues. You did not fill the bug report where it clearly indicate what information we need and instead decided to delete everything. 

Reopen this bug after editing your bug report and providing information like we ask.

**Comment by HibaShoukath123** [comment]
Dear sir, 
Version: Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
OS: kali linux 2020.2
aircrack-ng handshake.cap -w wordlist
It runs nicely, but I can't stop it using q or ctrl+c .  I may need to do this in case I am using it with john to save my session then restore it later.

**Comment by tydonk** [comment]
I'm having the same issue, same info as @hothefa1998 big report.  Can't quit, stop or pause a session

**Comment by aircrack-ng** [comment]
Update to the latest kali, and try again:

```
apt update
apt dist-upgrade
```

If it still happens after that, reopen the ticket and provide the capture file and wordlist used.

**Comment by omgmajk** [comment]
This is still happening btw.

**Comment by SC0d3r** [comment]
Same issue :(

**Comment by Uditha-Sanjaya** [comment]
use this " | tee " at end of your line

ex :  jhon --wordlist= ####### --stdout --session=jk  | aircrack-ng handshake.cap -b 00:11:22:33:44:55 -w - | tee

then try Q or Ctrl+C , I will work !!!
