### ISSUE TITLE
BlackArch, hasn't got the dependency usbutils?

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#2156]
OS: BlackArch

The package is available in the Arch community repos. Installing it does not cause any problems, but if you try to use it, it says, you should install `lsusb`, too. So why isn't the package `usbutils` marked as dependency?

**Comment by aircrack-ng** [comment]
The way you wrote it is confusing. It sounds like you are saying usbutils should be mentioned as a dependency for airmon-ng which is taken care of by e94b307a0878fff0913d5473682005241a9accb4

If it isn't what you said, reopen and reexplain the issue.
