### ISSUE TITLE
Packets contained no EAPOL data; unable to process this AP.

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#2157]
Hi , im trying to break to wpa2 and i dump on my AP and saved the capture file , but when im trying to brute force my list i got this error ( i did deauth and after that i leaved airodump-ng for 8 minuts to make sure capture file is correct )

Reading packets, please wait...
Opening output1-01.cap
Read 16668 packets.

   #  BSSID              ESSID                     Encryption

   1  (my ap bssid )  (my essid )           WPA (0 handshake)

Choosing first network as target.

Reading packets, please wait...
Opening output1-01.cap
Read 16668 packets.

1 potential targets

Packets contained no EAPOL data; unable to process this AP.

Quitting aircrack-ng...

**Comment by aircrack-ng** [comment]
Support is done in the [forum](https://forum.aircrack-ng.org/). This is a technique issue, there are no handshake in your capture. Check the wiki, there is s an [analysis of a handshake](https://aircrack-ng.org/doku.php?id=wpa_capture) to help you understand what is missing

**Comment by Jasperchan000** [comment]
Hello, is your problem solved? I'm having the same problem as you.
Reading packets, please wait...
Opening openwrt
Failed to open 'openwrt' (2): No such file or directory
Opening 1-01.cap
Read 322 packets.

1 potential targets

Packets contained no EAPOL data; unable to process this AP.


Quitting aircrack-ng...

**Comment by heriipurnama** [comment]
same issue

**Comment by Rizwan102003** [comment]
Got the same issue but i terminated the de auth attack after getting the wpa handshake. Can someone explain what I'm missing?

**Comment by sgdyeye** [comment]
هل هناك من حل مشكلة Packets contained no EAPOL data; unable to process this AP.

**Comment by sgdyeye** [comment]
Packets contained no EAPOL data; unable to process this AP.

**Comment by Rizwan102003** [comment]
@sgdyeye You are trying to crack a WPA2-PSK passphrase but you didn't capture the right data in your *.cap file. The captured handshake file does not always capture the passpord . Read more in the forum as given above.
