### ISSUE TITLE
Incorrect key counting

### ISSUE THREAD

**Issue by ur7imd** [aircrack-ng/aircrack-ng#2160]
subj on RPi 4 and TinkerBoard

<h2>System information</h2>

- OS: Linux RPi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
- CPU: Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz
- Wireless card and chipset (if relevant): Ralink mt7601u

<h2>Aircrack-ng version</h2>

- Version: 1.6 rev 85754a8c
- Commit Revision hash: ???

<h2>How to reproduce the issue</h2>

- aircrack-ng -w anydic.txt -b \<bssid\> scan.cap

![2020-07-11-095946_1920x1200_scrot](https://user-images.githubusercontent.com/68142813/87219019-8a224580-c360-11ea-8435-cd4f2af7815a.jpg)

**Comment by aircrack-ng** [comment]
Closed as it doesn't follow bug reporting guidelines. Reopen after providing required information.
