### ISSUE TITLE
Airdump ng under mac

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#2161]
How to use airdump ng to get the MAC client side connected to AP under mac

mac book_pro
aircrack-ng 1.6
```
~]$ airodump-ng -w /tmp/airportSniffBBYS6K.cap -c 1 --bssid EA:0E:5A:A6:7E:7F en0
Failed initializing wireless card(s): en0
````

**Comment by aircrack-ng** [comment]
Mac isn't supported at this time. Support is provided in the [forum](https://forum.aircrack-ng.org/).
