### ISSUE TITLE
Airmon nh doesnt change name of my Interface

### ISSUE THREAD

**Issue by devilmen80** [aircrack-ng/aircrack-ng#2181]
Hello I have a problem now 

When I put Interface Wlan0 in monitor mode with airmon-ng it don't change name to my Interface and it is always the same name
Before today I don't had this problem..
Something can help me?
Thanks

**Comment by ZeroChaos-** [comment]
This isn't a bug.  If it were a bug then you would have an error message from airmon-ng.  Show us your output please.
