### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#2183]

**Comment by slt90** [comment]
> Hi I have an alpha AWUS036ACH wifi card and I use Kali linux 2020.3 after installing the driver https://github.com/aircrack-ng/rtl8812au
> i can detect both 2.4 and 5ghz networks but i have problems with 802.11ac frequencies.
> If I use airodump-ng --band a wlan1 I don't detect the 802.11AC frequencies to find them I have to use
> airodump-ng wlan1 -C 5100-5900, in this way I detect the AC networks (mac address and CH) but I can't see their ESSID. The network does not have a hidden ssd but airodump-ng cannot view it.
> How can I solve the problem?
> my test antennas are Ubiquiti rocket AC.
> Thanks.
> 
> ![20200919_154002](https://user-images.githubusercontent.com/71384188/93668909-359df380-fa90-11ea-9d2d-aa63ea9caed5.jpg)
> ![20200919_1337370](https://user-images.githubusercontent.com/71384188/93668910-36368a00-fa90-11ea-87f2-57e82a7d4154.jpg)

**Comment by Mister-X-** [comment]
So, you opened a bug in this repo, in [rtl8812au](https://github.com/aircrack-ng/rtl8812au/issues/724), as well as a thread in the [forum](https://forum.aircrack-ng.org/index.php/topic,7695.msg14052.html)?

Closing, not duplicate, but triplicate.
