### ISSUE TITLE
osdep/linux.c: double free() when not using libnl causes child process crash in airodump-ng

### ISSUE THREAD

**Issue by dracode** [aircrack-ng/aircrack-ng#2185]
# Issue type
- Defect - Crash

# System information

- OS: Android
- CPU: Cortex-A53

# Aircrack-ng version
- Version: 1.6

# Defect
in `do_linux_open`, when `CONFIG_LIBNL` is not defined,
the `iwpriv` variable is copied to the `priv_linux` struct here:
`dev->iwpriv = iwpriv;`

later in the function, `iwpriv` is freed.

then in `do_free`, the same pointer is free'd again:
`if (pl->iwpriv) free(pl->iwpriv);`

causing crash.

## How to reproduce the issue

compile aircrack suite with --disable-libnl.
run airodump-ng on more than one channel.
airodump-ng will fork() a new process to run the channel hopping.  the channel hopping child process will crash.

**Comment by dmfreemon** [comment]
This was also fixed in (from November 2019):
https://github.com/aircrack-ng/aircrack-ng/pull/2094
