### ISSUE TITLE
Solve

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#2187]

**Comment by aircrack-ng** [comment]
This is referring https://github.com/aircrack-ng/rtl8812au/issues/724

There is no SSID IE in the beacon. Reopen this ticket IF you can provide the location of the SSID IE for this special and how to decode it, with example PCAP.

**Comment by Zanzaux** [comment]
Se disconnetto il client collegato all'ap tramite aireplay  in "probes "  rilevo il nome della rete wifi ,ma in ESSID rimane sempre <length:  0> 
[AC.zip](https://github.com/aircrack-ng/aircrack-ng/files/5332754/AC.zip)
