### ISSUE TITLE
aircrack-ng: incorrect size definition of dictionaries on 32-bit machines

### ISSUE THREAD

**Issue by drygdryg** [aircrack-ng/aircrack-ng#2192]
# Issue type

- Defect - Incorrect value displayed/received/stored

# System information

- OS: Arch Linux 32 (32-bit), Linux Mint 19.3 (32-bit)
- CPU: Intel Core Duo (32-bit x86)

# Aircrack-ng version

- Version: 1.6
- Commit Revision hash: 73bacf8

# Defect

Ran aircrack-ng with different dictionaries, it displays the size of dictionary and time left larger than it actually is.
Compiled with GCC 10.2.0 (on Arch Linux) and GCC 7.5.0 (on Linux Mint).
![2020-10-26_07-31](https://user-images.githubusercontent.com/43933400/97135899-c4bebb00-1762-11eb-8123-d1b897085504.png)
![2020-10-26_08-03](https://user-images.githubusercontent.com/43933400/97135909-c8ead880-1762-11eb-8781-74c189cb85a4.png)

**Comment by jbenden** [comment]
Hello,

I have a PR that I'd like for you to test, to see if it fixes the bug. The PR is #2195.

Thanks!
-Joe

**Comment by drygdryg** [comment]
Fixed, thanks.
Arch Linux 32: fixed.
Linux Mint 19.3: fixed.

**Comment by jbenden** [comment]
Thank you for reporting this!
