### ISSUE TITLE
Airmon-ng has some issues... ifconfig shows wlan0 but i couldn't put it in Monitor mode.

### ISSUE THREAD

**Issue by kdiepie** [aircrack-ng/aircrack-ng#2198]
(root??localhost)-[~]# airmon-ng start wlan0

ls: cannot access '/sys/class/net': No such file or directory
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"

Requested device "wlan0" does not exist.
Run /usr/sbin/airmon-ng without any arguments to see available interfaces # #

**Comment by aircrack-ng** [comment]
We'll need more details on what system you're running it on, as well as the version. Basically all the stuff in the bug report template. In this case we'll probably also need hardware information about the platform (**Attach** outputs of `lscpu`, `lshw`), and please use markdown formatting to make it easier to read.

**Comment by ZeroChaos-** [comment]
This has all been rewritten with safety checks quite some time ago.  There is nothing actionable left in this bug report
