### ISSUE TITLE
 Incorrect work of Besside-ng. Error: Bad Beacon

### ISSUE THREAD

**Issue by Xanuman** [aircrack-ng/aircrack-ng#2203]
OS: Kali Linux Arm64 (last update)
DEV: Raspberry Pi 4
WiFi adapter: RTL 8812au
Aircrack-ng: Ver. 1.6

For a long time, Besside-ng worked perfectly on this system.

But recently, the program has completely stopped working correctly.

Outputs this to the terminal:

```
[17:51:12] / Scanning chan 04
Bad beacon
[17:51:12] - Scanning chan 05
Bad beacon
[17:51:12] | Scanning chan 05
Bad beacon
[17:51:12] - Scanning chan 06
Bad beacon
[17:51:12] - Scanning chan 06
Bad beacon
[17:51:12] | Scanning chan 07
Bad beacon
[17:51:13] / Scanning chan 07
Bad beacon
[17:51:13] - Scanning chan 07
Bad beacon
[17:51:13] | Scanning chan 08
Bad beacon
[17:51:13] / Scanning chan 08
```
What could be the problem?
#besside-ng

**Comment by knock-first** [comment]
I am also having this issue. Running a Raspberry Pi 3B+ on kernel 4.19.118-Re4son-v8+. I think it has to do with the chipset configuration of the NIC

**Comment by mrintern** [comment]
I am also having this issue. I have just recently setup my raspberry pi 4 with kali linux ARM 64 (from offensive security) so i'm certain everything is up to date.

I'm using the onboard wireless network interface controller

**Comment by Filip911** [comment]
Having same issue for some reason,using ralink wlan0  ...Any ideas or solutions?Im open :)

**Comment by maxgqc** [comment]
I have the same problem with Kali on my Raspberry Pi 4B with Alfa AWUS036NHA.
Aircrack-ng version on kali : aircrack-ng                           1:1.6+git20210130.91820bc-1

With the same hardware, if I switch my SD card to a Raspbian installation, it works flawlessly. The major difference I noticed is Aircrack-ng version which is : aircrack-ng                           1:1.5.2-3

I installed Aircrack-ng on raspbian using Katoolin3

Edit: I managed to make it work by downgrading Aircrack-ng to 1.5.2 using this package from Kali Repo : http://kali.download/kali/pool/main/a/aircrack-ng/aircrack-ng_1.5.2-3%2Bb1_armhf.deb
I can now use besside-ng without any problems

**Comment by AaaAziz** [comment]
Nanopi neo plus2 thx

1
wget --no-check-certificate http://kali.download/kali/pool/main/a/aircrack-ng/aircrack-ng_1.5.2-3%2Bb1_arm64.deb

2
sudo apt remove aircrack-ng

3
sudo apt install ./aircrack-ng_1.5.2-3+b1_arm64.deb

**Comment by psyhceros** [comment]
Is this fixed?

**Comment by xznhj8129** [comment]
> Nanopi neo plus2 thx
> 
> 1 wget --no-check-certificate http://kali.download/kali/pool/main/a/aircrack-ng/aircrack-ng_1.5.2-3%2Bb1_arm64.deb
> 
> 2 sudo apt remove aircrack-ng
> 
> 3 sudo apt install ./aircrack-ng_1.5.2-3+b1_arm64.deb

this does not work due to dependency hell

**Comment by AaaAziz** [comment]
> > Нанопи нео плюс2 спасибо
> > 1 wget --no-check-certificate http://kali.download/kali/pool/main/a/aircrack-ng/aircrack-ng_1.5.2-3%2Bb1_arm64.deb
> > 2 sudo apt удалить aircrack-ng
> > 3 sudo apt install ./aircrack-ng_1.5.2-3+b1_arm64.deb
> 
> это не работает из-за ада зависимостей

this works on nanopi neo2 , just moved to old.kali.org .  for other systems, you must specify the required file in the name

**Comment by m87quasar** [comment]
> > Nanopi neo plus2 thx
> > 1 wget --no-check-certificate http://kali.download/kali/pool/main/a/aircrack-ng/aircrack-ng_1.5.2-3%2Bb1_arm64.deb
> > 2 sudo apt remove aircrack-ng
> > 3 sudo apt install ./aircrack-ng_1.5.2-3+b1_arm64.deb
> 
> this does not work due to dependency hell

Working fine on Kali Debian 6.0.12
Download aircrack-ng_1.5.2-3+b1_arm64.deb from debian pkgs 
Then sudo apt install ./aircrack-ng_1.5.2-3+b1_arm64.deb

I get much better results from using hcxdumptool .pcapng [ng=new generation designed to work with hashcat .hc22000]

You will also need to install hcxtools, hcxpcapngtool convert .pcapng to .hc2200, aircrack-ng strips out way too much info which hcxdumptool & hashcat can use .....

**Comment by d3k4-k3rb3r0s** [comment]
Been fighting this all day. New install several times.  Apt binaries, from source, everything. Bad beacon no matter what.

**Comment by witoldpilecki88** [comment]
@d3k4-k3rb3r0s have you tried a different hardware interface?

**Comment by HarshVaragiya** [comment]
This issue still exists. Cannot seem to fix it, as rolling back to previous aircrack-ng version is a dependency hell as stated by @xznhj8129 !

Hardware: `Raspberry Pi Zero W`
OS: `Kali Pi-Tail` 
Uname: `Linux kali-raspberry-pi-zero-w-pitail 5.15.44-Re4son+ #1 Debian kali-pi (2022-07-02) armv6l GNU/Linux`
Aircrack-ng Version: `1.7`

**Comment by HarshVaragiya** [comment]
Tested the following versions: 
- aircrack-ng_1.6+git20200821.87bf5727-1_armel.deb
- aircrack-ng_1.2-0~rc3-0kali1_armel.deb 
- aircrack-ng_1.3-1_armel.deb 

All of these seem to not raise the Bad Beacon errors but give "Crappy Connection" a lot. I suspect this is due to the tiny built-in antenna of the pi-0W but i do not have a good way to test this. For me -> `aircrack-ng_1.3-1_armel.deb` seemed to work the best.

Archive: http://old.kali.org/kali/pool/main/a/aircrack-ng/

Steps:
```bash
wget 'http://old.kali.org/kali/pool/main/a/aircrack-ng/aircrack-ng_1.3-1_armel.deb' #(or the one for your arch)
sudo dpkg -i aircrack-ng_1.3-1_armel.deb
sudo besside-ng mon0 -p1 -W
```
