### ISSUE TITLE
airodump-ng problem MONITOR MODE signal PWR 

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/aircrack-ng#2204]
Hi I encountered the following problem using airodump-ng,  with aircrack-ng driver /rtl8812au 5.6.4.2 , 
if I use the mode managed by airodump-ng I detect the signal at a PWR power of -33, when I put the card in monitor mode the value becomes -71 !!!!

KALI 2020.4 64bit system

**Comment by ZeroChaos-** [comment]
we haven't had a release in a while but this already works correctly in git
