### ISSUE TITLE
Aireplay-ng and Aircrack-ng don't worked correctly.

### ISSUE THREAD

**Issue by qwertyuiop2k20** [aircrack-ng/aircrack-ng#2215]
Aircrack-ng has working keeps after password is found (when 100% programm showed password). Aireplay-ng send many packets. Tested on Debian 10. Version 1.2 (from Debian 9) haven't the problems. Help please.

**Comment by aircrack-ng** [comment]
This is support which is taken care of in the forum. And FYI, you'll need to provide more details on what you're doing that doesn't work, the hardware involved and drivers.
