### ISSUE TITLE
Airmon-ng check doesn't show udhcpc

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#2219]
# Issue type

- Defect - Incorrect value displayed/received/stored

# System information

- OS: Alpine Linux 3.12/3.13

# Aircrack-ng version

- Version: 1.6
- Commit Revision hash: e998873f148898179d3e1679bc09a087ae42fb74

# Defect
## How to reproduce the issue

Run `airmon-ng check` in a terminal. It will find one process but doesn't display any PID/process info. Killing it works just fine, but also no process info displayed.

**Comment by ZeroChaos-** [comment]
I'm not digging through git history to find the exact date it was added, but this has been in place since <2019 and this ticket requires no action except possibly for some linux distro to update their package
