### ISSUE TITLE
RTL8192EU Deauth problem

### ISSUE THREAD

**Issue by LaRevoltage** [aircrack-ng/aircrack-ng#2223]
I have tp-link 822n with rtl8192eu chipset, i have downloaded driver from here https://github.com/clnhub/rtl8192eu-linux.
When i start deauth with airodump, it says that successfuly deauthes, but all client's still connected to the network, help please

**Comment by ZeroChaos-** [comment]
if the driver doesn't transmit then open a bug for the driver

**Comment by albaluz35** [comment]
@LaRevoltage In my case enabling monitor mode and doing packet injection WORKS! as follows:

sudo apt update
sudo apt upgrade
sudo apt-get install linux-headers-\`uname -r\` build-essential dkms
git clone https://github.com/clnhub/rtl8192eu-linux.git
cd rtl8192eu-linux
sed -i -E 's/CONFIG_WIFI_MONITOR\s*=\s*n/CONFIG_WIFI_MONITOR = y/' Makefile

sudo rmmod 8192eu rtl8xxxu r8188eu
echo "blacklist rtl8xxxu" >> ./blacklist-rtl8xxxu.conf
sudo mv ./blacklist-rtl8xxxu.conf /etc/modprobe.d/
./install_wifi.sh

-----------------------

**IF THERE ARE PROBLEMS WITH ./install_wifi.sh, RUN ./uninstall_wifi.sh then execute make commands manually:**
\# sudo make
\# sudo make install

-----------------

sudo modprobe 8192eu
sudo lsmod |grep 8192eu                                                     

!To enable Monitor mode and test packet injection:!
=================================================

WL=wlan0
sudo iwconfig
sudo ifconfig $WL down
sudo airmon-ng check kill
sudo iwconfig $WL mode monitor
sudo ifconfig $WL up
sudo iwconfig

\# Wait for a moment and retry if there are issues or reboot and try the "
!To enable Monitor mode and test packet injection:! " steps
sudo aireplay-ng --test $WL
