### ISSUE TITLE
aireplay-ng for windows

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#224]
**Reported by anonymous on 2 Jun 2007 21:20 UTC**

Add some type of aireplay-ng for windows users so we can speed up the time it takes to allocate enough IVs to begin a crack.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 2 Jun 2007 21:20 UTC**

I don't understand, could you explain it a bit more.

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 2 Jun 2007 21:20 UTC**

My thoughts were to have a program that would allow packet injection, like aireplay-ng, on Windows OS. As to speed up the amount of packets that are captured by airodump-ng.

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 2 Jun 2007 21:20 UTC**

On all the injection options, I see you must have a PRGA (pseudo random generation algorithm) file. There seems to be no way of obtaining one of these on a Windows machine. So, maybe an aireplay-ng for Windows would allow Windows users to create PRGA (pseudo random generation algorithm) file.

**Comment by aircrack-ng** [comment]
**Comment by hirte on 2 Jun 2007 21:20 UTC**

read the forum about the porting to cygwin. it already works.

there will be no aireplay version for the 0.9 aircrack tree.

**Comment by aircrack-ng** [comment]
**Modified by anonymous on 2 Jun 2007 21:20 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 2 Jun 2007 21:20 UTC**

**Comment by Arnob231** [comment]
How can I use aireplay-ng in the window? It is asking for an adapter name. And when I give it says to open the help option. I just put this command, aireplay-ng.exe (Adapter name without brachets) -0 0 -a (bssid). But this not worked. Can you help me with this?
