### ISSUE TITLE
airmon-ng does not rename rtl8187 interface after enabling monitor mode

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#2245]
# Issue type

- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: N/A
- CPU: N/A
- Wireless card and chipset (if relevant): rtl8187 (mac80211 driver)

# Aircrack-ng version

- Version: 1.6
- Commit Revision hash: 91820bc

# Defect
## How to reproduce the issue

Airmon-ng used to rename the interface and add `mon` at the end. This behavior can be seen with the stable 1.6 release. It does not anymore, as of 91820bc.

Investigate what changed and if it affects other drivers as well. From there, we'll see what we'll do.

Note: Functionality (monitor mode) is unaffected.

## Related issues

Forum post: https://forum.aircrack-ng.org/index.php/topic,8407.0.html

**Comment by ZeroChaos-** [comment]
not a bug, some drivers don't support virtual interfaces

**Comment by scorpius** [comment]
It is a bug, because the rtl8187 supports virtual interfaces. Something changed between 1.6 and now.

**Comment by ZeroChaos-** [comment]
> It is a bug, because the rtl8187 supports virtual interfaces. Something changed between 1.6 and now.

I can understand why you feel this way, but check out how it works:
https://github.com/aircrack-ng/aircrack-ng/blob/master/scripts/airmon-ng.linux#L483

The driver says it doesn't support interface combinations, so airmon-ng doesn't create a second interface.  I agree, there is a bug here, but it's not in airmon-ng.  I am open to a more reliable way to detect crap drivers, but honestly this seems like something very valid to report to the kernel driver maintainer.
