### ISSUE TITLE
Airodump seems to send packages but in fact no packages are send

### ISSUE THREAD

**Issue by TheMMcOfficial** [aircrack-ng/aircrack-ng#2246]
I have 2 wireless card with different chipset. One intel 9560 and a mediatek mt7612u. I'm able to put the cards in monitor mode and the injection seems to work on 2,4ghz. But when I try on 5ghz all the clients connected to my router continues there conversations like nothing happen... I also try to check if I can see the deauth in kismet or wireshark but I don't see them. I'm aware that not all the card support the injection but i'm confused...

**Comment by ZeroChaos-** [comment]
new airmon-ng has a check for this, but almost certainly your reg domain is unset.
"iw reg get" and assuming I'm right, "iw reg set XX" where XX is the right two letter code for your country.

**Comment by TheMMcOfficial** [comment]
```
sudo iw reg get
global
country MY_COUNTRY: DFS-FCC
	(2402 - 2472 @ 40), (N/A, 30), (N/A)
	(5150 - 5250 @ 80), (N/A, 23), (N/A), NO-OUTDOOR, AUTO-BW
	(5250 - 5350 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
	(5470 - 5600 @ 80), (N/A, 24), (0 ms), DFS
	(5650 - 5730 @ 80), (N/A, 24), (0 ms), DFS
	(5735 - 5835 @ 80), (N/A, 30), (N/A)

                                                                                                                              

 sudo iw wlan1 set channel 100
                                                                                                                              

sudo aireplay-ng -D --test -e SSID -a ROUTER_MAC wlan1
07:50:07  Trying broadcast probe requests...
07:50:08  No Answer...
07:50:08  Found 1 AP 

07:50:08  Trying directed probe requests...
07:50:08  ROUTER_MAC - channel: 100 - 'SSID'
07:50:14   0/30:   0%

```

**Comment by TheMMcOfficial** [comment]
Ok my bad we need to be really careful to check the DFS channel in your country. My lab was using those channels at the time of my tests. I succeeded to inject on specifics channel that are not DFS in my country.
The success rate is not 100% but satisfying :)
