### ISSUE TITLE
A litile problem when converting .pcap to .hccapx

### ISSUE THREAD

**Issue by markopola** [aircrack-ng/aircrack-ng#2258]
└─$ sudo aircrack-ng -j hs hs.pcap                                                                                                                                 1 ⨯
Reading packets, please wait...
Opening hs.pcap
Read 4 packets.

   #  BSSID              ESSID                     Encryption

   1  18:D6:C7:E6:82:4A                            WPA (1 handshake)

Choosing first network as target.

Reading packets, please wait...
Opening hs.pcap
Read 4 packets.

1 potential targets

Building Hashcat (3.60+) file...

An ESSID is required. Try option -e.

Quitting aircrack-ng...

Why ESSID there are empty?

**Comment by aircrack-ng** [comment]
The error message is pretty clear, you need to provide a SSID. And this is a support request, which is to be done in the forum.

Also, please follow the bug reporting guidelines from the template next time.
