### ISSUE TITLE
Aircrack-ng hangs after ctrl-c.

### ISSUE THREAD

**Issue by BloodBlight** [aircrack-ng/aircrack-ng#2259]
- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information
- OS: Ubuntu 20.04
- CPU: Xeon X5660

# Aircrack-ng version
- Version: 1.6
# Defect
## How to reproduce the issue
When reading a pcap file, press Ctrl-C at the selection menu will result in a loop:

```
#aircrack-ng SomeFile.cap-01.cap 
Reading packets, please wait...
Opening SomeFile.cap-01.cap
Read 2218 packets.

   #  BSSID              ESSID                     Encryption

...stuff...

Index number of target network ? ^C  
Quitting aircrack-ng...
^C
Quitting aircrack-ng...
^C
Quitting aircrack-ng...
^C

```

## Related issues
#1989
#2002

**Comment by BloodBlight** [comment]
Update, this happens if the file is sill being written to my airodump

**Comment by aircrack-ng** [comment]
This should be fixed in the development version. Could you try the latest git master and report back?

**Comment by aircrack-ng** [comment]
Reopen the issue if it still happens with latest git master.
