### ISSUE TITLE
Can't open aircrack-ng

### ISSUE THREAD

**Issue by termux4me2** [aircrack-ng/aircrack-ng#2260]
Could not open '/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so': dlopen failed: library "/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so" not found

**Comment by aircrack-ng** [comment]
Please follow the bug reporting guidelines. You did not provide enough information for us to properly diagnose the issue.
