### ISSUE TITLE
Cut a new gcc-10 compatible release.

### ISSUE THREAD

**Issue by trofi** [aircrack-ng/aircrack-ng#2261]
Current `aircrack-ng-1.6` release tarball is not compatible to `gcc-10`:

```
ld: ./.libs/libradiotap.a(radiotap.o):(.bss+0x0): multiple definition of `__packed'; lib/osdep/.libs/libaircrack_osdep_la-linux.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2990: libaircrack-osdep.la] Error 1
```

It comes from `ieee80211_radiotap_header`, fixed in d4496006ac1e0c99908108b998ae39afb0658733.

Thanks!

**Comment by aircrack-ng** [comment]
There are 2 issues being worked on before we do a release.
