### ISSUE TITLE
When will aircrack-ng be runable on the Mac M1

### ISSUE THREAD

**Issue by zerodev-exe** [aircrack-ng/aircrack-ng#2265]
Hello there mr. aircrack-ng I was just woundnderieng when will you make aircrack-ng runable on the mac M1

**Comment by jbenden** [comment]
Hi!

Are you asking about a package or the source code? The source code in the git repository should compile and run just fine.

Thanks,
-Joe

**Comment by aircrack-ng** [comment]
No update, so closing. @Altair933 next time, please follow the bug reporting guidelines.
