### ISSUE TITLE
Aircrack-ng is not stoped after password was found

### ISSUE THREAD

**Issue by qwertyuiop2k20** [aircrack-ng/aircrack-ng#2267]
Aircrack-ng (no matter what version 1.6 or 1.5.2-3) is not stoped after password was found. This problem is the .deb paket for Debian / Kali Linux. Ubuntu hasn't the problem. But when I installed Ubuntu version (1.6-4) on my Debian 11 - problem remains. I can't understand what is the problem, but version 1.2 was work succesfully (now I should using version 1.2 from Debian Stretch on my Debian Bullseye, the version hasn't problems, but she is obsolete).

## System information

- OS Name: Debian Bullseye
- OS Version: 11
- CPU: Dual Core Intel Core i5-3340M
- Wireless card and chipset (if relevant): Qualcomm Atheros AR9485 Wireless Network Adapter (AR5B225)

## Aircrack-ng version

- Version: 1.6

**Comment by aircrack-ng** [comment]
The issue should be fixed in git master. Does the issue happens with latest git master. If it does, please reopen the issue.
