### ISSUE TITLE
Besside-ng 1.6 beacon issue

### ISSUE THREAD

**Issue by qwertyuiop2k20** [aircrack-ng/aircrack-ng#2268]
Besside-ng in Aircrack-ng version 1.6 has problem - send bad beacon, previous version (1.5.2-3) hasn't the problem

## System Information
OS: Debian 11 Bullseye

**Comment by aircrack-ng** [comment]
Could you at least provide the command you ran so we can replicate the issue? And update the title if necessary.

**Comment by qwertyuiop2k20** [comment]
sudo besside-ng wlp3s0mon
--------------------------------------------
(my network adapter switched in monitor mode airmon-ng and was renamed from wlp3s0 on wlp3s0mon)
my network wifi card is AR5B225

**Comment by ParadoxInfinite** [comment]
@aircrack-ng I've seen this issue too, with the regular version from Kali linux as well as the latest version(from github).

When I run `sudo besside-ng wlan1mon`, It keeps saying Bad beacon, refer to this issue https://github.com/aircrack-ng/aircrack-ng/issues/2203. As the last comment on the issue suggests, using a previous aircrack version, `aircrack-ng_1.5.2-3+b1_arm64`, fixes this. I would like to pick up this issue and help fix it, if you could help me on any pointers, I'd love to have a look! Let me know.

I'd debugged it once before, but I didn't get far, so any help would be appreciated, I'll post my findings here once I get back to the same point I was at the previous time.

**Comment by themustafaomar** [comment]
I'm having the exact same issue.

I gave `aircrack-ng` v1.7 a try but it doesn't fix the issue as well :(

Could you please take a look @aircrack-ng 

- Kali Linux: 2022.1 | 2022.2

- Aircrack-ng: 1.6 | 1.7

- Chipset: MT7612U

**UPDATE**: I've modified the source code deepening on #2275 and it's working perfectly.

![image](https://user-images.githubusercontent.com/46113191/171923639-7b90dfbc-c48b-48b3-a2d6-7aaad46691f1.png)

**Comment by psyhceros** [comment]
> 

How did you fixed it?

**Comment by ParadoxInfinite** [comment]
@psyhceros you will have to modify the code manually as mentioned in https://github.com/aircrack-ng/aircrack-ng/pull/2275 for now. If and when that gets merged, the packaged binaries should automatically be fixed.

**Comment by psyhceros** [comment]
@ParadoxInfinite  Thank you so much! It's finally working now.

**Comment by d3k4-k3rb3r0s** [comment]
No luck with anything mentioned here either.
