### ISSUE TITLE
Aircrack-ng is not stoped after password was found (again)

### ISSUE THREAD

**Issue by qwertyuiop2k20** [aircrack-ng/aircrack-ng#2269]
Aircrack-ng (last git version) is not stoped after password was found. It's was tested on Debian 11 Bullseye and Debian 10 Buster.
The problem repeated itself. The program continues to run after the passphrase was found without stopping, only when executed 100% the program displays the password. You can check for yourself on these systems.

## System information

- OS Name: Debian 11 Bullseye
- OS Version: 11
- CPU: Dual Core Intel Core i5-3340M
- Wireless card and chipset (if relevant): Qualcomm Atheros AR9485 Wireless Network Adapter (AR5B225)

## Aircrack-ng version

- Version: Aircrack-ng 1.6 rev `e225caa0`

**Comment by qwertyuiop2k20** [comment]
In the program aircrack-ng I did not know this problem in the code, when I checked its latest version with version 1.2 - there are many differences. But for some reason after this version all versions of the program including the last one on the githab have this bug when the program is already installed on Debian.
How to stop the program when it found the passphrase at this moment? This problem is on all versions of Debian, now i using Bullseye 11. It turns out that there is a bug somewhere in the program.

**Comment by qwertyuiop2k20** [comment]
What did you do after version 1.2 that the program (aircrack-ng) does not stop when the password was found?

**Comment by qwertyuiop2k20** [comment]
I noticed that version 1.6 has mutexes in the code and version 1.2 doesn't. As a result, the two versions of the program work differently in Debian. But I can't solve this problem by myself, maybe Debian has mutex problems. Help me, please. Ubuntu hasn't the problem, but i am Debian user, and maybe developers Ubuntu can help.

**Comment by aircrack-ng** [comment]
As mentioned in #2293, this has been fixed some time ago. Test current git, and reopen this bug with updated information if this still happens.

**Comment by NicoAlmazan** [comment]
I don`t know if my issue is the same, but i've created a txt file with the password of the handshake I`m trying to crack. The program just finishes with the "KEY NOT FOUND" message even though I know for sure it is there. Can anybody help me? Thank you!

**Comment by MASTREX** [comment]
It might be due to uncrackable hashes caused due striping tools.
