### ISSUE TITLE
m1 macbook air issue about "make"

### ISSUE THREAD

**Issue by Fluxico** [aircrack-ng/aircrack-ng#2270]
![image](https://user-images.githubusercontent.com/42116519/136513902-cb8d4f77-914a-4e71-8ade-9e0f4937305c.png)
how to ...

**Comment by ykugb** [comment]
I have the same issue on macOS Monterey

**Comment by aircrack-ng** [comment]
There is zero details in this report, so we can't do anything. Update the ticket with the required information as indicated when filing it.
