### ISSUE TITLE
Same Key is Showing even after changing the password of the wifi machine . 

### ISSUE THREAD

**Issue by TurbanTrap** [aircrack-ng/aircrack-ng#2271]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [x] Defect - Incorrect value displayed/received/stored
- [x] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name:
- OS Version:
- CPU:
- Wireless card and chipset (if relevant):

## Aircrack-ng version

- Version:
- Commit Revision hash:

**Comment by aircrack-ng** [comment]
No details, no PCAP, closing the issue.
