### ISSUE TITLE
PWR  = 1 or -1   with linux  5.15.x

### ISSUE THREAD

**Issue by wifislax-ng** [aircrack-ng/aircrack-ng#2278]
Since upgrade to linux 5.15 i see power 1 or -1 , with linux 5.14 are ok , rebuild not help.

I  test 2 different chipsets , one realtek and other atheros , all two see bad pwr , working as expected on linux 5.14

Probably need include some new call header from linux 5.15.x

Thanks!

**Comment by aircrack-ng** [comment]
There is a known issue with 5.15 and 5.15.1 where radiotap flags are mangled.

More details there: https://lore.kernel.org/all/20211109100203.c61007433ed6.I1dade57aba7de9c4f48d68249adbae62636fd98c@changeid/

But it might be a good idea to have airmon-ng says so when it notices the offending kernels.

**Comment by ZeroChaos-** [comment]
5.15.2 as well

**Comment by gottaeat** [comment]
can confirm that on linux 5.15.0 + 5.15.2 pwr is either 1 or -1, with iwlwifi 6205. clean rebuild with the linux headers and everything updated does not do anything. rolling back to 5.14 fixes the issue.

**edit** problem still persists with 5.15.3.

**Comment by aircrack-ng** [comment]
Fix has been merged in 5.15.5, and airmon-ng is warning when it notices that kernel version (201c8c0)
