### ISSUE TITLE
How do i install aircrack-ng on a Teltonika RUT955

### ISSUE THREAD

**Issue by frank987654** [aircrack-ng/aircrack-ng#2279]
How do i install aircrack-ng on a teltonika rut955.

i have been trying to install this tool via opkg and also cross compiling new firmware but both will no success.

there is always a problem with either openssl  or other libraries

i have tried opkg remove to the library and reinstall but after a reboot it normally breaks the sim connetion or luci (gui web)

if anyone has a idea please help! 

Thanks.

**Comment by aircrack-ng** [comment]
This is not a bug, this is support, so this goes in the [forum](https://forum.aircrack-ng.org).

One thing: when you say there are problems with XYZ, state the exact problem/errors.

**Comment by frank987654** [comment]
it is a problem because it brakes the teltonika/openwrt system when installing
