### ISSUE TITLE
Unable to see Station address (Clients)

### ISSUE THREAD

**Issue by SudoKIngpin** [aircrack-ng/aircrack-ng#2290]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name:
- OS Version:
- CPU:
- Wireless card and chipset (if relevant):

## Aircrack-ng version

- Version:
- Commit Revision hash:

## Related issues

Hi Dev , I am using a Qualcomm Atheros ath5k adapter in-built in my laptop, it supports deauth attack, Soft AP and monitor mode also works perfectly. But whenever I specify a specific bssid and want to monitor it so that I can see the client (station) connected to a WiFi , it doesn't list any client addresses even though clients are connected to WiFi  . It only shows heading station but no client listed it keeps on scanning

**Comment by ZerBea** [comment]
Please also consider to store all undirected PROBEREQUESTs to the dump file. This is not the case if BSSID filter is set.
PROBEREQUEST frames contain useful information: 
https://github.com/evilsocket/pwnagotchi/issues/835#issuecomment-598597214

**Comment by aircrack-ng** [comment]
ath5k is 802.11g card, and current client are likely connecting with 802.11n/ac or even ax, which won't be seen.

Reopen with details after confirming clients are 802.11b/g.

Please fill the requested field correctly next time you file a bug report (issue type, OS information are missing, and the text in the related issue should be under "details").
