### ISSUE TITLE
When I run "sudo airmon-ng start wlan0" nothing happens

### ISSUE THREAD

**Issue by RadoslavL** [aircrack-ng/aircrack-ng#2291]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [x] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Gentoo Linux
- OS Version: 5.10.78-gentoo-dist
- CPU: Intel Core 2 Duo 3.00GHz
- Wireless card and chipset (if relevant):
Model: TP-Link WN722N, Chipset: rtl8188eu
## Aircrack-ng version

- Version: Latest
- Commit Revision hash:

**Comment by gmishealplus** [comment]
Do u try using sudo su. Then your Kali password and then sudo airmon-ng start wlan0

**Comment by RadoslavL** [comment]
Is it the same as running it with "sudo airmon-ng start wlan0"?

**Comment by aircrack-ng** [comment]
This must be discussed in the [forum](https://forum.aircrack-ng.org) first. Reopen this bug if it is confirmed in the forum, with updated information

**Comment by RadoslavL** [comment]
@aircrack-ng I do not think, that my wireless adapter chipset actually supports monitor mode. I tried running "sudo iwconfig wlan0 mode monitor", it returned some errors and nothing changed.
