### ISSUE TITLE
Aircrack-ng is not stopped after password was found (repeat #2269)

### ISSUE THREAD

**Issue by qwertyuiop2k20** [aircrack-ng/aircrack-ng#2293]
Mutex does not work when the program has displayed the password and then continues to search for the password. I noticed that version 1.6 has mutexes in the code and version 1.2 doesn't. As a result, the two versions of the program work differently in Debian. But I can't solve this problem by myself, maybe Debian has mutex problems. Help me, please. Ubuntu hasn't the problem, but i am Debian user, and maybe developers Ubuntu can help. This has happened since version 1.3 when you rewrote the program to include mutexes in it. This bug has not been fixed since then.

System information

    OS Name: Debian 11 Bullseye
    OS Version: 11
    CPU: Dual Core Intel Core i5-3340M
    Wireless card and chipset (if relevant): Qualcomm Atheros AR9485 Wireless Network Adapter (AR5B225)

**Comment by qwertyuiop2k20** [comment]
I really hope you can help me in some way.

**Comment by qwertyuiop2k20** [comment]
Mutexes do not seem to work correctly in the program, or the pthread lib has a problem. I can't say exactly what it is. I tried reinstalling libc6, libc6-dev. The program must stop if the password is found, but it does not stop.

**Comment by jbenden** [comment]
Please try the code on master, it's been fixed for a very long time (around a year).

**Comment by aircrack-ng** [comment]
Reopen this bug with updated information if this still happens with current git master.
