### ISSUE TITLE
ls: cannot access '/sys/class/net': No such file or directory

### ISSUE THREAD

**Issue by Mus90YT** [aircrack-ng/aircrack-ng#2304]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [x] Defect - Crash
- [x] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Kali Linux (running on Termux) 
- OS Version: 2022.1
- CPU: AArch64 Processor rev 2 (aarch64)
- Wireless card and chipset (if relevant): (couldn't find) 

## Aircrack-ng version

- Version: Lastest
- Commit Revision hash:

## Defect
When I run airmon-ng, it says error. 
### Details
┌──(root㉿localhost)-[~]                                                                 └─# airmon-ng
ls: cannot access '/sys/class/net': No such file or directory
PHY     Interface       Driver          Chipset

### How to reproduce the issue
airmon-ng

**Comment by aircrack-ng** [comment]
Without the information requested in the template, we can't debug the issue. Edit his ticket with it.

**Comment by Mus90YT** [comment]
> Without the information requested in the template, we can't debug the issue. Edit his ticket with it.

When I try to enter /sys/class/net directory, I can't, I only can enter /sys directory, /sys/class directory doesn't exist.

**Comment by aircrack-ng** [comment]
That's just what the error says.

Now, could you please provide the information requested in the template? Without it, we don't have enough to understand what happened.

Along with that, provide `lsusb` and `lspci` output.

**Comment by Mus90YT** [comment]
> That's just what the error says.
> 
> Now, could you please provide the information requested in the template? Without it, we don't have enough to understand what happened.
> 
> Along with that, provide `lsusb` and `lspci` output.

Sorry, I'm not very good at English, but, what information is requested in the template?

**Comment by Mus90YT** [comment]
> That's just what the error says.
> 
> Now, could you please provide the information requested in the template? Without it, we don't have enough to understand what happened.
> 
> Along with that, provide `lsusb` and `lspci` output.

# lsusb
unable to initialize libusb: -99

**Comment by aircrack-ng** [comment]
When you open a bug report, it shows a template.

Instead of filling it like you were supposed to, you erased everything.

**Comment by Mus90YT** [comment]
> When you open a bug report, it shows a template.
> 
> Instead of filling it like you were supposed to, you erased everything.

Oh, sorry, so I have to open a new one, not?

**Comment by aircrack-ng** [comment]
No need. you can look at a new one, but put the results here.

**Comment by aircrack-ng** [comment]
See latest comment in #2305.

**Comment by Sachin85y** [comment]
![Uploading Screenshot_2023-07-16-19-23-33-012_com.termux.jpg…]()
