### ISSUE TITLE
ls: cannot access '/sys/class/net': No such file or directo

### ISSUE THREAD

**Issue by Mus90YT** [aircrack-ng/aircrack-ng#2305]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [x] Defect - Crash
- [x] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Kali Linux (running on Termux) 
- OS Version: 2022.1
- CPU: AArch64 Processor rev 2 (aarch64)
- Wireless card and chipset (if relevant): (couldn't find) 

## Aircrack-ng version

- Version: Lastest
- Commit Revision hash:

## Defect
When I run airmon-ng, it says error. 
### Details
┌──(root㉿localhost)-[~]                                                                 └─# airmon-ng
ls: cannot access '/sys/class/net': No such file or directory
PHY     Interface       Driver          Chipset

### How to reproduce the issue
airmon-ng

**Comment by ZeroChaos-** [comment]
I've added a check to help users with this issue in the future, but please make sure /sys is actually mounted.  A lot of stuff will break if it's not.
https://github.com/aircrack-ng/aircrack-ng/commit/2214d6f5278f26e47bdeb6fb07c070ce9c442cd7

**Comment by aircrack-ng** [comment]
@Mus90YT, for next time you open a bug report:
- Ensure to follow the template
- Don't open a new bug when it's the same issue.
- Fill the version: latest doesn't tell us what it is. Are you using a package from a distro, or latest git? If a distro, give us the package version, and if git, the commit.
- Regarding the checkbox: remove the ones not used, as indicated in the template.
- If airmon-ng work, post the name of the card from there, otherwise, either post lspci and lsusb. This can also be found in dmesg.

**Comment by abidmaria** [comment]
Hello guys 
I am running kali on termux [ Android] , I have the same issue ,I am not able ALSO  to configure my wireless adapter ... 
Do you have any idea ? 

Thanks
Best regards

**Comment by ZeroChaos-** [comment]
I checked the code and there was in fact one remaining unprotected call to /sys/class/net, which I have now protected.  That said, if you don't have /sys/class/net, your system is pretty broken, and I have no idea what won't work.  Feel free to report bugs, but they may be closed if there is nothing I can do to get the needed info without /sys/class/net

**Comment by aircrack-ng** [comment]
4df8830bfa5ddc527a64930d9ecdd94ae059b685

**Comment by Peco2324** [comment]
this comes out to me
![Uploading Screenshot_20230508_182207_Termux.jpg…]()
