### ISSUE TITLE
Can't Crack WEP with OSX, Only Kali (Linux)

### ISSUE THREAD

**Issue by ret2c** [aircrack-ng/aircrack-ng#2308]
# Defect Report

## Issue type
- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [x] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: macOS
- OS Version: Monterey 12.3.1
- CPU: x86_64
- Wireless card and chipset (if relevant): N/A

## Aircrack-ng version

- Version: 1.6.0
- Commit Revision hash: N/A

## Defect
I am unable to crack WEP keys when using my macOS system.

### Details
I ran aircrack-ng on my host machine and it failed with the original .pcap IV count of 24,592. When I attempted to use the same .pcap file (checked with md5sum) on my Kali Linux VM, aircrack-ng successfully cracked the WEP key. The main differences between the two terminal outputs was the amount of byte(vote)(s) it was able to produce, as well as the amount of keys it was able to test.

**macOS Output:**
```
                         [00:00:08] Tested 151823 keys (got 24592 IVs)

   KB    depth   byte(vote)
    0   80/ 81   6F(25856) 26(25856) 65(25856) AC(25856) 2F(25856) 48(25600) 89(25600) 
    1   14/  1   E1(28416) 0C(28160) DB(27904) A6(27904) 96(27904) 80(27904) B6(27904) 
    2   15/  2   71(28928) CB(28672) 5F(28416) 28(28416) 02(28416) 49(28160) BF(28160) 
    3    1/  8   7E(30464) 88(29696) 29(29440) D5(29440) 02(29184) E6(29184) 22(29184) 
    4   10/ 16   06(29184) EC(28928) DC(28672) D5(28672) 99(28672) 59(28416) 3F(28416) 

Failed. Next try with 25000 IVs.
```
**Kali Linux VM Output:**
```
                                                     [00:00:00] Tested 503031 keys (got 24592 IVs)

   KB    depth   byte(vote)
    0    1/  4   41(31488) BC(30976) DE(30976) 9E(30208) 22(29952) 3B(29952) 9C(29952) A5(29696) A8(29696) B1(29696) 99(29440) D8(29440) 
    1    0/  1   AD(33792) 27(32000) 92(30208) AE(29952) 7F(29696) 61(29184) 3B(28928) 76(28928) A4(28928) FB(28928) 0B(28672) 62(28672) 
    2    0/  1   10(33792) 47(32768) 1C(31488) 8E(31232) EC(30464) 8B(30208) C7(30208) B5(29952) E2(29952) 65(29440) 6D(29440) A0(29440) 
    3    0/  1   CC(35328) 7E(30464) 88(29696) 29(29440) D5(29440) 02(29184) 22(29184) E6(29184) 11(28928) 12(28928) 2B(28928) 46(28928) 
    4    0/  1   D1(34560) 03(30464) 1F(30464) 12(30208) 3B(29952) B5(29952) 5E(29696) 76(29440) C6(29440) FF(29440) 06(29184) EC(28928) 
    5    0/  1   5E(36608) 26(30720) 76(30464) 27(29952) EF(29952) FB(29952) 2D(29696) B6(29696) 05(29440) 82(29440) 89(29440) 91(29440) 
    6    0/  1   A5(32000) 24(30720) D9(30720) 1B(30464) 36(30208) F0(30208) C6(29952) 16(29696) 1E(29440) 97(29440) A8(29440) B9(29440) 
    7    0/  1   EC(32000) 00(30464) 11(29952) FB(29952) 2E(29696) BA(29696) CD(29696) 2D(29440) 4D(29440) 1C(29184) 5B(29184) 3C(28928) 
    8    0/  1   DC(31744) 93(30720) 61(30464) 9B(30464) 13(30208) 30(30208) A6(29952) 1C(29440) 6F(29440) 45(29184) 8D(29184) C8(29184) 
    9    0/  1   C2(33024) AA(31488) 0A(30720) E5(30720) 3B(30464) 14(29952) 7C(29952) 1A(29696) 6D(29696) 7D(29184) 9F(29184) 62(28928) 
   10    0/  1   8D(30976) 0A(30720) 41(30208) 1F(29952) 0C(29696) 31(29184) 5A(28928) 6E(28928) 81(28928) 37(28672) 57(28672) 74(28672) 
   11    0/  1   37(32000) 2F(31488) B6(30720) 55(30464) D5(30464) 00(29952) C5(29952) 06(29696) 57(29440) 7F(29440) 45(28928) 5F(28928) 
   12    1/  2   CA(30592) 44(30508) 32(29972) D8(29456) BF(29380) 45(29336) ED(29164) 56(29128) 9C(29016) D0(28940) 54(28860) EF(28756) 

             KEY FOUND! [ <IN:SE:RT:KE:YH:ER:E0> ] 
        Decrypted correctly: 100%
```
*Note: This .pcap file is a lab, and does not include sensitive information. This is simply a test file to demonstrate.

### How to reproduce the issue
I simply ran `aircrack-ng <PCAPFile>.pcap` on each of my machines, and got different output between the two of them.

**Comment by Mister-X-** [comment]
Kali isn't really using 1.6, they have a more recent version from git.

Uninstall that version from MacOS, then compile the latest version from git and try again. There are instructions in the `README.md`. If it still fails please upload the PCAP.

**Comment by Mister-X-** [comment]
Considering resolved as no update has been provided. Reopen with version info of the one installed on MacOS if the issue is still present.
