### ISSUE TITLE
Failed initializing wireless card(s): enx00c0caaf5dfe

### ISSUE THREAD

**Issue by Soulsender** [aircrack-ng/aircrack-ng#2309]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [x] Defect - Incorrect value displayed/received/stored
- [x] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Linux Mint
- OS Kernel Version: 5.4.0-109-generic
- CPU: Intel i7-8750H (12) @ 2.200GHz 
- Wireless card and chipset (if relevant): Alfa AWUS036ACH (RTL8812AU chipset)

## Aircrack-ng version

- Version: 1.6

### Details

I get error
```
ioctl(SIOCSIWMODE) failed: Invalid argument
ioctl(SIOCSIWMODE) failed: Invalid argument
Error setting monitor mode on enx00c0caaf5dfe
Failed initializing wireless card(s): enx00c0caaf5dfe
```
when attempting to turn on monitor mode. Adapter has a weird name `enx00c0caaf5dfe` not something like `wlan0`. Connecting to internet through wifi works fine. I have used this same adapter before.

### How to reproduce the issue

Followed [these](https://www.reddit.com/r/Ubuntu/comments/gbb1nw/comment/fp6c9vx/?utm_source=share&utm_medium=web2x&context=3) instructions to install the drivers. Unable to find any similar issues online.

## Related issues

None that I could find.

**Comment by ZeroChaos-** [comment]
your version of aircrack-ng is too old.  That driver is much newer and badly written.  It is supported in the git version of airmon-ng

**Comment by Soulsender** [comment]
I actually had two different drivers installed, so I removed the wrong one and it worked. 

For anyone else having this issue, check [this](https://unix.stackexchange.com/questions/162455/remove-a-manually-installed-driver-wireless-usb) link to remove the wrong drivers.
