### ISSUE TITLE
airodump-ng 1.7 GPS - No Fix

### ISSUE THREAD

**Issue by danf42** [aircrack-ng/aircrack-ng#2311]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [X] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Kali 
- OS Version: 2022.2
- CPU: x86_64
- Wireless card and chipset (if relevant):

## Aircrack-ng version

- Version: Release 1.7
- Commit Revision hash: N/A

## Defect

When using --gpsd option with airodump-ng the GPS status is No Fix.

### Details

Running airodump-ng with the --gpsd option results in the GPS status indicating No Fix.  Reverting back airodump-ng version 1.6, on the same machine obtains a GPS fix and correctly displays the GPS coordinates.  gpsd version is 3.22

### How to reproduce the issue

1. airodump-ng --gpsd wlan1

Observer that the GPS status indicates No Fix.

**Comment by Mister-X-** [comment]
Can you confirm you had a fix in both cases (1.6 and 1.7), outside of airodump-ng?

**Comment by danf42** [comment]
Status from cgps is ` Status:         3D FIX (196 secs)`.  

airodump-ng v1.6 shows the GPS coordinates after a few seconds from starting.  When ctrl-C is used to quit from airodump-ng, the application terminates successfully.  

airodump-ng v1.7 shows `GPS  *** No Fix! ***`.  When ctrl-C is used to quit from airodump-ng the application displays `Quitting...` and just hangs.

**Comment by danf42** [comment]
Notice a difference between 1.6 and 1.7 in function `json_get_value_for_name`.  

Version 1.6 is
```

	if (buffer == NULL || strlen(buffer) == 0 || name == NULL
		|| strlen(name) == 0
		|| value == NULL)
```

Version 1.7 is 
```
	if (buffer == NULL || *buffer == '\0' || name == NULL || *name != '\0'
					  
		|| value == NULL)
```

In v1.7, if I change `*name != '\0'` to `*name == '\0'`, the GPS coordinates are displayed and I can ctrl-C to terminate the application successfully.

**Comment by jbenden** [comment]
Thanks for the fix! :)

**Comment by AmirrezaNasiri** [comment]
Using the latest build (Airodump-ng 1.7 rev 48f1c5a3), the issue has not been migrated by the commit above (https://github.com/aircrack-ng/aircrack-ng/commit/6d4539c1cefc12ce4c37f3a5e2ef694152894393).
Here it is - we have `3D FIX` for a long time in `cgps`, but `airodump-ng` is mostly on `No Fix` state. It only gets the fix once every few seconds:
![Screenshot from 2022-06-24 22-14-09](https://user-images.githubusercontent.com/19557224/175614487-b13c7a95-382f-45a2-b9c6-560b3b672b9c.png)

@jbenden Can you please open the issue again?

**Comment by Mister-X-** [comment]
@AmirrezaNasiri that should be a separate issue. Could you open a new bug report with the info you posted and reference this issue number as well?

**Comment by Slaphead007** [comment]
I am having this problem when running airodump that I get no fix from GPS. I also get the hanging when trying to quit airodump with ctrl+c.
Running Kali on Raspberry Pi, aircrack-ng is latest version. 
If i run cgps I get plenty of GPS locations, running other apps like Kismet also pick up GPS.

**Comment by rodface365** [comment]
> I am having this problem when running airodump that I get no fix from GPS. I also get the hanging when trying to quit airodump with ctrl+c. Running Kali on Raspberry Pi, aircrack-ng is latest version. If i run cgps I get plenty of GPS locations, running other apps like Kismet also pick up GPS.

Same issue as well. There is a posted solution above, however I cannot find what file or line @danf42 is referencing to reproduce and fix myself. I really don't want to revert my aircrack to an outdated version to make airodump record GPSd.

**Comment by ac6de** [comment]
Same issue as above. Can someone pass the file path to the the fix that @danf42 posted?
