### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by trankhanhhiep123** [aircrack-ng/aircrack-ng#2312]
aircrack-ng -h
Could not open '/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so': dlopen failed: library "/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa-arm-neon.so" not found

that's the error i got in termux i cant fix it please help me

**Comment by aircrack-ng** [comment]
This report is not actionable. You need to use the template we provide!
