### ISSUE TITLE
aireplay-ng does not send --deauth command properly on Kali Linux

### ISSUE THREAD

**Issue by zs0c131y** [aircrack-ng/aircrack-ng#2320]
# Defect Report
Hello,
When I use the aireplay-ng command on my Kali Linux terminal while sending `--deauth` packets, it doesn't send specified number of **deauth** requests but gets stuck after sending 3 or 4 requests. 

The command I use are all in this order and I'm pentesting my own WiFi networks. 

1. `sudo su`
2. `airmon-ng check kill`
3. `airmon-ng start wlan0 (after changing to monitor mode)`
4. `airodump-ng wlan0`
5. `airodump-ng --bssid XX:XX -c X -w file wlan0`
6. `aireplay-ng --deauth XX -a XX:XX -c YY:YY wlan0`

At step 6, I'm facing the issue wherein after sending that command, the terminal sends 3 or 4 commands and then does not process the remaining number of the count set. I have not found anything helpful on the web and would be glad if someone could help me. Thanks in advance. I have attached an image of how it appears on my screen. 

![kali](https://user-images.githubusercontent.com/108751847/177378484-c942cb07-cc3b-4531-ba18-c606e2dc754e.png)

## Issue type

Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Kali Linux
- OS Version: Kali-Linux-2022.2-virtualbox-amd64
- CPU: 64-bit
- Wireless card and chipset (if relevant): D-Link DWA-131 Wireless N Nano Adapter (rev.E) v1030.40.128.2019 (latest according to Windows)

## Aircrack-ng version

- Version: 1:1.6+git20210130.91820bc-2
- Commit Revision hash: 

You can reproduce the issue by following the steps I have stated above. This issue happens randomly at times and there is no fixed method to reproduce it.

**Comment by aircrack-ng** [comment]
Windows is irrelevant, so please add driver name from `airmon-ng`.

Next time, please copy and paste content from your screen, it is pure text, so it can be copied easily.

Start again (your six steps), but clear dmesg (`dmesg -c`) after the first step. When done, attach the `dmesg` output here (NOT A SCREENSHOT, attach a text file).

**Comment by zs0c131y** [comment]
**Driver Name:** D-Link Corp. DWA-131 Wireless N Nano Adapter (Rev. E1) [Realtek RTL8192EU] which is shown from `airmon-ng`.

I have attached the dmesg output as a .txt file.
[dmesg.txt](https://github.com/aircrack-ng/aircrack-ng/files/9051173/dmesg.txt)

**Comment by aircrack-ng** [comment]
Driver name is what is under 'Driver' in airmon-ng. What you gave was under 'Chipset'.

Here is an example:
```
~# airmon-ng
PHY	Interface	Driver		Chipset

phy0	wlan0		ath9k_htc	Atheros Communications, Inc. AR9271 802.11n
```
What I need is the third column, the 'Driver', and in this case, it is `ath9k_htc`.

Regarding dmesg, you didn't clear as I asked. Do it again.

And also provide kernel version while we're at it (`uname -a`).

**Comment by zs0c131y** [comment]
The driver is `rtl8xxxu` from the _Driver_ column. 

Kernel Version: `Linux kali 5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux`

I hope this time I did `dmesg -c` right. A text file is attached.
[dmesg.txt](https://github.com/aircrack-ng/aircrack-ng/files/9060127/dmesg.txt)

**Comment by aircrack-ng** [comment]
Update your system: 

```
apt update 
apt dist-upgrade
```

Then reboot and try again.

**Comment by aircrack-ng** [comment]
Update your system: 

```
apt update 
apt dist-upgrade
```

Then reboot and try again.

**Comment by zs0c131y** [comment]
I tried that and rebooted the system thrice, but nothing changed. This problem still persists. Is there anything else that can be done? Thanks!

**Comment by aircrack-ng** [comment]
You failed to follow directions again. I asked to update the system (kernel 5.18.0-kali5-amd64 is the current one, you have 5.16) THEN reboot, you just rebooted. dmesg is again incorrect as it contains the whole thing. It should be small to contain only the interesting details.

I tested with a number of drivers/adapters, and this seems to be an issue with only two of them: rtl8192cu and iwlwifi (plus the rtl8xxxu you mentioned). And there is no indication of any issue in dmesg.

A workaround is to get another adapter for the time being.
