### ISSUE TITLE
Kali Error

### ISSUE THREAD

**Issue by strunz983** [aircrack-ng/aircrack-ng#2322]
Hi my OS is kali linux
Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux
and when i try to install Aircrack-ng 1.7 i got this error message

/autogen.sh                
configure.ac:100: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:100: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:100: the top level
configure.ac:133: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:133: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
build/m4/libgcrypt.m4:30: AM_PATH_LIBGCRYPT is expanded from...
build/m4/ax_lib_gcrypt.m4:50: AX_LIB_GCRYPT is expanded from...
build/m4/aircrack_ng_crypto.m4:40: AIRCRACK_NG_CRYPTO is expanded from...
configure.ac:133: the top level
configure.ac:135: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:135: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_libnl.m4:40: AIRCRACK_NG_LIBNL is expanded from...
configure.ac:135: the top level
configure.ac:144: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:144: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_hwloc.m4:40: AIRCRACK_NG_HWLOC is expanded from...
configure.ac:144: the top level
configure.ac:161: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
build/m4/aircrack_ng_pthread.m4:40: AIRCRACK_NG_PTHREAD is expanded from...
configure.ac:161: the top level
configure.ac:100: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:100: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:100: the top level
configure.ac:133: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:133: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
build/m4/libgcrypt.m4:30: AM_PATH_LIBGCRYPT is expanded from...
build/m4/ax_lib_gcrypt.m4:50: AX_LIB_GCRYPT is expanded from...
build/m4/aircrack_ng_crypto.m4:40: AIRCRACK_NG_CRYPTO is expanded from...
configure.ac:133: the top level
configure.ac:135: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:135: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_libnl.m4:40: AIRCRACK_NG_LIBNL is expanded from...
configure.ac:135: the top level
configure.ac:144: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:144: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_hwloc.m4:40: AIRCRACK_NG_HWLOC is expanded from...
configure.ac:144: the top level
configure.ac:161: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
build/m4/aircrack_ng_pthread.m4:40: AIRCRACK_NG_PTHREAD is expanded from...
configure.ac:161: the top level
configure.ac:100: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:100: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:100: the top level
configure.ac:133: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:133: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
build/m4/libgcrypt.m4:30: AM_PATH_LIBGCRYPT is expanded from...
build/m4/ax_lib_gcrypt.m4:50: AX_LIB_GCRYPT is expanded from...
build/m4/aircrack_ng_crypto.m4:40: AIRCRACK_NG_CRYPTO is expanded from...
configure.ac:133: the top level
configure.ac:135: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:135: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_libnl.m4:40: AIRCRACK_NG_LIBNL is expanded from...
configure.ac:135: the top level
configure.ac:144: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:144: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_hwloc.m4:40: AIRCRACK_NG_HWLOC is expanded from...
configure.ac:144: the top level
configure.ac:161: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
build/m4/aircrack_ng_pthread.m4:40: AIRCRACK_NG_PTHREAD is expanded from...
configure.ac:161: the top level
configure.ac:72: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:115: error: possibly undefined macro: AC_DEFINE
configure:21873: error: possibly undefined macro: AC_MSG_RESULT

And i also try to install from this page   https://www.aircrack-ng.org/doku.php?id=install_aircrack    but i got same error
Thank you 

# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name:
- OS Version:
- CPU:
- Wireless card and chipset (if relevant):

## Aircrack-ng version

- Version:
- Commit Revision hash:

**Comment by jbenden** [comment]
Instead of `autogen.sh`, try using `autoreconf -vif`.

**Comment by strunz983** [comment]
I get error message again

autoreconf -vif
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4/stubs -I build/m4
configure.ac:100: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:100: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:100: the top level
configure.ac:133: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:133: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
build/m4/libgcrypt.m4:30: AM_PATH_LIBGCRYPT is expanded from...
build/m4/ax_lib_gcrypt.m4:50: AX_LIB_GCRYPT is expanded from...
build/m4/aircrack_ng_crypto.m4:40: AIRCRACK_NG_CRYPTO is expanded from...
configure.ac:133: the top level
configure.ac:135: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:135: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_libnl.m4:40: AIRCRACK_NG_LIBNL is expanded from...
configure.ac:135: the top level
configure.ac:144: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:144: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_hwloc.m4:40: AIRCRACK_NG_HWLOC is expanded from...
configure.ac:144: the top level
configure.ac:161: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
build/m4/aircrack_ng_pthread.m4:40: AIRCRACK_NG_PTHREAD is expanded from...
configure.ac:161: the top level
configure.ac:100: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:100: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:100: the top level
configure.ac:133: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:133: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
build/m4/libgcrypt.m4:30: AM_PATH_LIBGCRYPT is expanded from...
build/m4/ax_lib_gcrypt.m4:50: AX_LIB_GCRYPT is expanded from...
build/m4/aircrack_ng_crypto.m4:40: AIRCRACK_NG_CRYPTO is expanded from...
configure.ac:133: the top level
configure.ac:135: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:135: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_libnl.m4:40: AIRCRACK_NG_LIBNL is expanded from...
configure.ac:135: the top level
configure.ac:144: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:144: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_hwloc.m4:40: AIRCRACK_NG_HWLOC is expanded from...
configure.ac:144: the top level
configure.ac:161: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
build/m4/aircrack_ng_pthread.m4:40: AIRCRACK_NG_PTHREAD is expanded from...
configure.ac:161: the top level
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:100: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:100: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:100: the top level
configure.ac:133: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:133: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
build/m4/libgcrypt.m4:30: AM_PATH_LIBGCRYPT is expanded from...
build/m4/ax_lib_gcrypt.m4:50: AX_LIB_GCRYPT is expanded from...
build/m4/aircrack_ng_crypto.m4:40: AIRCRACK_NG_CRYPTO is expanded from...
configure.ac:133: the top level
configure.ac:135: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:135: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_libnl.m4:40: AIRCRACK_NG_LIBNL is expanded from...
configure.ac:135: the top level
configure.ac:144: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:144: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
build/m4/aircrack_ng_hwloc.m4:40: AIRCRACK_NG_HWLOC is expanded from...
configure.ac:144: the top level
configure.ac:161: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
build/m4/aircrack_ng_pthread.m4:40: AIRCRACK_NG_PTHREAD is expanded from...
configure.ac:161: the top level
configure.ac:72: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:115: error: possibly undefined macro: AC_DEFINE
configure:10178: error: possibly undefined macro: AC_MSG_RESULT
autoreconf: error: /usr/bin/autoconf failed with exit status: 1

**Comment by jbenden** [comment]
Thanks! There are some known issues with autoconf 2.71 or later, as described in the issue report for Clear Linux #2229. Since these are actually the same, I am closing this bug report.
