### ISSUE TITLE
1.7 fails to build on s390x (and other big endian archs)

### ISSUE THREAD

**Issue by samueloph** [aircrack-ng/aircrack-ng#2324]
# Defect Report

## Issue type

- [x] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Debian
- OS Version: Unstable
- CPU: s390x
- Wireless card and chipset (if relevant):

## Aircrack-ng version

- Version: 1.7
- Commit Revision hash:

## Defect

Aircrack 1.7 fails to build from source on S390X in the Debian build fleet.
I think the issue is unlikely to be in the packaging side.

### Details

Build log is available here:
https://buildd.debian.org/status/fetch.php?pkg=aircrack-ng&arch=s390x&ver=1%3A1.7-2&stamp=1658152158&raw=0

The failure happens when running the tests:
```
=========================================
   aircrack-ng 1.7.0: ./test-suite.log
=========================================

# TOTAL: 45
# PASS:  36
# SKIP:  0
# XFAIL: 0
# FAIL:  9
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test-aircrack-ng-0001.sh
===================================

Specifying more processes (4) than available CPUs (2) would cause performance degradation.
Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0001.sh (exit status: 1)

FAIL: test/test-aircrack-ng-0003.sh
===================================

Specifying more processes (4) than available CPUs (2) would cause performance degradation.
Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0003.sh (exit status: 1)

FAIL: test/test-aircrack-ng-0004.sh
===================================

Specifying more processes (4) than available CPUs (2) would cause performance degradation.
Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0004.sh (exit status: 1)

FAIL: test/test-aircrack-ng-0008.sh
===================================

Specifying more processes (4) than available CPUs (2) would cause performance degradation.
Resetting EAPOL Handshake decoder state.
Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0008.sh (exit status: 1)

FAIL: test/test-aircrack-ng-0009.sh
===================================

Specifying more processes (4) than available CPUs (2) would cause performance degradation.
Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0009.sh (exit status: 1)

FAIL: test/test-aircrack-ng-0016.sh
===================================

Specifying more processes (4) than available CPUs (2) would cause performance degradation.
Reading packets, please wait...
Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0016.sh (exit status: 134)

FAIL: test/test-aircrack-ng-0017.sh
===================================

Specifying more processes (4) than available CPUs (2) would cause performance degradation.
Reading packets, please wait...
Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0017.sh (exit status: 134)

FAIL: test/test-aircrack-ng-0021.sh
===================================

Invariant Failed: now_us > 0
Aborted
FAIL test/test-aircrack-ng-0021.sh (exit status: 1)

FAIL: test/test-airolib-ng-0001.sh
==================================

Database </tmp/acng.JShB> does not already exist, creating it...
Database </tmp/acng.JShB> successfully created
Reading file...
Writing...
Done.
Reading file...
1000 lines read, 919 invalid lines ignored.
2000 lines read, 1814 invalid lines ignored.
Writing...
Done.

Computed 233 PMK in 1 seconds (233 PMK/s, 0 in buffer)
Invariant Failed: now_us > 0
Aborted
FAIL test/test-airolib-ng-0001.sh (exit status: 1)

============================================================================
Testsuite summary for aircrack-ng 1.7.0
============================================================================
# TOTAL: 45
# PASS:  36
# SKIP:  0
# XFAIL: 0
# FAIL:  9
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://forum.aircrack-ng.org
============================================================================
```

### How to reproduce the issue

Build aircrack 1.7 on a s390x machine

## Related issues

Just for reference, here is the build result for all the archs on Debian:
https://buildd.debian.org/status/package.php?p=aircrack-ng

edit -
The build is also failing on other big endian architectures, so the failures are likely to be triggered by this,

**Comment by jbenden** [comment]
Would you mind trying the patch below? Thanks!

[pr2324.patch.txt](https://github.com/aircrack-ng/aircrack-ng/files/9627716/pr2324.patch.txt)

**Comment by Mister-X-** [comment]
I actually tested 1.7, ba8a93b, and #2326, they all build fine on MIPS BE and pass tests successfully without any patching. However, that is on an older Debian version, Buster.

So, that may be s390x specific and/or Bullseye

**Comment by samueloph** [comment]
The proposed patch [pr2324.patch.txt](https://github.com/aircrack-ng/aircrack-ng/files/9627716/pr2324.patch.txt) fixes the issue, as seen on:
https://buildd.debian.org/status/fetch.php?pkg=aircrack-ng&arch=s390x&ver=1%3A1.7-4&stamp=1664002637&raw=0

I assume the issue is not exactly architecture related, but rather related to the amount of CPUs the machine has (maybe a combination of that and the arch), judging by the patch.

I'll go ahead and upload 1.7 with that patch included for Debian and I'm gonna leave the issue open as I assume you're gonna close it after merging the fix in the repo.

Thank you very much @jbenden and @Mister-X-.
