### ISSUE TITLE
airodump-ng and traffic capturing

### ISSUE THREAD

**Issue by ChillVibesMushroom** [aircrack-ng/aircrack-ng#2327]
# Defect Report
Not a defect just a question 
## Issue type
I'm capturing traffic on a 5Ghz OPN Network and pulling information from my Android device but all traffic is coming in as TLS 1 1.2 1.3 and typically I'll get DNS traffic and what not but this time I'm having to rely on the client hello from the TLS packets

Not any defects I believe
- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Dragon OS Focal 🐉
- OS Version: latest
- CPU: 
- Wireless card and chipset (if relevant):
Alfa 
## Aircrack-ng version
Pre installed latest
- Version:
- Commit Revision hash:

### Details
I noticed that aireplay-ng doesn't kick the client off when targeting the device but will kick the client off when targeting the router itself

WPA2 router 

Typically in Wireshark I type DNS MDNS HTTP and get the wanted traffic

### How to reproduce the issue
sudo airmon-ng start wlan0

sudo airodump-ng wlan0mon --band a

Selects desired network

Runs Wireshark

Connects my phone

Packet injection works

On the protected network 5G I can gather info using the AP password

## Related issues

I've been looking into ways to decrypt TLS

I found one method where we create a keylog file and from the same shell run Firefox but I need something OTA and I was told it's possible just not how

I came here because I know you can help

**Comment by ChillVibesMushroom** [comment]
I have a 🍍 I was thinking maybe just kicking them off of the OPN and forcing a reconnect to myself while running tcpdump in order to capture traffic if aircrack-ng support can't help me with the issue but I always will and do appreciate tools from great men and women like yourselves

**Comment by Mister-X-** [comment]
As mentioned in the multi choice when opening a new issue, questions are to be asked in the forum (as they aren't issues).

You can also start a thread, in the "discussion" tab here, which is meant for questions.
