### ISSUE TITLE
Integration testing FAIL: test/test-airbase-ng-0001.sh

### ISSUE THREAD

**Issue by NightFlexer** [aircrack-ng/aircrack-ng#2331]
I run: make integration.
And I get this:
FAIL: test/test-airbase-ng-0001.sh
FAIL: test/test-airbase-ng-0002.sh
...
# TOTAL: 17
# PASS:  14
# SKIP:  1
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
How can this be fixed?

**Comment by aircrack-ng** [comment]
If you fill the ticket properly instead of deleting everything like you did, this will be fixed. Reopen after updating with the proper information.
