### ISSUE TITLE
Air'O'Script-NG: Failed to open '/tmp/tmp.$ID/$MAC-$NO.cap' (2): No such file or directory

### ISSUE THREAD

**Issue by bphd** [aircrack-ng/aircrack-ng#2332]
# Defect Report

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [X] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: A
- OS Version: L
- CPU: I
- Wireless card and chipset (if relevant):

## Aircrack-ng version

- Version: L
- Commit Revision hash:

### How to reproduce the issue

| 6) | Autopawn - Automatic cracking       |
[+] Attack 0. Using wep_attacks_fakeinteractive in $MAC

**Comment by Mister-X-** [comment]
Reopen this ticket with system information, aircrack-ng version, how to reproduce the issue filled correctly.

Note: You must be using current git, as stated by the ticket
