### ISSUE TITLE
hostapd-2.10-wpe.patch not installing (make install) on Raspbian Buster 

### ISSUE THREAD

**Issue by Stefan2483** [aircrack-ng/aircrack-ng#2334]
# Defect Report

## Issue type

- [x] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [ ] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- OS Name: Raspbian
- OS Version: Buster
- CPU: armv7I
- Wireless card and chipset (if relevant): N/A

## Aircrack-ng version

- Version: 2.10
- Commit Revision hash: 

### Details
Issue is that `sudo make install` fails after you apply the wpe patch on version 2.10:

```
install -D hostapd-wpe /usr/local/bin//hostapd-wpe
install: cannot stat 'hostapd-wpe': No such file or directory
make: *** [Makefile:1277: /usr/local/bin//hostapd-wpe] Error 1
```

To reproduce the issue on raspberry pi 4 with Raspbian Buster:
```
wget https://raw.githubusercontent.com/aircrack-ng/aircrack-ng/master/patches/wpe/hostapd-wpe/hostapd-2.10-wpe.patch
wget https://w1.fi/releases/hostapd-2.10.tar.gz
tar -zxf hostapd-2.10.tar.gz
cd hostapd-2.10
patch -p1 < ../hostapd-2.10-wpe.patch
cd hostapd
```

Then:

```
make
sudo make install
```

Error is:
```
LD  hostapd-wpe
install -D hostapd-wpe /usr/local/bin//hostapd-wpe
install: cannot stat 'hostapd-wpe': No such file or directory
make: *** [Makefile:1277: /usr/local/bin//hostapd-wpe] Error 1
```

Edit by Mister-X-: added backticks for code

**Comment by Mister-X-** [comment]
A few things:
- Raspbian Buster is old, I'd recommend switching to Bullseye
- The instructions you have are outdated. See https://github.com/aircrack-ng/aircrack-ng/tree/master/patches/wpe/hostapd-wpe
- Please use the backticks for anything that is in the terminal.

However, using instructions mentioned above, the issue is confirmed on x86 64 bit.
