### ISSUE TITLE
autoconf failed with exit status: 1

### ISSUE THREAD

**Issue by AlphaOneWhiskeyFour** [aircrack-ng/aircrack-ng#2339]

**Comment by aircrack-ng** [comment]
Closing this. Reopen after filling the bug report as required. This doesn't have enough info, so this isn't actionable.

**Comment by xxalfa** [comment]
Not all sources were entered in the `/etc/apt/sources.list` file. Now I finally managed to install over `apt-get install aircrack-ng`. 
```
add-apt-repository main
add-apt-repository universe
add-apt-repository restricted
add-apt-repository multiverse
```
Thank you for your help, continued success.
