### ISSUE TITLE
Monitor mode issue Kali 2022.3 AWUS 1900 long range adapter

### ISSUE THREAD

**Issue by pranavkinicok** [aircrack-ng/aircrack-ng#2340]
I'm using the latest version of Kali Linux that is 2022.3 and the OS is perfectly updated and upgraded also the driver is also installed as recommended from the official site. The hardware that I'm using is AWUS1900 with four antennas attached and I believe this is the high end version of Adapters in ALPHA network. it is actually supposed to show wlan0 changed to mon0 but it simply showing monitor mode enabled so I used the same name that is wlan0 and tried to collect the packets using the command sudo airmon-ng wlan0.

![image](https://user-images.githubusercontent.com/59532968/197355507-24ca6ced-aab4-46ad-bbd3-b0bb70eda2fd.png)

several minutes elapsed not even single packet is shown.

![image](https://user-images.githubusercontent.com/59532968/197355845-ad64c94e-fb35-4663-baa5-957ae8bece98.png)

**Comment by aircrack-ng** [comment]
The interface name doesn't change, it stays `wlan0` in with this driver (and rtl8812au)

Wrong repo.
