### ISSUE TITLE
root@kali:~# airmon-ng

### ISSUE THREAD

**Issue by iranzithierry** [aircrack-ng/aircrack-ng#2344]
root@kali:~# airmon-ng 

PHY	Interface	Driver		Chipset

phy0	wlan0		88XXau		Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac

root@kali:~# airmon-ng start wlan0mon

Found 3 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

  PID Name
  506 NetworkManager
  591 wpa_supplicant
  794 dhclient

PHY	Interface	Driver		Chipset

phy0	wlan0		88XXau		Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac

root@kali:~# airodump-ng wlan0mon
Interface wlan0mon: 
ioctl(SIOCGIFINDEX) failed: No such device
Failed initializing wireless card(s): wlan0mon

whats the problem i downloaded the driver but still its not working on monitor mode

_Originally posted by @suhaib124 in https://github.com/aircrack-ng/aircrack-ng/issues/1911#issuecomment-488379007_

**Comment by Mister-X-** [comment]
There are several issues with this ticket:
1. You didn't follow the guidelines provided for the bug report.
2. This is not a bug report, this is support, and that is done in the [forum](https://forum.aircrack-ng.org).
3. Wrong repository: see [rtl8814au](https://github.com/aircrack-ng/rtl8814au)
4. It's `airmon-ng start wlan0`, not `airmon-ng start wlan0mon`
5. It's `airodump-ng wlan0` (Just FYI, this driver and another don't get `mon` added to the interface name) and not `airodump-ng wlan0mon`. Please read the error message, it says 'No such device'.
7. As an advice, you should kill the network manager prior to putting the wireless card in monitor mode.
