### ISSUE TITLE
Weird URL on www.aircrack-ng.org

### ISSUE THREAD

**Issue by etiennemlb** [aircrack-ng/aircrack-ng#2345]
# Defect Report ?

NOTE: This concerns the www.aircrack-ng.org website and I didn't post on the forum about this "issue".

## Issue type

- [ ] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed
- [ ] Defect - Crash
- [ ] Defect - Incorrect value displayed/received/stored
- [x] Defect - Unexpected behavior (obvious or confirmed in the forum)

## System information

- Irrelevant ? This about what the server's response.

### Details

On this page: https://www.aircrack-ng.org/doku.php?id=aircrack-ng

![unexpected](https://user-images.githubusercontent.com/72296335/204102568-5ef06327-4384-4a25-9c9b-341d9b632600.png)
![unexpected2](https://user-images.githubusercontent.com/72296335/204102583-4b3e6d94-b2fa-4440-b398-7b6d64efe804.png)

### How to reproduce the issue

Go to https://www.aircrack-ng.org/doku.php?id=aircrack-ng .

## Related issues

`-`

**Comment by aircrack-ng** [comment]
It was a configuration issue. Dokuwiki is supposed to autodetect the path on the server, but it seems to have failed. Setting 'basedir' to '/' seems to fix it.
