### ISSUE TITLE
OpenSSL Handshake Failure during download of aircrack-ng-1.7.tar.gz

### ISSUE THREAD

**Issue by StasLambant** [aircrack-ng/aircrack-ng#2363]
When I run _wget https://download.aircrack-ng.org/aircrack-ng-1.7.tar.gz_ I get the following error:

_Connecting to download.aircrack-ng.org (download.aircrack-ng.org)|81.130.111.239|:443... connected.
OpenSSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
Unable to establish SSL connection._

Accessing the link directly via web browser (latest version of Chrome), I get an error: _This site can’t provide a secure connection_

**Comment by Mister-X-** [comment]
We don't control that server's configuration, it's a shared hosting.

Thus, it's probably an issue on your side as Chromium 107.0.5304.121 works just fine, and my guess is your distribution either has a very strict configuration, or it's really old

Could you give me the version of chrome, wget, and openssl that you're using.

**Comment by jbenden** [comment]
Try running:

```
$ printf "HEAD /aircrack-ng-1.7.tar.gz HTTP/1.1\nServer: download.aircrack-ng.org\n\n" | openssl s_client -verify 3 -connect download.aircrack-ng.org:443 -debug -strict -ign_eof
```

It should print out a bunch of useful data which could be cleaned and posted here for debugging.

Another possible is either bad certificate or a browser compiled without strong encryption support, which is typical outside of the USA.

**Comment by StasLambant** [comment]
> We don't control that server's configuration, it's a shared hosting.
> 
> Thus, it's probably an issue on your side as Chromium 107.0.5304.121 works just fine, and my guess is your distribution either has a very strict configuration, or it's really old
> 
> Could you give me the version of chrome, wget, and openssl that you're using.

Chrome version 108.0.5359.124
OpenSSL version : LibreSSL 2.8.3
wget version: GNU Wget 1.21.3 built on darwin20.6.0.

**Comment by StasLambant** [comment]
> Try running:
> 
> ```
> $ printf "HEAD /aircrack-ng-1.7.tar.gz HTTP/1.1\nServer: download.aircrack-ng.org\n\n" | openssl s_client -verify 3 -connect download.aircrack-ng.org:443 -debug -strict -ign_eof
> ```
> 
> It should print out a bunch of useful data which could be cleaned and posted here for debugging.
> 
> Another possible is either bad certificate or a browser compiled without strong encryption support, which is typical outside of the USA.

I am based in the UK but I'm using a the latest version os Chrome so not sure what level of encryption support it has.
I ran it without the -strict parameter as it was returning an unknown option error.

Here's the result with some data cleaned up. Any help with this would be appreciated. Thanks:

_verify depth is 3
CONNECTED(00000005)
...
read/write data removed
...
4525534892:error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure:/System/Volumes/Data/SWE/macOS/BuildRoots/37599d3d49/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.4/libressl-2.8/ssl/ssl_pkt.c:1200:SSL alert number 40
4525534892:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/System/Volumes/Data/SWE/macOS/BuildRoots/37599d3d49/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.4/libressl-2.8/ssl/ssl_pkt.c:585:

no peer certificate available

No client certificate CA names sent

SSL handshake has read 7 bytes and written 0 bytes

New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1672675740
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)_

**Comment by jbenden** [comment]
I think it is missing CA certificates?

**Comment by StasLambant** [comment]
> I think it is missing CA certificates?

not sure tbh.

When I access the link directly from Chrome, the detailed error is: _The client and server don't support a common SSL protocol version or cipher suite._, but I've checked and both my browser and the server support TLS 1.3 and 1.2 and have several common supported cypher suites.

In any case, I was able to download it from the git repository and all seems to work now, albeit ldconfig returns _command not found_
