### ISSUE TITLE
Update the bug reporting URL

### ISSUE THREAD

**Issue by Mister-X-** [aircrack-ng/aircrack-ng#2375]
# Description

Update the bug reporting URL from the forum to https://github.com/aircrack-ng/aircrack-ng/issues (the forum has been moved to GitHub discussions)

**Comment by gemesa** [comment]
I think this can be closed because as I can see the related references are updated:
- https://github.com/aircrack-ng/aircrack-ng/commit/f8e3bbcbd38a88dbf90e581c9b87a5d917afbf09
- https://www.aircrack-ng.org/support.html
- https://www.aircrack-ng.org/doku.php?id=bugs
