### ISSUE TITLE
Fix MacOS GitHub action

### ISSUE THREAD

**Issue by Mister-X-** [aircrack-ng/aircrack-ng#2376]
# Defect Report

## Issue type

- [x] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed

## System information

- OS Name: MacOS
- CPU: i386

## Aircrack-ng version

- Version: 1.7
- Commit Revision hash:  e781834

## Airmon-ng debug information

N/A

### Details

The action fails with gcc-9 and gcc-10.

At least with gcc-10, we can see the error `ccache: error: Could not find compiler "gcc-10" in PATH` in the logs. See https://github.com/aircrack-ng/aircrack-ng/actions/runs/3850459568/jobs/6560625246 for example

### How to reproduce the issue

Commit to the repository

## Related issues

N/A

**Comment by Mister-X-** [comment]
Details on the MacOS runner: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

We may want to update it, and use more recent versions of clang and gcc.

**Comment by Mister-X-** [comment]
d61d603a2160f80bf411cbc63b3031c9b0ccac2f

**Comment by gemesa** [comment]
Linked PR fixes both `gcc` and `clang` related issues in the MacOs workflow.
