### ISSUE TITLE
A GUI for linux

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#238]
**Reported by itek on 14 Jun 2007 09:51 UTC**

why not a GUI for linux?

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

This would be awesome

**Comment by aircrack-ng** [comment]
**Comment by misterx on 14 Jun 2007 09:51 UTC**

It will be for later.

**Comment by aircrack-ng** [comment]
**Comment by Sh on 14 Jun 2007 09:51 UTC**

I hope not i will send you something to test next week..........
Best Regards

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

just because it's not necessary ;)
nobody needs it and it would only be support wanted cause more noobs would like to use aircrack

**Comment by aircrack-ng** [comment]
**Comment by Hussain on 14 Jun 2007 09:51 UTC**

Yeah.. GUI Please

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

@10/12/07 21:59:11 changed by anonymous

yeah, you need to be hardcore command line guru to use a handy tool. Stupid as hell!

**Comment by aircrack-ng** [comment]
**Comment by marco punto on 14 Jun 2007 09:51 UTC**

also a noob can use aircrack suite in CLI with all that supports and guides out there.
A GUI will simply speed up the process.
A GUI is useful stop

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

Dude ur a tool, just cuz u know a few command lines u think u rule the world. I know probably a few more than you and im all up for it

**Comment by aircrack-ng** [comment]
**Comment by exile on 14 Jun 2007 09:51 UTC**

Replying to [anonymous](comment:8):
> Dude ur a tool, just cuz u know a few command lines u think u rule the world. I know probably a few more than you and im all up for it
^ And here we are presented with an example of one of such said "noobs". Look at that spelling!

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

I recon a GUI would be useful for speeding things up.

**Comment by aircrack-ng** [comment]
**Modified by misterx on 14 Jun 2007 09:51 UTC**

**Comment by aircrack-ng** [comment]
**Comment by ZeroCool on 14 Jun 2007 09:51 UTC**

A GUI would speed things up ... and you know every second counts when you're hacking a Gibson and the man's bearing down on you're ass !

**Comment by aircrack-ng** [comment]
**Comment by Kuba on 14 Jun 2007 09:51 UTC**

Yes, I opt for GUI as well, great idea.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 14 Jun 2007 09:51 UTC**

http://techbase.kde.org/Development/Tutorials/Shell_Scripting_with_KDE_Dialogs

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

GUI would speed up the proccess and reduce errors. sounds like a brilliant idea...

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

sooooo wanting this!

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

http://sourceforge.net/projects/qaircrack-ng/

**Comment by aircrack-ng** [comment]
**Comment by end of king on 14 Jun 2007 09:51 UTC**

I am writing java gui for aircrack-ng

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 14 Jun 2007 09:51 UTC**

I'm gonna make a gui for aircrack-ng in java. I'll post a mediafire link once I get it done.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 14 Jun 2007 09:51 UTC**

There are a lot of them available, we just need to document output files and formats.

**Comment by t-gitt** [comment]
I tried doing a python gtk3 ui for it, feel free to contribute.
https://github.com/tqk-gh/aircrack-ng-gui

**Comment by kimocoder** [comment]
Great. I'll follow it for fun :+1: thanks

**Comment by aircrack-ng** [comment]
@tqk-gh You should post it in the forum too
