### ISSUE TITLE
Increase buildbot timeout for armel builder

### ISSUE THREAD

**Issue by Mister-X-** [aircrack-ng/aircrack-ng#2389]
# Description

armel buildbot [fails due to timeout](https://buildbot.aircrack-ng.org/#/builders/8/builds/1262/steps/5/logs/stdio):

```
command timed out: 1200 seconds without output running [b'make', b'-j', b'1', b'check'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=1363.752687
```

I'm assuming it's just a matter of updating the timeout. Unless it is freezing completely (then maybe we can add a cooler/update the heatsink)

**Comment by jbenden** [comment]
It actually because the unit tests timeout running the compatibility code of `libce-wpa`. I've already added some env var stuff to drop tests out, but really this machine just can't handle it, and I'm in the wrong place in USA for cool machine operation. :smiley:

**Comment by Mister-X-** [comment]
So I guess we can add an active cooler on it, which hopefully would help.

**Comment by Mister-X-** [comment]
This has become irrelevant since we build docker containers for this cpu arch
