### ISSUE TITLE
docker image not finding the manifest

### ISSUE THREAD

**Issue by TomK32** [aircrack-ng/aircrack-ng#2424]
# Defect Report

## Issue type

- [ ] Defect - Unexpected behavior (obvious or confirmed in the GitHub Discussions)

## System information

- Docker version 20.10 (latest on manjaro)

### Details

I did try using aircrack via the docker image on docker hub but it failed with this error message:

    Error response from daemon: manifest for aircrackng/release:latest not found: manifest unknown: manifest unknown

### How to reproduce the issue

   docker pull aircrackng/release

**Comment by Mister-X-** [comment]
It was created after 1.7 release, so there is no release yet in there. Next one hitting that repository will be 1.8.
