### ISSUE TITLE
Support passing multiple --encrypt filters

### ISSUE THREAD

**Issue by drws** [aircrack-ng/aircrack-ng#2437]
# Description

Currently only a single `--encrypt` argument can be passed to filter out a single encryption type. This is a feature request to implement support for passing multiple `--encrypt` filters, like #1940 did for `--bssid`.

**Comment by gemesa** [comment]
> Currently only a single `--encrypt` argument can be passed

Not true, see #2438

**Comment by Mister-X-** [comment]
It just wasn't documented.
