### ISSUE TITLE
Support passing multiple --essid filters

### ISSUE THREAD

**Issue by drws** [aircrack-ng/aircrack-ng#2441]
# Description

Currently only a single `--essid` argument can be passed to `airodump-ng`, in contrast to multiple `--bssid` introduced in #2432. This is a feature request to implement support for passing multiple `--essid` filters as well. This was also discussed in (and spun off) #1940.

**Comment by gemesa** [comment]
It is also available similarly to `--encrypt` (#2437), just not documented in `airodump-ng --help`.
