### ISSUE TITLE
Cannot set color on an AP when 'Color on'

### ISSUE THREAD

**Issue by Mister-X-** [aircrack-ng/aircrack-ng#2459]
# Defect Report

## Issue type

- [x] Defect - Unexpected behavior (obvious or confirmed in the GitHub Discussions)

## System information

- OS Name: Ubuntu
- OS Version: 22.04
- Kernel version: 5.19.0-32-generic
- CPU: x86 64
- Wireless card and chipset (if relevant): N/A

## Aircrack-ng version

- Version: 1.7
- Commit Revision hash: d34de64e6a26e583daafee7e303c89152666072b

### Details

There seems to be a weird behavior if color is on ('p'), and in interactive mode (using tab). When trying to set a color to an AP with 'm', it quickly flashes the first color (red) then revert back to grey. When "Color is off", this isn't a problem.

### How to reproduce the issue

1. Run airodump-ng: `airodump-ng wlan0mon`
2. Enable color with 'p'
3. Use tab and go up/down
4. Use 'm' to go through the colors

**Comment by gemesa** [comment]
I checked the 1.7 release version of `airodump-ng`:

1. run `airodump-ng wlan0mon`
2. use tab, arrow keys and 'm' to mark some APs
3. press 'o' to enable color --> suddenly all of the previously added markers are cleared

So conclusion: the markers are cleared if we press 'o' to enable colors.

Checked also the current implementation (https://github.com/aircrack-ng/aircrack-ng/commit/d34de64e6a26e583daafee7e303c89152666072b):

1. run `airodump-ng wlan0mon`
2. use tab, arrow keys and 'm' to mark some APs
3. press 'o' to enable color --> suddenly all of the previously added markers are cleared

So the behavior is the same so far but there is a big difference introduced in #2435 and #2445: once you hit 'o' to enable colors, the `color_on()` function keeps getting called constantly (in 1.7 it was called only once which caused #2109). This means the markers are cleared as soon as you put them if color is enabled with 'o'.

So I think we need to rework `color_on()` not to touch the marked APs somehow, or revert #2435 and #2445 and accept that we need to press 'o' again to color the newly added APs and stations as well.

**Comment by gemesa** [comment]
> So conclusion: the markers are cleared if we press 'o' to enable colors.

This is because `color_off()` is called at the beginning of `color_on()` for some reason:
```
static void color_on(void)
{
	struct AP_info * ap_cur;
	struct ST_info * st_cur;
	int color = 2;
	int i;
	int match;

	color_off();
...
}
```

I removed the `color_off()` call and it seems to working fine now, so this is a possible fix but needs further testing.
