### ISSUE TITLE
macOS CI failing

### ISSUE THREAD

**Issue by gemesa** [aircrack-ng/aircrack-ng#2465]
# Defect Report

## Issue type

- [X] Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed

## System information

- OS Name: macOS
- CPU: i386

## Aircrack-ng version

- Version: 1.7
- Commit Revision hash: https://github.com/aircrack-ng/aircrack-ng/commit/d0c32c8bb8bc571d542f3f31d92edd60a29d7da1

## Airmon-ng debug information

N/A

### Details

The action fails with `clang`, see [this job](https://github.com/aircrack-ng/aircrack-ng/actions/runs/4240756537/jobs/7370146024) for example:

```
   ../test/unit/test-circular-buffer.c:102:2: error: passing 'uint8_t[17]' to parameter of type 'const char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Werror,-Wpointer-sign]
          assert_string_equal("a1234567b1234567", buffer);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/local/include/cmocka.h:1363:31: note: expanded from macro 'assert_string_equal'
      _assert_string_equal((a), (b), __FILE__, __LINE__)
                                ^~~
  /usr/local/include/cmocka.h:2352:68: note: passing argument to parameter 'b' here
  void _assert_string_equal(const char * const a, const char * const b,
                                                                     ^
  1 error generated.
  make[2]: *** [test/unit/circular_buffer-test-circular-buffer.o] Error 1
```

### How to reproduce the issue

Commit to the repository.

## Related issues

N/A

**Comment by gemesa** [comment]
Looks like this is fixed, see [this job](https://github.com/aircrack-ng/aircrack-ng/actions/runs/4246882391/jobs/7384254381) and https://github.com/aircrack-ng/aircrack-ng/commit/d0c32c8bb8bc571d542f3f31d92edd60a29d7da1.

**Comment by Mister-X-** [comment]
Unless I'm missing something, that doesn't make any sense.

**Comment by gemesa** [comment]
Yea it is weird to me also. Looks like it is failing when triggered by a PR and it passes when triggered by a push to master.

**Comment by Mister-X-** [comment]
Let's keep this open then.

**Comment by gemesa** [comment]
I will reopen it if it fails on my next PR.
