### ISSUE TITLE
buildbot/aircrack-ng-fbsd-13 is still being triggered

### ISSUE THREAD

**Issue by gemesa** [aircrack-ng/aircrack-ng#2481]
# Defect Report

## Issue type

- [X] Defect - Unexpected behavior (obvious or confirmed in the GitHub Discussions)

## System information

N/A

## Aircrack-ng version

- Version: 1.7
- Commit Revision hash: https://github.com/aircrack-ng/aircrack-ng/commit/ceac6585f65e57ed3d063af4412f4749f882d398

## Airmon-ng debug information

N/A

### Details

`buildbot/aircrack-ng-fbsd-13` is still being triggered by push to master but buildbots have been replaced with GH actions (https://github.com/aircrack-ng/aircrack-ng/commit/7f833e548cf077e4bc1ee152ae4b143dcdb9748a). The FreeBSD CI action [uses the latest FreeBSD (13.1)](https://github.com/vmactions/freebsd-vm).

![image](https://user-images.githubusercontent.com/59890178/221942835-bb49b91e-1fb9-439f-a8b4-777ff381508a.png)

### How to reproduce the issue

Push to master.

## Related issues

N/A

**Comment by Mister-X-** [comment]
That one has been decommissioned as well.
