### ISSUE TITLE
Airmon-ng not work on my custmon kernel(4.4.205) Android

### ISSUE THREAD

**Issue by gyhxrr31** [aircrack-ng/aircrack-ng#2484]
airmon-ng wlan2 start
/sys is not mounted, you can probably mount it with: mount -t sysfs sysfs /sys
This program cannot continue without a working sysfs.

**Comment by Mister-X-** [comment]
I'll close this as it's missing all the information we request from any bug report, which makes it unactionable from our side. Once you've adjusted it, reopen the ticket.

**Comment by Alaahardav** [comment]
Someone help me please...
Airmon-ng cannot continue without working sysfs; what is that mean and what the solution for this issue
