### ISSUE TITLE
packagecloud.io link not working

### ISSUE THREAD

**Issue by slfpercy** [aircrack-ng/aircrack-ng#2485]
Hello, the packagecloud.io link to download the deb package isn't working anymore, someone knows what happened to the link? Thanks

**Comment by Mister-X-** [comment]
Yes, we stopped providing binaries.

**Comment by slfpercy** [comment]
Is there a way I could get the binary aircrack-ng_1.7-1_amd64.deb or a point of contact to get that binary?

**Comment by Mister-X-** [comment]
The repositories were deleted so that's not possible.
