### ISSUE TITLE
Airmon-ng not working on my kernel with support all function for Nethunter

### ISSUE THREAD

**Issue by gyhxrr31** [aircrack-ng/aircrack-ng#2487]
I am getting an error with airmon-ng on my redmi note 7 device with custom kernel and rom. And the error is only on my kernel, which I myself compiled from source. This error ONLY occurs on my kernel. When I try to mount, it says that the partition is already mounted:###  **`mount: /sys: sysfs already mounted or mount point busy. call. dmesg(1) may have more information after failed mount system.`** I've already tried a lot, but I don't know what to do anymore. My wifi card is support monitor, but problem in my kernel...

ERROR: 
airmon-ng wlan2 start
/sys is not mounted, you can probably mount it with: mount -t sysfs sysfs /sys
This program cannot continue without a working sysfs.

**Comment by Mister-X-** [comment]
This bug report lacks the information requested in bug reports. It is unactionable for us. Update it with the requested information, then reopen it.
