### ISSUE TITLE
deauthentication attack not work on WPA3

### ISSUE THREAD

**Issue by 354169679** [aircrack-ng/aircrack-ng#2539]

**Comment by Mister-X-** [comment]
First of all, your bug is lacking all the information required. Don't do this again.

WPA3 has 802.11w (aka Protected Management Frames, PMF), which authenticate deauthentication. So regular deauth won't work.

**Comment by 354169679** [comment]
> First of all, your bug is lacking all the information required. Don't do this again.
> 
> WPA3 has 802.11w (aka Protected Management Frames, PMF), which authenticate deauthentication. So regular deauth won't work.

OK,Thanks.
