### ISSUE TITLE
airmon-ng crash

### ISSUE THREAD

**Issue by TaraDaReal** [aircrack-ng/aircrack-ng#2549]
# Defect Report

## Issue type

- [x] Defect - Crash
- [x] Defect - Unexpected behavior (obvious or confirmed in the GitHub Discussions)

## System information

- OS Name: Debian
- OS Version: 11
- Kernel version: Linux localhost 4.14.116 #1 SMP PREEMPT Mon May 16 11:02:17 CST 2022 aarch64 GNU/Linux
- CPU: lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory.
- Wireless card and chipset (if relevant): unable to initialize libusb: -99

## Aircrack-ng version

- Version: 1.6
- Commit Revision hash:

## Defect

airmon-ng crashes.

### Details
ls: cannot access '/sys/class/net': No such file or directory                                   PHY     Interface       Driver          Chipset                                                 null    wlan0           ??????          non-mac80211 device? (report this!) 

### How to reproduce the issue

I dont know.

**Comment by Mister-X-** [comment]
1.6 is a very old release. Update at least to 1.7. If it still is a problem there, then try current git. If current git is a problem, reopen and update this bug report.

**Comment by TaraDaReal** [comment]
Updated to 1.7
Same behaviour
