### ISSUE TITLE
Update: #2549

### ISSUE THREAD

**Issue by TaraDaReal** [aircrack-ng/aircrack-ng#2550]
Update from #2549.
Updated to 1.7 Same behaviour.

root@localhost ~# airmon-ng                     
ls: cannot access '/sys/class/net': No such file or directory
PHY     Interface       Driver          Chipset                                                 null    wlan0           ??????          non-mac80211 device? (report this!)

**Comment by ZeroChaos-** [comment]
Relevant system details in previous bug https://github.com/aircrack-ng/aircrack-ng/issues/2549

**Comment by ZeroChaos-** [comment]
Your system appears to be horribly broken in ways which are not explained in your bug.  `lscpu` is an absolutely standard utility and even that fails.  More telling is that `lscpu` fails for exactly the same reason as airmon-ng, sysfs appears to be broken.  I have added early checks for broken sysfs but I can't even add meaningful output without knowing why sysfs is broken.    Can you maybe provide the output of `mount | grep sys` and provide anything special or different about your system beyond the debian 11 norms?

**Comment by TaraDaReal** [comment]
The only difference is its running On Termux. Everything else seems fine. May that be the cause?

**Comment by ZeroChaos-** [comment]
Running on android with an android kernel.  Yes, that's 100% the cause.  I don't know what cause /sys to not include /sys/class/net but it's not going to be supported without that path available; it's simply needed for too many different functionalities.

**Comment by TaraDaReal** [comment]
Well, kali nethunter should work. Thats why its designed. PEN testing on android rootless.
