### ISSUE TITLE
password not found aircrack-ng 1.7 termux

### ISSUE THREAD

**Issue by boo6ster** [aircrack-ng/aircrack-ng#2552]
sometimes it happens that the victim will mistakenly enter the wrong wifi password, aircrack has a bug and will never find the correct password if there are two handshakes from different devices for the same network in the .cap file from airodump-ng, for example one good and one bad (incomplete - wrong pass)

**Comment by Mister-X-** [comment]
That is why cleaning up the PCAP file to select a complete 4-way handshake is recommended. Check out the WPA capture analysis in our wiki.

Aircrack-ng can deal with less than 4 EAPOL frames, which is great. However, this leads to issues like that.

**Comment by boo6ster** [comment]
wpaclean delete complete handshake and left incomplete handshake :(
i must use editcap to delete packets number with eapol 1/4 and 2/4
