### ISSUE TITLE
 the bssid and channel name not show in kali what can i do ?

### ISSUE THREAD

**Issue by gk123r** [aircrack-ng/aircrack-ng#2567]
### Discussed in https://github.com/aircrack-ng/aircrack-ng/discussions/2430

<div type='discussions-op-text'>

<sup>Originally posted by **DonInSF** February 12, 2023</sup>
Greetings,
Newbie here. Running Kali 5.18.0 on persistent USB on Macbook Pro.
Using an Alfa AWUS036ACHM and am unable to obtain a handshake on my own 5GHz wireless network.
Output of airmon-ng indicates I'm using mt76x0u driver for the AWUS036ACHM.
I have used `sudo airmon-ng check kill` to stop wpa_supplicant and NetworkManager.
iwconfig indicates AWUS036ACHM is in monitor mode (wlan1mon) after starting with airmon-ng, as well as using 5.765 GHz frequency.
I also brought my MacBooks internal wireless card down with `sudo ifconfig wlan0 down`, as I read that this could interfere.
After determining BSSID, client MAC address, and channel by using airodump-ng, I ran `sudo airodump-ng -c 153 --bssid xx:xx:xx:xx:xx:xx -w filename wlan1mon` in one terminal window, and `sudo aireplay-ng -0 0 -a xx:xx:xx:xx:xx:xx -c aa:aa:aa:aa:aa:aa wlan1mon`, where xx:xx:xx:xx:xx:xx is AP, aa:aa:aa:aa:aa:aa is client (my other computer), and 153 is the channel.
After letting it run for about a minute, while simultaneously clicking around the web on the client machine, the aireplay window indicates that DeAuth packets are being sent, but the airodump window does not recognize any handshake attempts.
I've brought my kali box and AWUS036ACHM right next to the AP as well as a couple other locations in the apartment.
What am I doing incorrectly?
Thank you.

</div>

**Comment by aircrack-ng** [comment]
Not a bug. It's a discussion.

**Comment by gk123r** [comment]
Yesh , thanks

**Comment by 09Farhan** [comment]
I've got the same issue help me out!
