### ISSUE TITLE
Authenticate using the Wifi password if it is known - Aireplay-ng

### ISSUE THREAD

**Issue by reaveruser** [aircrack-ng/aircrack-ng#2613]
Please add an option in aireplay-ng to authenticate using the actual correct Wifi password so we can make more test with getting deauthentication packets.

I think it is very useful for lots of test, but I need it to recover my pin code using reaver, as I know the wifi password, I want to try to authenticate using the correct actual wifi password.

I think a lot will find this feature useful

Thanks

**Comment by Mister-X-** [comment]
wpa_supplicant should be able to do that. Reopen the ticket if it doesn't.
