### ISSUE TITLE
airodump-ng with RT2870/RT3070 and kernel 6.9 list only channel 1 stations 

### ISSUE THREAD

**Issue by sleeplessaa** [aircrack-ng/aircrack-ng#2614]
Hello team, 

airodump-ng with chipset Ralink RT2870/RT3070 and kernel 6.9 list only channel 1 stations
even scan with enabled filter of specific different channel or scan all channels.

There is only stations with CH 1 column in the output list.

cat /etc/issue Debian GNU/Linux 12 \n \l
uname -a Linux 6.9.0
aricrack-ng 1.7 compiled from source
driver rt2800usb with firmware rt2870.bin from package firmware-misc-nonfree version 20230210-5

airodump-ng  and driver iwlwifi for chipset Intel there is no such issue 
and all different stations with their channels appeared successfully.

Anyone with the same problem ? 

Regards

**Comment by ZerBea** [comment]
This is a Linux kernel bug and it was reported here:
https://bugzilla.kernel.org/show_bug.cgi?id=218884
It might be useful to report your problems / confirm the bug there as well.
The more people it affects, the sooner it will be fixed.

**Comment by sleeplessaa** [comment]
Thank you for your answer.

Interesting is that not all drivers are affected. iwlwifi works and can switch channels as expected.

The bug report said : 
> Let's mark monitor mode of kernel 6.9.x as broken and set focus on 6.10?

Just asking, what about 6.10-rc3, Is there any fix ?

Regards

**Comment by ZerBea** [comment]
Is packet injection working too on iwlwifi? I don't have such a device and can't test it.

I'm monitoring the wireless mailing list:
https://patchwork.kernel.org/project/linux-wireless/list/
There are a lot of changes regarding iwlwifi. That could be the reason why it is working.

I have not tested 6.10-rc3. Maybe the recent changes fixed the bug - maybe there are some new ones?

Regards
Mike

**Comment by sleeplessaa** [comment]
> Is packet injection working too on iwlwifi?

Yes, confirm. Packet injection works with iwlwifi and kernel 6.9.0.

**Comment by ZerBea** [comment]
Thanks.
Would be great, if you confirm that iwlwifi is working on bugzilla.kernel.org
Maybe it is helpful to discover the bug exactly.

For me it doesn't make sense to hunt for the bug as long as mac80211 receive changes nearly every day.
https://bugzilla.kernel.org/show_bug.cgi?id=218884#c16
May hardware is a way too slow to compile the kernel every day.  Bisecting from 6.8 to 6.9 took me several days.

BTW:
Does airodump-ng still use deprecated wireless extensions?
`$ sudo dmesg | grep wireless`

**Comment by sleeplessaa** [comment]
> BTW: Does airodump-ng still use deprecated wireless extensions? `$ sudo dmesg | grep wireless`

One single roll in dmesg output :
[   47.267771] warning: `iwconfig' uses wireless extensions which will stop working for Wi-Fi 7 hardware; use nl80211

**Comment by Mister-X-** [comment]
By default, no. You have to specify a flag to compile it in airodump-ng. If you have any further question, it may be better to use the [discussion](https://github.com/aircrack-ng/aircrack-ng/discussions) rather than a bug report. Not that it bothers me but so that makes more sense.

I'll close this bug as it's not related to airodump-ng but due to a bug in a driver.
