### ISSUE TITLE
Use other DB for airolib-ng

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#586]
**Reported by misterx on 26 Feb 2009 22:06 UTC**

We already have sqlite for airolib-ng but we could have more than 1 DB type for it and thus have an dbdep, a library to have common functions access to all types of DB.

Here are a few DB:
  * HamsterDB, Embedded DB: http://hamsterdb.com/
  * MySQL
  * PostgreSQL
  * Oracle
  * ...

**Comment by aircrack-ng** [comment]
**Comment by cruppstahl on 26 Feb 2009 22:06 UTC**

i'm the hamsterdb author. if you need any information or assistance, please don't hesitate to get in touch: chris at crupp dot de

**Comment by aircrack-ng** [comment]
**Modified by misterx on 26 Feb 2009 22:06 UTC**

**Comment by frankenstein91** [comment]
I apologize for contributing to such an old ticket. I would also be interested in supporting MySQL. You could so easily create a way for multiple devices to work on one rainbowtable.
