### ISSUE TITLE
WZCook for Vista

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#589]
**Reported by adam1 0 on 28 Feb 2009 18:50 UTC**

I have windows vista and when I opened up wzcook it gave me the following:
  Fatal: RegOpenKey(Software\Microsoft\WZCSVC\Parameters\Interfaces) failed

Please help me on this I would very much appreciate it. Thank You

**Comment by aircrack-ng** [comment]
**Modified by misterx on 28 Feb 2009 18:50 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 28 Feb 2009 18:50 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 28 Feb 2009 18:50 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 28 Feb 2009 18:50 UTC**

**Comment by aircrack-ng** [comment]
**Comment by Kabindra on 28 Feb 2009 18:50 UTC**

Where can i get the changed one for windows vista. I am having the same problem

**Comment by aircrack-ng** [comment]
**Comment by evanejk on 28 Feb 2009 18:50 UTC**

I'm having the same problem.

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 28 Feb 2009 18:50 UTC**

I am running windows 7, and i keep getting the error message whenever I launch WZCOOK. I am running the program as an administrator.
  Fatal: RegOpenKey(Software\Microsoft\WZCSVC\Parameters\Interfaces) failed
How can I fix / get past this? Any pointers?

**Comment by aircrack-ng** [comment]
**Comment by ansq on 28 Feb 2009 18:50 UTC**

Win7 x64 same error...
Compatibility and run as administrator set to all tools

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 28 Feb 2009 18:50 UTC**

even if you change the compatibility and run as administrator you get the same error Fatal: RegOpenKey?(Software\Microsoft\WZCSVC\Parameters\Interfaces) failed..

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 28 Feb 2009 18:50 UTC**

?(Software\Microsoft\WZCSVC\Parameters\Interfaces) failed..

**Comment by aircrack-ng** [comment]
**Modified by misterx on 28 Feb 2009 18:50 UTC**

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 28 Feb 2009 18:50 UTC**

Did anyone solve this? I am having the same error on Windows 10.

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 28 Feb 2009 18:50 UTC**

Only XP is supported. Vista and 10 need a different technique.

**Comment by avangardistic** [comment]
Fatal: RegOpenKey(Software\Microsoft\WZCSVC\Parameters\Interfaces) failed

i get this error n windows 10 64b
