### ISSUE TITLE
Airmon-ng batch mode

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#634]
**Reported by XayOn on 6 Jun 2009 17:58 UTC**

Airmon-ng gives a pretty human-readable output, but hard to handle on scripts.
It would be  great to  have a "batch" option allowing airmon to reply with 0, 1 or interface name (if  1, and creates a interface).

**Comment by aircrack-ng** [comment]
**Comment by misterx on 6 Jun 2009 17:58 UTC**

could you describe a bit more what you want? what will be the input/command, what does airmon-ng will have to do and what does it have to return? ...

**Comment by aircrack-ng** [comment]
**Comment by XayOn on 6 Jun 2009 17:58 UTC**

I left that part opened, I mean, no requeriments, just to make it scriptable.

repliying with 0 or 1 part will be another ticket, as I've seen airmon-ng doesn't handle errors produced by tools it launches (I mean, it should check $? and exit with non-zero status if $? not zero).
then, when script finished, it should exit 0; Thay way exit status can be checked within other tools.
For that, just checking $? at exit is not an option, since it launches more things, it can even be worked like first_command && second_command foreach command-group in airmon-ng, (it will be the easier way, but may be not the best)

The other thing is MAC80211 specific, just if <something> specified as arg (as if ${4} == "quiet", for example) reply just with monitor mode created interface (MONDEV).

**Comment by aircrack-ng** [comment]
**Modified by misterx on 6 Jun 2009 17:58 UTC**

**Comment by ZeroChaos-** [comment]
Honestly, I wouldn't typically advise using airmon-ng in scripts.  Different drivers are handled completely differently (some need new interfaces created, some don't) and just giving an exit code for success vs failure is unlikely to help.  that said, already an exit 1 is used for all failure conditions, so good luck
