### ISSUE TITLE
aircrack-ng throws floating point exception (sigfpe) in aircrack-ptw-lib.c

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#672]
**Reported by wdoekes on 15 Sep 2009 21:22 UTC**

In aircrack-ptw-lib.c in function correct() on line 248, k is set to rand() % 0 if state->sessions_collected == 10. The modulo 0 raises a SIGFPE.

(Some crazy proxy/security feature prevents me from posting the gdb data inline. It is attached as .txt file instead.)

**Comment by aircrack-ng** [comment]
**Modified by misterx on 15 Sep 2009 21:22 UTC**

**Comment by aircrack-ng** [comment]
**Comment by contact on 15 Sep 2009 21:22 UTC**

I made a patch that removes the need of k, and so the risk that it could do a division by zero. 

Assigning to k a precise value was useless. I replaced k by 0 and it works well. 

The patch is attached to this report, it's also available on download.paulk.fr/aircrack-ng/aircrack-ptw-lib-divbyzero.patch

**Comment by aircrack-ng** [comment]
**Comment by misterx on 15 Sep 2009 21:22 UTC**

Would you have a capture file that triggers this bug?

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 15 Sep 2009 21:22 UTC**

Replying to [misterx](comment:3):
> Would you have a capture file that triggers this bug?

I had one but I deleted it. Anyway, it's clear that 
k = rand()%(state->sessions_collected-10); 
will make a division by zero if state->sessions_collected == 10. I had that bug on a capture file with 10 IVS.

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 15 Sep 2009 21:22 UTC**

Try using different wordlist. It worked for me.

**Comment by michaelknap** [comment]
I should have checked the github issues before making the report. 
This line will cause division by zero if the number of IVs is exactly 10 but it will cause segmentation fault via out-of-bound memory access if the number of IVs is  >= 3 < 10. The random value generated by rand_u32 after reminder by negative number will be passed as index to an array causing crash in consecutive rc4test_amd64_sse2 but can potentially cause access to a valid memory address with unpredictable outcome.
![image](https://github.com/aircrack-ng/aircrack-ng/assets/145442568/8618dafe-dd94-4205-9a43-f0275e2440d7)

This line will cause the crash by trying to access invalid memory in an optimized routine:
// save keystream variable
		"movq %q6, " keystream_ "       \n\t"
		
In some cases the random value may cause it to access valid memory address which would ultimately lead to undefined behavior or worse. 

Important to note that executing aircrack with a -w wordlist flag will cause this routine to be bypassed and instead complain about minimum 4 IVs.

![image](https://github.com/aircrack-ng/aircrack-ng/assets/145442568/9a8d0864-463f-4640-b3ca-3a6bdb3dbfce)

**Comment by Mister-X-** [comment]
Don't worry. The only time it's frown upon is when the bug report is exactly the same as the email; I already receive emails notifications from GitHub.

In this case, your email is not only different, but it is also well written.
