### ISSUE TITLE
Add SSID mask

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#757]
**Reported by anonymous on 19 Jun 2010 00:45 UTC**

It would be useful to be able to specify a mask for the SSID.

**Comment by gemesa** [comment]
I think this would be redundant since `--essid-regex` option is available. You can use that as a "mask", to match SSIDs starting with the same substring for example.

**Comment by Mister-X-** [comment]
Agreed.
