### ISSUE TITLE
More accurate chipset definition in airmon-ng

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#765]
**Reported by misterx on 21 Jul 2010 16:42 UTC**

Airmon-ng currently display the chipset and this is "linked" to the driver name.

Use other methods to display more accurately the chipset of the card (a driver supports several chipsets):

  - lsusb/lspci
  - dmesg (firmware name, ...)
  - ...

**Comment by aircrack-ng** [comment]
**Comment by misterx on 21 Jul 2010 16:42 UTC**

For wl12xx, check for the name of the firmware to load:

```
wl12xx spi4.0: firmware: requesting wl1251-fw.bin
```

and/or maybe if needed grep dmesg and look for 1251/1271

**Comment by aircrack-ng** [comment]
**Comment by misterx on 21 Jul 2010 16:42 UTC**

Same idea can be used for wl1271:

```
wl1271_sdio mmc0:0001:2: firmware: requesting wl1271-fw.bin
wl1271_sdio mmc0:0001:2: firmware: requesting wl1271-nvs.bin
```

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 21 Jul 2010 16:42 UTC**

ath5k:

```
[   13.471695] ath5k phy0: Atheros AR2425 chip found (MAC: 0xe2, PHY: 0x70)
```

**Comment by aircrack-ng** [comment]
**Comment by misterx on 21 Jul 2010 16:42 UTC**

Some drivers don't have a link with the phy (especially closed source drivers), so there might be a need to find out on what USB port is linked a specific driver.

**Comment by ZeroChaos-** [comment]
we provide everything lspci and lsusb can provide, absent specific requests for specific info, we can close this general bug
