### ISSUE TITLE
Allow filtering for ESSID

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#776]
**Reported by Matthias Schiffer  mschiffer on 21 Aug 2010 16:40 UTC**

Trying to scan the wireless networks of my university, I found it necessary to add an ESSID filter to airodump, as the network consists of several of APs working on the same ESSID, but the number of other network made it difficult to focus on the right networks.

The attached patch adds an --essid option to airodump-ng. It can be used several times to show multiple ESSIDs at once; filtering for an empty string will show networks with hidden ESSIDs.

Without specifying -a, the --essid filter will show all unassociated clients, but only those associated clients which are connected to an AP with the specified ESSIDs.

I'm also planning to add an regex ESSID filter, so scanning for default network names will be possible.

**Comment by aircrack-ng** [comment]
**Comment by Matthias Schiffer  mschiffer on 21 Aug 2010 16:40 UTC**

Hi,
I've attached an updated version of the patch, as the old one didn't apply cleanly anymore.

Also, I've added support for filtering for ESSIDs by regular expressions; to not require libprce by default, this must be enabled with PRCE=true during build.

The --essid parameter works like explained in my last post. The --essid-regex parameter can be used to filter by regular expressions; it can be used only once, as it is possible to search for the conjunction of two regex by using | (--essid-regex 'A|B' will filter for ESSIDs containing an A or a B). If both --essid parameters and --essid-regex are given, all networks are shown that match one of the --essid parameters or the regex.

I'd be great if I could at least get a reply this time, so I'm motivated to contribute further to this cool project :)

**Comment by aircrack-ng** [comment]
**Comment by Ton on 21 Aug 2010 16:40 UTC**

Exactly what i'm looking for Mschiffer.
I will be trying this patch asap.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 21 Aug 2010 16:40 UTC**

I'll be testing it in the next few days. The only thing that's missing right now is some documentation in the manpages.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 21 Aug 2010 16:40 UTC**

Committed. aircrack-ng/aircrack-ng@c5e9b72aca03feeeb8fe2aa78fa34e10ec43c903.

**Comment by larryralphs** [comment]
If I can, can ask another regex question?
I want to not display records where the ESSID is not set. That is it contains something like
<length: 16>
I've tried a few but no success. Any ideas on a regex that will filter out these ESSIDs?

Thanks
