### ISSUE TITLE
Added --ignore-negative-one for airodump-ng

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#895]
**Reported by wims on 1 Jul 2011 08:09 UTC**

If a user havent patched his kernel / compat-wireless airodump-ng would always display fixed channel <interface> -1. This could be undesirable when one is deauthing clients for WPA attack, since airodump-ng would not display the handshake received message. With this new option airodump-ng would simply not display the fixed channel <interface> -1 message. 

There are two ways to set the option, either with --ignore-negative-one or just -N

**Comment by aircrack-ng** [comment]
**Comment by Jano on 1 Jul 2011 08:09 UTC**

The duplication of the existing patch of Aireplay-ng (option --ignore-negative-one) on Airodump-ng --> file "airodump-ng.c" is broken/incorrect format.

Jano

**Comment by aircrack-ng** [comment]
**Comment by wims on 1 Jul 2011 08:09 UTC**

I removed the option of using -N, now only --ignore-negative-one works. I also merged the patch files into a single patch. Added entry for the manpage as well

**Comment by aircrack-ng** [comment]
**Comment by Jano on 1 Jul 2011 08:09 UTC**

Patch does not work:

OS: Ubuntu

Kernel: 2.6.38-10

Kernel: 3.0.0

Drivers: rtl8187/mac80211 without patch


VirtualBox: Ubuntu Natty

Kernel: 2.6.38-8

Drivers: rtl8187/mac80211 without patch


```
jano:~/aircrack-ng/src$ grep -r "G.ignore_negative_one\|--ignore-negative-one" airodump-ng.c 
"      --ignore-negative-one : Removes the message that says\n"
        if(G.ignore_negative_one == 1 && chan==-1) return 0;
        {"ignore-negative-one", 0, &G.ignore_negative_one, 1},

```


```
 CH  6 ][ Elapsed: 4 s ][ 2011-07-04 02:43 ][ fixed channel mon0: -1                        
                                                                                            
 BSSID              PWR RXQ  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID         
                                                                                            
 00:xx:xx:xx:xx:xx  -48  75       57        0    0   6  54e. WPA2 CCMP   PSK  <length:  0>  
 E0:xx:xx:xx:xx:xx  -57  90       68        0    0   6  54e  WPA2 CCMP   PSK  -------------  
 00:xx:xx:xx:xx:xx  -73  78       58        0    0   6  54   WPA  TKIP   PSK  -------------
                                                                                            
 BSSID              STATION            PWR   Rate    Lost    Frames  Probe                  
                                                                                            
 00:xx:xx:xx:xx:xx  00:xx:xx:xx:xx:xx   -9    0 -54     14       14  
```

Jano

**Comment by aircrack-ng** [comment]
**Comment by Jano on 1 Jul 2011 08:09 UTC**

Sorry, It is my mistake, I swapped the correct PC for test.

The patch works.

Jano

**Comment by aircrack-ng** [comment]
**Comment by Zero Chaos on 1 Jul 2011 08:09 UTC**

Committed revision 1917

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 1 Jul 2011 08:09 UTC**

Hello.

Sorry but I am new here and I have the -1 channel problem.

I already downloaded de patch, but how do I use it? I don't know what to do with the file...

Excuse my ignorance...

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 1 Jul 2011 08:09 UTC**

Replying to [anonymous](comment:6):
> Hello.
> 
> Sorry but I am new here and I have the -1 channel problem.
> 
> I already downloaded de patch, but how do I use it? I don't know what to do with the file...
> 
> Excuse my ignorance...
> 

Hi,
To use the patch (as far as I know, since I'm a newbie too) type:
patch -Np0 -i <patchName>

-N  --forward  Ignore patches that appear to be reversed or already applied.
-p NUM  --strip=NUM  Strip NUM leading components from file names.
-i PATCHFILE  --input=PATCHFILE  Read patch from PATCHFILE instead of stdin.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 1 Jul 2011 08:09 UTC**

THIS IS NOT A FORUM AND THERE'S A TUTORIAL IN THE WIKI FOR THAT.

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 1 Jul 2011 08:09 UTC**

Replying to [misterx](comment:8):
> THIS IS NOT A FORUM AND THERE'S A TUTORIAL IN THE WIKI FOR THAT.

A link to the tutorial would have been usefu

**Comment by aircrack-ng** [comment]
**Comment by misterx on 1 Jul 2011 08:09 UTC**

Bottom right of the index page of our website.

**Comment by anandharaj-dotworld** [comment]
$ sudo aireplay-ng --deauth 0 -a 40:F5:20:3E:66:3B --ignore-negative-one wlan1 
17:56:22  Waiting for beacon frame (BSSID: 40:F5:20:3E:66:3B) on channel 7
17:56:32  No such BSSID available.

-> I don't know why i getting "No such BSSID available"

**Comment by anandharaj-dotworld** [comment]
how to deauth negative energy

**Comment by spiral009** [comment]
Where is that fukin kernel patch!
